{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/audiosource\/createstream()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/audiosource\/createstream()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createStream","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"LocalAudioStream","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalAudioStream","preciseIdentifier":"c:objc(cs)SKWLocalAudioStream","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSource"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:objc(cs)SKWAudioSource(im)createStream","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createStream","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"LocalAudioStream","preciseIdentifier":"c:objc(cs)SKWLocalAudioStream","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"createStream","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"createStream()"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSource\/createStream()","interfaceLanguage":"swift"},"abstract":[{"text":"ストリームを作成します。","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSource":{"url":"\/documentation\/skywayroom\/audiosource","type":"topic","abstract":[{"text":"音声入力ソースの抽象クラス","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioSource","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSource","title":"AudioSource","navigatorTitle":[{"text":"AudioSource","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalAudioStream":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocalAudioStream"}],"url":"\/documentation\/skywayroom\/localaudiostream","role":"symbol","navigatorTitle":[{"text":"LocalAudioStream","kind":"identifier"}],"type":"topic","title":"LocalAudioStream","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalAudioStream","abstract":[{"type":"text","text":"LocalAudioStreamクラス"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSource/createStream()":{"url":"\/documentation\/skywayroom\/audiosource\/createstream()","type":"topic","abstract":[{"type":"text","text":"ストリームを作成します。"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createStream"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWLocalAudioStream","text":"LocalAudioStream"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSource\/createStream()","title":"createStream()","navigatorTitle":[{"kind":"identifier","text":"createStream"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createStream"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createStream","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalAudioStream","text":"SKWLocalAudioStream","preciseIdentifier":"c:objc(cs)SKWLocalAudioStream","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createStream","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSource\/title","value":"SKWAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSource\/fragments","value":[{"text":"SKWAudioSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSource\/navigatorTitle","value":[{"text":"SKWAudioSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalAudioStream\/title","value":"SKWLocalAudioStream"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalAudioStream\/fragments","value":[{"text":"SKWLocalAudioStream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalAudioStream\/navigatorTitle","value":[{"text":"SKWLocalAudioStream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSource~1createStream()\/title","value":"createStream"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSource~1createStream()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createStream","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}