{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAudioLevel"},{"text":"() -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/remoteaudiostream\/getaudiolevel()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/remoteaudiostream\/getaudiolevel()"]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"getAudioLevel","kind":"identifier"}],"title":"getAudioLevel()","externalID":"c:objc(cs)SKWRemoteAudioStream(im)getAudioLevel","symbolKind":"method","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAudioLevel","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"kind":"symbol","sections":[],"abstract":[{"text":"直近100msにおける最大音量を取得します（値の範囲：0.0-1.0）。","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteAudioStream"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteAudioStream\/getAudioLevel()","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteAudioStream":{"url":"\/documentation\/skywayroom\/remoteaudiostream","type":"topic","abstract":[{"text":"RemoteAudioStreamクラス","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RemoteAudioStream"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteAudioStream","title":"RemoteAudioStream","navigatorTitle":[{"kind":"identifier","text":"RemoteAudioStream"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteAudioStream/getAudioLevel()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAudioLevel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"\/documentation\/skywayroom\/remoteaudiostream\/getaudiolevel()","role":"symbol","navigatorTitle":[{"text":"getAudioLevel","kind":"identifier"}],"type":"topic","title":"getAudioLevel()","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteAudioStream\/getAudioLevel()","abstract":[{"text":"直近100msにおける最大音量を取得します（値の範囲：0.0-1.0）。","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"getAudioLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"getAudioLevel","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"identifier","text":"getAudioLevel"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteAudioStream\/title","value":"SKWRemoteAudioStream"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteAudioStream\/fragments","value":[{"text":"SKWRemoteAudioStream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteAudioStream\/navigatorTitle","value":[{"text":"SKWRemoteAudioStream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteAudioStream~1getAudioLevel()\/title","value":"getAudioLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteAudioStream~1getAudioLevel()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getAudioLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}