{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/publicationdelegate\/publication(_:connectionstatedidchange:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/publicationdelegate\/publication(_:connectionstatedidchange:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publication","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"publication","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Publication","text":"Publication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"connectionStateDidChange"},{"kind":"text","text":" "},{"text":"connectionState","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConnectionState","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState","preciseIdentifier":"c:@E@SKWConnectionState"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"publication","content":[{"type":"paragraph","inlineContent":[{"text":"Publication","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"接続状態"}],"type":"paragraph"}],"name":"connectionState"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/PublicationDelegate"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publication","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Publication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication"},{"text":", ","kind":"text"},{"text":"connectionStateDidChange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWConnectionState"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"publication:connectionStateDidChange:"}],"roleHeading":"Instance Method","symbolKind":"method","title":"publication(_:connectionStateDidChange:)"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/PublicationDelegate\/publication(_:connectionStateDidChange:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"このPublicationの接続状態が変化したときに発生するイベント"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ConnectionState":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionState"}],"url":"\/documentation\/skywayroom\/connectionstate","role":"symbol","navigatorTitle":[{"text":"ConnectionState","kind":"identifier"}],"type":"topic","title":"ConnectionState","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState","abstract":[{"type":"text","text":"接続状態"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationDelegate/publication(_:connectionStateDidChange:)":{"url":"\/documentation\/skywayroom\/publicationdelegate\/publication(_:connectionstatedidchange:)","navigatorTitle":[{"kind":"identifier","text":"publication:connectionStateDidChange:"}],"type":"topic","kind":"symbol","title":"publication(_:connectionStateDidChange:)","abstract":[{"text":"このPublicationの接続状態が変化したときに発生するイベント","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/PublicationDelegate\/publication(_:connectionStateDidChange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publication"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication"},{"text":", ","kind":"text"},{"text":"connectionStateDidChange","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SKWConnectionState","text":"ConnectionState","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Publication","kind":"identifier"}],"url":"\/documentation\/skywayroom\/publication","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Publication"}],"type":"topic","title":"Publication","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Publication","abstract":[{"type":"text","text":"Publication"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationDelegate":{"url":"\/documentation\/skywayroom\/publicationdelegate","navigatorTitle":[{"kind":"identifier","text":"PublicationDelegate"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Publicationイベントデリゲート"}],"title":"PublicationDelegate","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/PublicationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PublicationDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"publication:connectionStateDidChange:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"publication:connectionStateDidChange:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"publication:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKWPublication","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Publication","preciseIdentifier":"c:objc(cs)SKWPublication"},{"text":" *) ","kind":"text"},{"text":"publication","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"connectionStateDidChange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKWConnectionState","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState","preciseIdentifier":"c:@E@SKWConnectionState"},{"text":") ","kind":"text"},{"text":"connectionState","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Publication"}]}],"name":"publication"},{"content":[{"inlineContent":[{"type":"text","text":"接続状態"}],"type":"paragraph"}],"name":"connectionState"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/title","value":"SKWConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/fragments","value":[{"kind":"identifier","text":"SKWConnectionState"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/navigatorTitle","value":[{"text":"SKWConnectionState","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationDelegate~1publication(_:connectionStateDidChange:)\/title","value":"publication:connectionStateDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationDelegate~1publication(_:connectionStateDidChange:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"publication:connectionStateDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication\/title","value":"SKWPublication"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication\/fragments","value":[{"text":"SKWPublication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication\/navigatorTitle","value":[{"kind":"identifier","text":"SKWPublication"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationDelegate\/title","value":"SKWPublicationDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationDelegate\/fragments","value":[{"text":"SKWPublicationDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationDelegate\/navigatorTitle","value":[{"text":"SKWPublicationDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}