{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/remoteroommemberdelegate\/remoteroommember(_:didsubscribepublicationof:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/remoteroommemberdelegate\/remoteroommember(_:didsubscribepublicationof:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteRoomMember"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"member","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RemoteRoomMember","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RemoteRoomMember"},{"kind":"text","text":", "},{"text":"didSubscribePublicationOf","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscription","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","text":"RoomSubscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Member","type":"text"}]}],"name":"member"},{"content":[{"inlineContent":[{"type":"text","text":"Subscribeした時のSubscription"}],"type":"paragraph"}],"name":"subscription"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate"]]},"metadata":{"externalID":"c:@M@SkyWayRoom@objc(pl)RemoteRoomMemberDelegate(im)remoteRoomMember:didSubscribePublicationOf:","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteRoomMember","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RemoteRoomMember","text":"RemoteRoomMember","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSubscribePublicationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"remoteRoomMember:didSubscribePublicationOf:"}],"roleHeading":"Instance Method","symbolKind":"method","title":"remoteRoomMember(_:didSubscribePublicationOf:)"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate\/remoteRoomMember(_:didSubscribePublicationOf:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"RemoteRoomMemberがPublicationをSubscribeした時にコールされます。"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMemberDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"RemoteRoomMemberイベントデリゲート"}],"title":"RemoteRoomMemberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteRoomMemberDelegate"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate","navigatorTitle":[{"kind":"identifier","text":"RemoteRoomMemberDelegate"}],"role":"symbol","url":"\/documentation\/skywayroom\/remoteroommemberdelegate","type":"topic"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember":{"url":"\/documentation\/skywayroom\/remoteroommember","navigatorTitle":[{"kind":"identifier","text":"RemoteRoomMember"}],"type":"topic","kind":"symbol","title":"RemoteRoomMember","abstract":[{"text":"他のSDKで生成されたRoomMember","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RemoteRoomMember","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMemberDelegate/remoteRoomMember(_:didSubscribePublicationOf:)":{"url":"\/documentation\/skywayroom\/remoteroommemberdelegate\/remoteroommember(_:didsubscribepublicationof:)","type":"topic","abstract":[{"type":"text","text":"RemoteRoomMemberがPublicationをSubscribeした時にコールされます。"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteRoomMember","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RemoteRoomMember","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RemoteRoomMember"},{"text":", ","kind":"text"},{"text":"didSubscribePublicationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate\/remoteRoomMember(_:didSubscribePublicationOf:)","title":"remoteRoomMember(_:didSubscribePublicationOf:)","navigatorTitle":[{"text":"remoteRoomMember:didSubscribePublicationOf:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscription":{"url":"\/documentation\/skywayroom\/roomsubscription","navigatorTitle":[{"kind":"identifier","text":"RoomSubscription"}],"type":"topic","kind":"symbol","title":"RoomSubscription","abstract":[{"text":"Room SDK におけるSubscription","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RoomSubscription","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"remoteRoomMember:didSubscribePublicationOf:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"remoteRoomMember:didSubscribePublicationOf:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"remoteRoomMember:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RemoteRoomMember","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RemoteRoomMember"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"member"},{"kind":"text","text":" "},{"text":"didSubscribePublicationOf:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","text":"RoomSubscription","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"subscription","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Member"}]}],"name":"member"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Subscribeした時のSubscription"}]}],"name":"subscription"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/title","value":"RemoteRoomMemberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/fragments","value":[{"kind":"identifier","text":"RemoteRoomMemberDelegate"}]},{"op":"replace","value":[{"text":"RemoteRoomMemberDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/navigatorTitle"},{"op":"replace","value":"RemoteRoomMember","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/fragments","value":[{"kind":"identifier","text":"RemoteRoomMember"}]},{"op":"replace","value":[{"kind":"identifier","text":"RemoteRoomMember"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate~1remoteRoomMember(_:didSubscribePublicationOf:)\/title","value":"remoteRoomMember:didSubscribePublicationOf:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate~1remoteRoomMember(_:didSubscribePublicationOf:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"remoteRoomMember:didSubscribePublicationOf:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/title","value":"RoomSubscription"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/fragments","value":[{"text":"RoomSubscription","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/navigatorTitle","value":[{"text":"RoomSubscription","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}