{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"subscriptionID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"]},{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"subscriptionID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"中止するSubscriptionのID"}],"type":"paragraph"}],"name":"subscriptionID"},{"content":[{"inlineContent":[{"type":"text","text":"完了コールバック"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/skywayroom\/localperson\/unsubscribe(subscriptionid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/localperson\/unsubscribe(subscriptionid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"unsubscribeWithSubscriptionID:completion:"}],"title":"unsubscribe(subscriptionID:completion:)","symbolKind":"method","externalID":"c:objc(cs)SKWLocalPerson(im)unsubscribeWithSubscriptionID:completion:","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsubscribe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"subscriptionID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Subscribeを中止します。"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPerson"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPerson\/unsubscribe(subscriptionID:completion:)","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPerson/unsubscribe(subscriptionID:completion:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsubscribe","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"subscriptionID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/skywayroom\/localperson\/unsubscribe(subscriptionid:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unsubscribeWithSubscriptionID:completion:"}],"type":"topic","title":"unsubscribe(subscriptionID:completion:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPerson\/unsubscribe(subscriptionID:completion:)","abstract":[{"type":"text","text":"Subscribeを中止します。"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWLocalPersonUnsubscribeCompletion":{"url":"\/documentation\/skywayroom\/skwlocalpersonunsubscribecompletion","navigatorTitle":[{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWLocalPersonUnsubscribeCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWLocalPersonUnsubscribeCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPerson":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalPerson"}],"url":"\/documentation\/skywayroom\/localperson","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocalPerson"}],"type":"topic","title":"LocalPerson","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPerson","abstract":[{"text":"このSDKで生成されたLocalMember","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"unsubscribeWithSubscriptionID:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unsubscribeWithSubscriptionID:completion:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"unsubscribeWithSubscriptionID:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"subscriptionID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWLocalPersonUnsubscribeCompletion","preciseIdentifier":"c:SKWLocalPerson.h@T@SKWLocalPersonUnsubscribeCompletion"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"中止するSubscriptionのID"}],"type":"paragraph"}],"name":"subscriptionID"},{"content":[{"inlineContent":[{"type":"text","text":"完了コールバック"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson~1unsubscribe(subscriptionID:completion:)\/title","value":"unsubscribeWithSubscriptionID:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson~1unsubscribe(subscriptionID:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unsubscribeWithSubscriptionID:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalPersonUnsubscribeCompletion\/title","value":"SKWLocalPersonUnsubscribeCompletion"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalPersonUnsubscribeCompletion\/fragments","value":[{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalPersonUnsubscribeCompletion\/navigatorTitle","value":[{"kind":"identifier","text":"SKWLocalPersonUnsubscribeCompletion"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson\/title","value":"SKWLocalPerson","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson\/fragments","value":[{"text":"SKWLocalPerson","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson\/navigatorTitle","value":[{"kind":"identifier","text":"SKWLocalPerson"}]}]}]}