{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberSubscriptionListDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"member","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"RoomMember","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMember","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomMember"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"member","content":[{"type":"paragraph","inlineContent":[{"text":"Member","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/roommemberdelegate\/membersubscriptionlistdidchange(_:)"]},{"paths":["\/documentation\/skywayroom\/roommemberdelegate\/membersubscriptionlistdidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"memberSubscriptionListDidChange:","kind":"identifier"}],"title":"memberSubscriptionListDidChange(_:)","externalID":"c:@M@SkyWayRoom@objc(pl)RoomMemberDelegate(im)memberSubscriptionListDidChange:","symbolKind":"method","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberSubscriptionListDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomMember","text":"RoomMember"},{"kind":"text","text":")"}]},"kind":"symbol","sections":[],"abstract":[{"text":"RoomMemberがSubscribeしているStreamの数が変化した後にコールされます。","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate\/memberSubscriptionListDidChange(_:)","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMember":{"url":"\/documentation\/skywayroom\/roommember","navigatorTitle":[{"text":"RoomMember","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Roomに入室しているMemberの抽象クラス","type":"text"}],"title":"RoomMember","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMember","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomMember"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoomMemberDelegate","kind":"identifier"}],"url":"\/documentation\/skywayroom\/roommemberdelegate","role":"symbol","navigatorTitle":[{"text":"RoomMemberDelegate","kind":"identifier"}],"type":"topic","title":"RoomMemberDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate","abstract":[{"text":"RoomMemberイベントデリゲート","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate/memberSubscriptionListDidChange(_:)":{"abstract":[{"text":"RoomMemberがSubscribeしているStreamの数が変化した後にコールされます。","type":"text"}],"title":"memberSubscriptionListDidChange(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberSubscriptionListDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RoomMember","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomMember","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate\/memberSubscriptionListDidChange(_:)","navigatorTitle":[{"text":"memberSubscriptionListDidChange:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/roommemberdelegate\/membersubscriptionlistdidchange(_:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"memberSubscriptionListDidChange:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"memberSubscriptionListDidChange:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"memberSubscriptionListDidChange:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMember","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomMember","text":"RoomMember","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"member","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Member"}]}],"name":"member"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMember\/title","value":"RoomMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMember\/fragments","value":[{"text":"RoomMember","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"RoomMember"}],"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMember\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate\/title","value":"RoomMemberDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate\/fragments","value":[{"text":"RoomMemberDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"RoomMemberDelegate"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate\/navigatorTitle","op":"replace"},{"value":"memberSubscriptionListDidChange:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate~1memberSubscriptionListDidChange(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"memberSubscriptionListDidChange:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate~1memberSubscriptionListDidChange(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}