{"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"ChannelDelegate Implementations","modules":[{"name":"SkyWayRoom"}],"role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"kind":"article","variants":[{"paths":["\/documentation\/skywayroom\/room\/channeldelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/room\/channeldelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/ChannelDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didPublishStreamOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didSubscribePublicationOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUnpublishStreamOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUnsubscribePublicationOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUpdateMetadata:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:member:metadataDidUpdate:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:memberDidJoin:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:memberDidLeave:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publication:metadataDidUpdate:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publicationDidChangeToDisabled:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publicationDidChangeToEnabled:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelDidClose(_:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelMemberListDidChange(_:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelPublicationListDidChange(_:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelSubscriptionListDidChange(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:publicationDidChangeToDisabled:)":{"url":"\/documentation\/skywayroom\/room\/channel(_:publicationdidchangetodisabled:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"publicationDidChangeToDisabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publicationDidChangeToDisabled:)","title":"channel(_:publicationDidChangeToDisabled:)","navigatorTitle":[{"text":"channel:publicationDidChangeToDisabled:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:publication:metadataDidUpdate:)":{"url":"\/documentation\/skywayroom\/room\/channel(_:publication:metadatadidupdate:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Channel","preciseIdentifier":"c:objc(cs)SKWChannel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"publication","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Publication","preciseIdentifier":"c:objc(cs)SKWPublication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metadataDidUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publication:metadataDidUpdate:)","title":"channel(_:publication:metadataDidUpdate:)","navigatorTitle":[{"text":"channel:publication:metadataDidUpdate:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:memberDidLeave:)":{"url":"\/documentation\/skywayroom\/room\/channel(_:memberdidleave:)","navigatorTitle":[{"kind":"identifier","text":"channel:memberDidLeave:"}],"type":"topic","kind":"symbol","abstract":[],"title":"channel(_:memberDidLeave:)","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:memberDidLeave:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"memberDidLeave","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWMember","text":"Member","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channelPublicationListDidChange(_:)":{"url":"\/documentation\/skywayroom\/room\/channelpublicationlistdidchange(_:)","title":"channelPublicationListDidChange(_:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"channelPublicationListDidChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Channel","preciseIdentifier":"c:objc(cs)SKWChannel"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelPublicationListDidChange(_:)","type":"topic","navigatorTitle":[{"text":"channelPublicationListDidChange:","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:didUnsubscribePublicationOf:)":{"kind":"symbol","title":"channel(_:didUnsubscribePublicationOf:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Channel","preciseIdentifier":"c:objc(cs)SKWChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUnsubscribePublicationOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Subscription","preciseIdentifier":"c:objc(cs)SKWSubscription"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUnsubscribePublicationOf:)","navigatorTitle":[{"kind":"identifier","text":"channel:didUnsubscribePublicationOfSubscription:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/room\/channel(_:didunsubscribepublicationof:)"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:member:metadataDidUpdate:)":{"url":"\/documentation\/skywayroom\/room\/channel(_:member:metadatadidupdate:)","title":"channel(_:member:metadataDidUpdate:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"member","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWMember","text":"Member","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metadataDidUpdate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:member:metadataDidUpdate:)","type":"topic","navigatorTitle":[{"text":"channel:member:metadataDidUpdate:","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channelSubscriptionListDidChange(_:)":{"kind":"symbol","title":"channelSubscriptionListDidChange(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelSubscriptionListDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Channel","preciseIdentifier":"c:objc(cs)SKWChannel","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelSubscriptionListDidChange(_:)","navigatorTitle":[{"text":"channelSubscriptionListDidChange:","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/room\/channelsubscriptionlistdidchange(_:)"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:didPublishStreamOf:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPublishStreamOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication"},{"kind":"text","text":")"}],"url":"\/documentation\/skywayroom\/room\/channel(_:didpublishstreamof:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"channel:didPublishStreamOfPublication:"}],"type":"topic","title":"channel(_:didPublishStreamOf:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didPublishStreamOf:)","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channelMemberListDidChange(_:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelMemberListDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/room\/channelmemberlistdidchange(_:)","role":"symbol","navigatorTitle":[{"text":"channelMemberListDidChange:","kind":"identifier"}],"type":"topic","title":"channelMemberListDidChange(_:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelMemberListDidChange(_:)","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:didUnpublishStreamOf:)":{"url":"\/documentation\/skywayroom\/room\/channel(_:didunpublishstreamof:)","title":"channel(_:didUnpublishStreamOf:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUnpublishStreamOf"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUnpublishStreamOf:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:didUnpublishStreamOfPublication:"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:publicationDidChangeToEnabled:)":{"url":"\/documentation\/skywayroom\/room\/channel(_:publicationdidchangetoenabled:)","navigatorTitle":[{"kind":"identifier","text":"channel:publicationDidChangeToEnabled:"}],"type":"topic","kind":"symbol","title":"channel(_:publicationDidChangeToEnabled:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publicationDidChangeToEnabled:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Channel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel"},{"text":", ","kind":"text"},{"text":"publicationDidChangeToEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Publication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication"},{"kind":"text","text":")"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channelDidClose(_:)":{"title":"channelDidClose(_:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"channelDidClose","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Channel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelDidClose(_:)","navigatorTitle":[{"text":"channelDidClose:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/room\/channeldidclose(_:)","type":"topic"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:memberDidJoin:)":{"url":"\/documentation\/skywayroom\/room\/channel(_:memberdidjoin:)","title":"channel(_:memberDidJoin:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"memberDidJoin","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWMember","text":"Member","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:memberDidJoin:)","type":"topic","navigatorTitle":[{"text":"channel:memberDidJoin:","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Room"}],"url":"\/documentation\/skywayroom\/room","role":"symbol","navigatorTitle":[{"text":"Room","kind":"identifier"}],"type":"topic","title":"Room","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room","abstract":[{"text":"Roomクラス","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:didSubscribePublicationOf:)":{"url":"\/documentation\/skywayroom\/room\/channel(_:didsubscribepublicationof:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channel","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Channel","preciseIdentifier":"c:objc(cs)SKWChannel"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSubscribePublicationOf"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Subscription","preciseIdentifier":"c:objc(cs)SKWSubscription"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didSubscribePublicationOf:)","title":"channel(_:didSubscribePublicationOf:)","navigatorTitle":[{"text":"channel:didSubscribePublicationOfSubscription:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:didUpdateMetadata:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Channel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel"},{"text":", ","kind":"text"},{"text":"didUpdateMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/room\/channel(_:didupdatemetadata:)","role":"symbol","navigatorTitle":[{"text":"channel:didUpdateMetadata:","kind":"identifier"}],"type":"topic","title":"channel(_:didUpdateMetadata:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUpdateMetadata:)","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didPublishStreamOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didSubscribePublicationOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUnpublishStreamOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUnsubscribePublicationOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:didUpdateMetadata:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:member:metadataDidUpdate:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:memberDidJoin:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:memberDidLeave:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publication:metadataDidUpdate:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publicationDidChangeToDisabled:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channel(_:publicationDidChangeToEnabled:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelDidClose(_:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelMemberListDidChange(_:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelPublicationListDidChange(_:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/channelSubscriptionListDidChange(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:publicationDidChangeToDisabled:)\/title","value":"channel:publicationDidChangeToDisabled:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:publicationDidChangeToDisabled:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:publicationDidChangeToDisabled:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:publication:metadataDidUpdate:)\/title","value":"channel:publication:metadataDidUpdate:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:publication:metadataDidUpdate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:publication:metadataDidUpdate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:memberDidLeave:)\/title","value":"channel:memberDidLeave:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:memberDidLeave:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:memberDidLeave:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channelPublicationListDidChange(_:)\/title","value":"channelPublicationListDidChange:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channelPublicationListDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelPublicationListDidChange:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didUnsubscribePublicationOf:)\/title","value":"channel:didUnsubscribePublicationOfSubscription:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didUnsubscribePublicationOf:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didUnsubscribePublicationOfSubscription:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:member:metadataDidUpdate:)\/title","value":"channel:member:metadataDidUpdate:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:member:metadataDidUpdate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:member:metadataDidUpdate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channelSubscriptionListDidChange(_:)\/title","value":"channelSubscriptionListDidChange:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channelSubscriptionListDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelSubscriptionListDidChange:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didPublishStreamOf:)\/title","value":"channel:didPublishStreamOfPublication:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didPublishStreamOf:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didPublishStreamOfPublication:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channelMemberListDidChange(_:)\/title","value":"channelMemberListDidChange:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channelMemberListDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelMemberListDidChange:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didUnpublishStreamOf:)\/title","value":"channel:didUnpublishStreamOfPublication:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didUnpublishStreamOf:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didUnpublishStreamOfPublication:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:publicationDidChangeToEnabled:)\/title","value":"channel:publicationDidChangeToEnabled:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:publicationDidChangeToEnabled:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:publicationDidChangeToEnabled:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channelDidClose(_:)\/title","value":"channelDidClose:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channelDidClose(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelDidClose:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:memberDidJoin:)\/title","value":"channel:memberDidJoin:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:memberDidJoin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:memberDidJoin:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/title","value":"Room","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/fragments","value":[{"kind":"identifier","text":"Room"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/navigatorTitle","value":[{"kind":"identifier","text":"Room"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didSubscribePublicationOf:)\/title","value":"channel:didSubscribePublicationOfSubscription:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didSubscribePublicationOf:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didSubscribePublicationOfSubscription:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didUpdateMetadata:)\/title","value":"channel:didUpdateMetadata:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didUpdateMetadata:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didUpdateMetadata:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}