{
  "abstract": [
    {
      "text": "Inherited from ",
      "type": "text"
    },
    {
      "code": "ChannelDelegate.channel(_:didUpdateMetadata:)",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:didUpdateMetadata:)"
  },
  "kind": "symbol",
  "metadata": {
    "extendedModule": "SkyWayRoom",
    "externalID": "c:@CM@SkyWayRoom@objc(cs)Room(im)channel:didUpdateMetadata:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "channel"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SKWChannel",
        "text": "Channel"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didUpdateMetadata"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "channel:didUpdateMetadata:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "channel(_:didUpdateMetadata:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "channel"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "channel"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SKWChannel",
              "text": "Channel"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didUpdateMetadata"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "metadata"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel": {
      "abstract": [
        {
          "text": "チャンネル",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Channel"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Channel"
        }
      ],
      "role": "symbol",
      "title": "Channel",
      "type": "topic",
      "url": "/documentation/skywayroom/channel"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room": {
      "abstract": [
        {
          "text": "Roomクラス",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Room"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Room"
        }
      ],
      "role": "symbol",
      "title": "Room",
      "type": "topic",
      "url": "/documentation/skywayroom/room"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:didUpdateMetadata:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWChannel",
          "text": "Channel"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/channel(_:didUpdateMetadata:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channel:didUpdateMetadata:"
        }
      ],
      "role": "symbol",
      "title": "channel(_:didUpdateMetadata:)",
      "type": "topic",
      "url": "/documentation/skywayroom/room/channel(_:didupdatemetadata:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "channel:didUpdateMetadata:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "channel:didUpdateMetadata:"
            }
          ]
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "channel:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SKWChannel",
                    "text": "SKWChannel"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "channel"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didUpdateMetadata:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "metadata"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room/title",
          "value": "Room"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "Room"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Room"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didUpdateMetadata:)/title",
          "value": "channel:didUpdateMetadata:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room~1channel(_:didUpdateMetadata:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "channel:didUpdateMetadata:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel/title",
          "value": "SKWChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWChannel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/room/channel(_:didupdatemetadata:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/room/channel(_:didupdatemetadata:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
