{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredMaxFrameRate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"デフォルトは30です。","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/skywayroom\/cameracaptureoptions\/preferredmaxframerate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/cameracaptureoptions\/preferredmaxframerate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"preferredMaxFrameRate"}],"title":"preferredMaxFrameRate","symbolKind":"property","externalID":"c:objc(cs)SKWCameraCaptureOptions(py)preferredMaxFrameRate","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredMaxFrameRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"最大フレームレート数"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraCaptureOptions"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraCaptureOptions\/preferredMaxFrameRate","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraCaptureOptions":{"url":"\/documentation\/skywayroom\/cameracaptureoptions","type":"topic","abstract":[{"type":"text","text":"カメラキャプチャオプション"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraCaptureOptions"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraCaptureOptions","title":"CameraCaptureOptions","navigatorTitle":[{"text":"CameraCaptureOptions","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraCaptureOptions/preferredMaxFrameRate":{"url":"\/documentation\/skywayroom\/cameracaptureoptions\/preferredmaxframerate","navigatorTitle":[{"kind":"identifier","text":"preferredMaxFrameRate"}],"type":"topic","kind":"symbol","title":"preferredMaxFrameRate","abstract":[{"type":"text","text":"最大フレームレート数"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraCaptureOptions\/preferredMaxFrameRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredMaxFrameRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"preferredMaxFrameRate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"preferredMaxFrameRate","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"int","kind":"typeIdentifier","preciseIdentifier":"c:I"},{"text":" ","kind":"text"},{"text":"preferredMaxFrameRate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraCaptureOptions\/title","value":"SKWCameraCaptureOptions"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraCaptureOptions\/fragments","value":[{"text":"SKWCameraCaptureOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraCaptureOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SKWCameraCaptureOptions"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraCaptureOptions~1preferredMaxFrameRate\/title","value":"preferredMaxFrameRate","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraCaptureOptions~1preferredMaxFrameRate\/fragments","value":[{"text":"preferredMaxFrameRate","kind":"identifier"}],"op":"replace"}]}]}