{
  "abstract": [
    {
      "text": "Inherited from ",
      "type": "text"
    },
    {
      "code": "RawRepresentable.hashValue",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationType/hashValue"
  },
  "kind": "symbol",
  "metadata": {
    "conformance": {
      "availabilityPrefix": [
        {
          "text": "Available when",
          "type": "text"
        }
      ],
      "conformancePrefix": [
        {
          "text": "Conforms when",
          "type": "text"
        }
      ],
      "constraints": [
        {
          "code": "Self",
          "type": "codeVoice"
        },
        {
          "text": " conforms to ",
          "type": "text"
        },
        {
          "code": "Hashable",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "RawValue",
          "type": "codeVoice"
        },
        {
          "text": " conforms to ",
          "type": "text"
        },
        {
          "code": "Hashable",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ]
    },
    "extendedModule": "Swift",
    "externalID": "s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@SKWPublicationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hashValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom",
        "relatedModules": [
          "Swift"
        ]
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "hashValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hashValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationType": {
      "abstract": [
        {
          "text": "Publicationの通信タイプ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PublicationType"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PublicationType"
        }
      ],
      "role": "symbol",
      "title": "PublicationType",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationtype"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationType/hashValue": {
      "abstract": [],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hashValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationType/hashValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "hashValue",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationtype/hashvalue"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationType/title",
          "value": "SKWPublicationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/publicationtype/hashvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
