{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/publicationtype\/p2p"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/publicationtype\/p2p"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"P2P","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:@E@SKWPublicationType@SKWPublicationTypeP2P","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"P2P","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SKWPublicationTypeP2P","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"PublicationType.P2P"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/PublicationType"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/PublicationType\/P2P","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationType":{"url":"\/documentation\/skywayroom\/publicationtype","type":"topic","abstract":[{"type":"text","text":"Publicationの通信タイプ"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PublicationType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/PublicationType","title":"PublicationType","navigatorTitle":[{"text":"PublicationType","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationType/P2P":{"url":"\/documentation\/skywayroom\/publicationtype\/p2p","navigatorTitle":[{"kind":"identifier","text":"SKWPublicationTypeP2P"}],"type":"topic","kind":"symbol","title":"PublicationType.P2P","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/PublicationType\/P2P","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"P2P"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SKWPublicationTypeP2P","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SKWPublicationTypeP2P","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SKWPublicationTypeP2P","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SKWPublicationType","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationType\/title","op":"replace"},{"value":[{"text":"SKWPublicationType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationType\/fragments","op":"replace"},{"value":[{"text":"SKWPublicationType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationType\/navigatorTitle","op":"replace"},{"value":"SKWPublicationTypeP2P","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationType~1P2P\/title","op":"replace"},{"value":[{"text":"SKWPublicationTypeP2P","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationType~1P2P\/fragments","op":"replace"}]}]}