{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableCameraIsMissing","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/skwerrorcode\/availablecameraismissing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwerrorcode\/availablecameraismissing"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SKWAvailableCameraIsMissing"}],"title":"SKWErrorCode.availableCameraIsMissing","externalID":"c:@E@SKWErrorCode@SKWAvailableCameraIsMissing","symbolKind":"case","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableCameraIsMissing"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/availableCameraIsMissing"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode":{"url":"\/documentation\/skywayroom\/skwerrorcode","navigatorTitle":[{"text":"SKWErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode","abstract":[{"type":"text","text":"エラーコード"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWErrorCode","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/availableCameraIsMissing":{"url":"\/documentation\/skywayroom\/skwerrorcode\/availablecameraismissing","navigatorTitle":[{"text":"SKWAvailableCameraIsMissing","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.availableCameraIsMissing","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/availableCameraIsMissing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableCameraIsMissing","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SKWAvailableCameraIsMissing"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SKWAvailableCameraIsMissing"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SKWAvailableCameraIsMissing","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/title","value":"SKWErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/fragments","value":[{"kind":"identifier","text":"SKWErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"SKWErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1availableCameraIsMissing\/title","value":"SKWAvailableCameraIsMissing"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1availableCameraIsMissing\/fragments","value":[{"kind":"identifier","text":"SKWAvailableCameraIsMissing"}]}]}]}