{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localPersonSubscribeError","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/skwerrorcode\/localpersonsubscribeerror"]},{"paths":["\/documentation\/skywayroom\/skwerrorcode\/localpersonsubscribeerror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonSubscribeError","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"symbolKind":"case","title":"SKWErrorCode.localPersonSubscribeError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localPersonSubscribeError"}],"navigatorTitle":[{"text":"SKWLocalPersonSubscribeError","kind":"identifier"}],"externalID":"c:@E@SKWErrorCode@SKWLocalPersonSubscribeError","roleHeading":"Case","role":"symbol","modules":[{"name":"SkyWayRoom"}]},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode"]]},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode":{"url":"\/documentation\/skywayroom\/skwerrorcode","navigatorTitle":[{"text":"SKWErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode","abstract":[{"type":"text","text":"エラーコード"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWErrorCode","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/localPersonSubscribeError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/localpersonsubscribeerror","navigatorTitle":[{"text":"SKWLocalPersonSubscribeError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.localPersonSubscribeError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonSubscribeError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localPersonSubscribeError","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SKWLocalPersonSubscribeError"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWLocalPersonSubscribeError","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SKWLocalPersonSubscribeError","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SKWErrorCode","op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/title"},{"value":[{"kind":"identifier","text":"SKWErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/fragments"},{"op":"replace","value":[{"text":"SKWErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/navigatorTitle"},{"op":"replace","value":"SKWLocalPersonSubscribeError","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonSubscribeError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonSubscribeError\/fragments","value":[{"text":"SKWLocalPersonSubscribeError","kind":"identifier"}]}]}]}