{"variants":[{"paths":["\/documentation\/skywayroom\/skwerrorcode\/memberupdatemetadataerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwerrorcode\/memberupdatemetadataerror"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberUpdateMetadataError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/memberUpdateMetadataError"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode"]]},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberUpdateMetadataError","kind":"identifier"}],"externalID":"c:@E@SKWErrorCode@SKWMemberUpdateMetadataError","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"SKWMemberUpdateMetadataError","kind":"identifier"}],"title":"SKWErrorCode.memberUpdateMetadataError","symbolKind":"case"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode":{"url":"\/documentation\/skywayroom\/skwerrorcode","navigatorTitle":[{"text":"SKWErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode","abstract":[{"type":"text","text":"エラーコード"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWErrorCode","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/memberUpdateMetadataError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/memberupdatemetadataerror","navigatorTitle":[{"text":"SKWMemberUpdateMetadataError","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.memberUpdateMetadataError","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/memberUpdateMetadataError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberUpdateMetadataError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SKWMemberUpdateMetadataError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWMemberUpdateMetadataError","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SKWMemberUpdateMetadataError"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/title","value":"SKWErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/fragments","value":[{"text":"SKWErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/navigatorTitle","value":[{"text":"SKWErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1memberUpdateMetadataError\/title","value":"SKWMemberUpdateMetadataError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1memberUpdateMetadataError\/fragments","value":[{"text":"SKWMemberUpdateMetadataError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}