{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/contextdelegate\/reconnectingsucceeded()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/contextdelegate\/reconnectingsucceeded()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"reconnectingSucceeded","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextDelegate"]]},"metadata":{"externalID":"c:objc(pl)SKWContextDelegate(im)reconnectingSucceeded","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reconnectingSucceeded","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"reconnectingSucceeded","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"reconnectingSucceeded()"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextDelegate\/reconnectingSucceeded()"},"abstract":[{"text":"SkyWayサーバと再接続成功後にコールされるイベント","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextDelegate"}],"url":"\/documentation\/skywayroom\/contextdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContextDelegate"}],"type":"topic","title":"ContextDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextDelegate","abstract":[{"type":"text","text":"Contextイベントデリゲート"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextDelegate/reconnectingSucceeded()":{"url":"\/documentation\/skywayroom\/contextdelegate\/reconnectingsucceeded()","type":"topic","abstract":[{"type":"text","text":"SkyWayサーバと再接続成功後にコールされるイベント"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"reconnectingSucceeded","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextDelegate\/reconnectingSucceeded()","title":"reconnectingSucceeded()","navigatorTitle":[{"text":"reconnectingSucceeded","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"reconnectingSucceeded","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reconnectingSucceeded"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"reconnectingSucceeded","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate\/title","value":"SKWContextDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate\/fragments","value":[{"kind":"identifier","text":"SKWContextDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SKWContextDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate~1reconnectingSucceeded()\/title","value":"reconnectingSucceeded","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate~1reconnectingSucceeded()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reconnectingSucceeded"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}