{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/contextdelegate\/startreconnecting()"]},{"paths":["\/documentation\/skywayroom\/contextdelegate\/startreconnecting()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startReconnecting","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextDelegate"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:objc(pl)SKWContextDelegate(im)startReconnecting","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startReconnecting","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"text":"startReconnecting","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"startReconnecting()"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextDelegate\/startReconnecting()","interfaceLanguage":"swift"},"abstract":[{"text":"SkyWayサーバと再接続開始後にコールされるイベント","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextDelegate/startReconnecting()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startReconnecting"},{"kind":"text","text":"()"}],"url":"\/documentation\/skywayroom\/contextdelegate\/startreconnecting()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startReconnecting"}],"type":"topic","title":"startReconnecting()","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextDelegate\/startReconnecting()","abstract":[{"type":"text","text":"SkyWayサーバと再接続開始後にコールされるイベント"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextDelegate"}],"url":"\/documentation\/skywayroom\/contextdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContextDelegate"}],"type":"topic","title":"ContextDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextDelegate","abstract":[{"type":"text","text":"Contextイベントデリゲート"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"startReconnecting","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startReconnecting","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"startReconnecting","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate~1startReconnecting()\/title","value":"startReconnecting"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate~1startReconnecting()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startReconnecting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate\/title","value":"SKWContextDelegate"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate\/fragments","value":[{"text":"SKWContextDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SKWContextDelegate"}]}]}]}