{"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SkyWayRoom"}],"title":"encodings","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodings","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Encoding","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWEncoding"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"encodings","kind":"identifier"}],"externalID":"c:@M@SkyWayRoom@objc(cs)RoomPublication(py)encodings"},"sections":[],"kind":"symbol","abstract":[{"text":"エンコーディング設定","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodings","kind":"identifier"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Encoding","preciseIdentifier":"c:objc(cs)SKWEncoding","text":"Encoding","kind":"typeIdentifier"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"詳しい設定例については開発者ドキュメントの","type":"text"},{"isActive":true,"identifier":"https:\/\/skyway.ntt.com\/ja\/docs\/user-guide\/tips\/large-scale\/","type":"reference"},{"type":"text","text":"をご覧ください。"}]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/roompublication\/encodings"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/roompublication\/encodings"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication\/encodings","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication":{"url":"\/documentation\/skywayroom\/roompublication","type":"topic","abstract":[{"type":"text","text":"Room SDKにおけるPublication"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomPublication"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication","title":"RoomPublication","navigatorTitle":[{"kind":"identifier","text":"RoomPublication"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/encodings":{"url":"\/documentation\/skywayroom\/roompublication\/encodings","title":"encodings","kind":"symbol","abstract":[{"text":"エンコーディング設定","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodings","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Encoding","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWEncoding"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication\/encodings","type":"topic","navigatorTitle":[{"text":"encodings","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Encoding":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Encoding"}],"url":"\/documentation\/skywayroom\/encoding","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Encoding"}],"type":"topic","title":"Encoding","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Encoding","abstract":[{"text":"エンコーディング設定","type":"text"}]},"https://skyway.ntt.com/ja/docs/user-guide/tips/large-scale/":{"identifier":"https:\/\/skyway.ntt.com\/ja\/docs\/user-guide\/tips\/large-scale\/","url":"https:\/\/skyway.ntt.com\/ja\/docs\/user-guide\/tips\/large-scale\/","titleInlineContent":[{"text":"大規模会議アプリを実装する上での注意点","type":"text"}],"title":"大規模会議アプリを実装する上での注意点","type":"link"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"encodings","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"encodings"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SKWEncoding *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"encodings"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"RoomPublication","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/title"},{"op":"replace","value":[{"kind":"identifier","text":"RoomPublication"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"RoomPublication"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/navigatorTitle"},{"op":"replace","value":"encodings","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1encodings\/title"},{"op":"replace","value":[{"kind":"identifier","text":"encodings"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1encodings\/fragments"},{"op":"replace","value":"SKWEncoding","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Encoding\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SKWEncoding"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Encoding\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SKWEncoding"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Encoding\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}