{
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/PublicationDelegate-Implementations"
  },
  "kind": "article",
  "metadata": {
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "PublicationDelegate Implementations"
  },
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.7.0",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication": {
      "abstract": [
        {
          "text": "Room SDKにおけるPublication",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomPublication"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomPublication"
        }
      ],
      "role": "symbol",
      "title": "RoomPublication",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:connectionStateDidChange:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publication"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "connectionStateDidChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKWConnectionState",
          "text": "ConnectionState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:connectionStateDidChange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publication:connectionStateDidChange:"
        }
      ],
      "role": "symbol",
      "title": "publication(_:connectionStateDidChange:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication/publication(_:connectionstatedidchange:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:didUpdateMetadata:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publication"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:didUpdateMetadata:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publication:didUpdateMetadata:"
        }
      ],
      "role": "symbol",
      "title": "publication(_:didUpdateMetadata:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication/publication(_:didupdatemetadata:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:subscribed:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publication"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "subscribed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWSubscription",
          "text": "Subscription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:subscribed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publication:subscribed:"
        }
      ],
      "role": "symbol",
      "title": "publication(_:subscribed:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication/publication(_:subscribed:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:unsubscribed:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publication"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "unsubscribed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWSubscription",
          "text": "Subscription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:unsubscribed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publication:unsubscribed:"
        }
      ],
      "role": "symbol",
      "title": "publication(_:unsubscribed:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication/publication(_:unsubscribed:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationDisabled(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationDisabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationDisabled(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationDisabled:"
        }
      ],
      "role": "symbol",
      "title": "publicationDisabled(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication/publicationdisabled(_:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationEnabled(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationEnabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationEnabled(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationEnabled:"
        }
      ],
      "role": "symbol",
      "title": "publicationEnabled(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication/publicationenabled(_:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationStateDidChange(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationStateDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationStateDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationStateDidChange:"
        }
      ],
      "role": "symbol",
      "title": "publicationStateDidChange(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication/publicationstatedidchange(_:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationSubscriptionListDidChange(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationSubscriptionListDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationSubscriptionListDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationSubscriptionListDidChange:"
        }
      ],
      "role": "symbol",
      "title": "publicationSubscriptionListDidChange(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication/publicationsubscriptionlistdidchange(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:connectionStateDidChange:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:didUpdateMetadata:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:subscribed:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:unsubscribed:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationDisabled(_:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationEnabled(_:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationStateDidChange(_:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationSubscriptionListDidChange(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:connectionStateDidChange:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:didUpdateMetadata:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:subscribed:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publication(_:unsubscribed:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationDisabled(_:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationEnabled(_:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationStateDidChange(_:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication/publicationSubscriptionListDidChange(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publicationDisabled(_:)/title",
          "value": "publicationDisabled:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publicationDisabled(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publicationDisabled:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publicationEnabled(_:)/title",
          "value": "publicationEnabled:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publicationEnabled(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publicationEnabled:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publication(_:subscribed:)/title",
          "value": "publication:subscribed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publication(_:subscribed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publication:subscribed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication/title",
          "value": "RoomPublication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomPublication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomPublication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publication(_:connectionStateDidChange:)/title",
          "value": "publication:connectionStateDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publication(_:connectionStateDidChange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publication:connectionStateDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publicationSubscriptionListDidChange(_:)/title",
          "value": "publicationSubscriptionListDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publicationSubscriptionListDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publicationSubscriptionListDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publicationStateDidChange(_:)/title",
          "value": "publicationStateDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publicationStateDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publicationStateDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publication(_:unsubscribed:)/title",
          "value": "publication:unsubscribed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publication(_:unsubscribed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publication:unsubscribed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publication(_:didUpdateMetadata:)/title",
          "value": "publication:didUpdateMetadata:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication~1publication(_:didUpdateMetadata:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publication:didUpdateMetadata:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/roompublication/publicationdelegate-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/roompublication/publicationdelegate-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
