{"variants":[{"paths":["\/documentation\/skywayroom\/connectionstate\/reconnecting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/connectionstate\/reconnecting"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState\/reconnecting"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState"]]},"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reconnecting","kind":"identifier"}],"externalID":"c:@E@SKWConnectionState@SKWReconnecting","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"kind":"identifier","text":"SKWReconnecting"}],"title":"ConnectionState.reconnecting","symbolKind":"case"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ConnectionState":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionState"}],"url":"\/documentation\/skywayroom\/connectionstate","role":"symbol","navigatorTitle":[{"text":"ConnectionState","kind":"identifier"}],"type":"topic","title":"ConnectionState","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState","abstract":[{"type":"text","text":"接続状態"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ConnectionState/reconnecting":{"url":"\/documentation\/skywayroom\/connectionstate\/reconnecting","navigatorTitle":[{"kind":"identifier","text":"SKWReconnecting"}],"type":"topic","kind":"symbol","title":"ConnectionState.reconnecting","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState\/reconnecting","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SKWReconnecting"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWReconnecting","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SKWReconnecting","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/title","value":"SKWConnectionState"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/fragments","value":[{"text":"SKWConnectionState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/navigatorTitle","value":[{"text":"SKWConnectionState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState~1reconnecting\/title","value":"SKWReconnecting"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState~1reconnecting\/fragments","value":[{"text":"SKWReconnecting","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}