{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SkyWayRoom"}],"title":"state","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ForwardingState","kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWForwardingState"}],"navigatorTitle":[{"kind":"identifier","text":"state"}],"externalID":"c:objc(cs)SKWForwarding(py)state"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Forwardingの状態"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ForwardingState","text":"ForwardingState","kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWForwardingState"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/forwarding\/state"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/forwarding\/state"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/state","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ForwardingState":{"url":"\/documentation\/skywayroom\/forwardingstate","navigatorTitle":[{"kind":"identifier","text":"ForwardingState"}],"type":"topic","kind":"symbol","title":"ForwardingState","abstract":[{"text":"フォワーディング状態","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ForwardingState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForwardingState"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Forwarding"}],"url":"\/documentation\/skywayroom\/forwarding","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Forwarding"}],"type":"topic","title":"Forwarding","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding","abstract":[{"type":"text","text":"フォワーディング"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding/state":{"url":"\/documentation\/skywayroom\/forwarding\/state","navigatorTitle":[{"kind":"identifier","text":"state"}],"type":"topic","kind":"symbol","title":"state","abstract":[{"text":"Forwardingの状態","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWForwardingState","text":"ForwardingState"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"state","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"state","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SKWForwardingState","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ForwardingState","preciseIdentifier":"c:@E@SKWForwardingState"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ForwardingState\/title","value":"SKWForwardingState","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ForwardingState\/fragments","value":[{"text":"SKWForwardingState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ForwardingState\/navigatorTitle","value":[{"text":"SKWForwardingState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding\/title","value":"SKWForwarding","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding\/fragments","value":[{"text":"SKWForwarding","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding\/navigatorTitle","value":[{"text":"SKWForwarding","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1state\/title","value":"state","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1state\/fragments","value":[{"text":"state","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}