{"variants":[{"paths":["\/documentation\/skywayroom\/encoding\/scaleresolutiondownby"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/encoding\/scaleresolutiondownby"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"映像の解像度をスケールダウンさせる指数","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaleResolutionDownBy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"このオプションはVideoStreamのみ有効です。"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"例えば2.0を設定してPublishを行うと、縦横それぞれ半分の解像度にスケールダウンするのでオリジナルの映像の25%まで解像度が下がります。","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"デフォルトでは1.0です。","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Encoding"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Encoding\/scaleResolutionDownBy"},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaleResolutionDownBy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"externalID":"c:objc(cs)SKWEncoding(py)scaleResolutionDownBy","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"kind":"identifier","text":"scaleResolutionDownBy"}],"title":"scaleResolutionDownBy","symbolKind":"property"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Encoding":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Encoding"}],"url":"\/documentation\/skywayroom\/encoding","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Encoding"}],"type":"topic","title":"Encoding","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Encoding","abstract":[{"text":"エンコーディング設定","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Encoding/scaleResolutionDownBy":{"url":"\/documentation\/skywayroom\/encoding\/scaleresolutiondownby","type":"topic","abstract":[{"type":"text","text":"映像の解像度をスケールダウンさせる指数"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleResolutionDownBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Encoding\/scaleResolutionDownBy","title":"scaleResolutionDownBy","navigatorTitle":[{"text":"scaleResolutionDownBy","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"scaleResolutionDownBy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"scaleResolutionDownBy"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"scaleResolutionDownBy","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Encoding\/title","value":"SKWEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Encoding\/fragments","value":[{"text":"SKWEncoding","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Encoding\/navigatorTitle","value":[{"kind":"identifier","text":"SKWEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Encoding~1scaleResolutionDownBy\/title","value":"scaleResolutionDownBy"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Encoding~1scaleResolutionDownBy\/fragments","value":[{"kind":"identifier","text":"scaleResolutionDownBy"}]}]}]}