{"kind":"symbol","abstract":[{"type":"text","text":"fmtpパラメータ設定"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"parameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CodecParameters","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CodecParameters","preciseIdentifier":"c:objc(cs)SKWCodecParameters"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/skywayroom\/codec\/parameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/codec\/parameters"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Codec\/parameters"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","title":"parameters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parameters"},{"kind":"text","text":": "},{"text":"CodecParameters","preciseIdentifier":"c:objc(cs)SKWCodecParameters","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"parameters"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)SKWCodec(py)parameters","modules":[{"name":"SkyWayRoom"}]},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Codec"]]},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Codec":{"url":"\/documentation\/skywayroom\/codec","navigatorTitle":[{"kind":"identifier","text":"Codec"}],"type":"topic","kind":"symbol","title":"Codec","abstract":[{"text":"コーデック設定","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Codec","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Codec"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Codec/parameters":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parameters","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CodecParameters","preciseIdentifier":"c:objc(cs)SKWCodecParameters","kind":"typeIdentifier"}],"url":"\/documentation\/skywayroom\/codec\/parameters","role":"symbol","navigatorTitle":[{"text":"parameters","kind":"identifier"}],"type":"topic","title":"parameters","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Codec\/parameters","abstract":[{"type":"text","text":"fmtpパラメータ設定"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CodecParameters":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CodecParameters"}],"url":"\/documentation\/skywayroom\/codecparameters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CodecParameters"}],"type":"topic","title":"CodecParameters","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CodecParameters","abstract":[{"type":"text","text":"コーデックパラメータ"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"parameters"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"parameters","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SKWCodecParameters","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CodecParameters","preciseIdentifier":"c:objc(cs)SKWCodecParameters"},{"kind":"text","text":" * "},{"kind":"identifier","text":"parameters"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SKWCodec","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Codec\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Codec\/fragments","value":[{"text":"SKWCodec","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Codec\/navigatorTitle","value":[{"kind":"identifier","text":"SKWCodec"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Codec~1parameters\/title","value":"parameters"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Codec~1parameters\/fragments","value":[{"kind":"identifier","text":"parameters"}]},{"op":"replace","value":"SKWCodecParameters","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CodecParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CodecParameters\/fragments","value":[{"kind":"identifier","text":"SKWCodecParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CodecParameters\/navigatorTitle","value":[{"text":"SKWCodecParameters","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}