{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/subscription\/getstats()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/subscription\/getstats()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStats","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"WebRTCStats","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWWebRTCStats"},{"text":"?","kind":"text"}]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"SkyWayCore v2.0.0で非推奨となりました。"}],"type":"paragraph"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription"]]},"metadata":{"externalID":"c:objc(cs)SKWSubscription(im)getStats","modules":[{"name":"SkyWayRoom"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStats"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWWebRTCStats","text":"WebRTCStats","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":[{"message":"SkyWayCore v2.0.0で非推奨となりました。","beta":false,"unavailable":false,"deprecated":true}],"role":"symbol","navigatorTitle":[{"text":"getStats","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"getStats()"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription\/getStats()"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Subscription/getStats()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getStats"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWWebRTCStats","text":"WebRTCStats"},{"kind":"text","text":"?"}],"url":"\/documentation\/skywayroom\/subscription\/getstats()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getStats"}],"deprecated":true,"type":"topic","title":"getStats()","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription\/getStats()","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Subscription":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Subscription","kind":"identifier"}],"url":"\/documentation\/skywayroom\/subscription","role":"symbol","navigatorTitle":[{"text":"Subscription","kind":"identifier"}],"type":"topic","title":"Subscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription","abstract":[{"type":"text","text":"SubscriptionはLocalMemberがSubscribeした時に取得でき、Subscriptionに含まれるStreamを利用して映像を描画したりします。"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/WebRTCStats":{"url":"\/documentation\/skywayroom\/webrtcstats","navigatorTitle":[{"kind":"identifier","text":"WebRTCStats"}],"type":"topic","kind":"symbol","title":"WebRTCStats","abstract":[],"deprecated":true,"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebRTCStats"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":true,"beta":false,"unavailable":false}],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"getStats","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getStats","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"SKWWebRTCStats","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStats","preciseIdentifier":"c:objc(cs)SKWWebRTCStats"},{"text":" *) ","kind":"text"},{"text":"getStats","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"SkyWayCore v2.0.0で非推奨となりました。","type":"text"}]}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription~1getStats()\/title","value":"getStats","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription~1getStats()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getStats","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/title","value":"SKWSubscription"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/fragments","value":[{"text":"SKWSubscription","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/navigatorTitle","value":[{"kind":"identifier","text":"SKWSubscription"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStats\/title","value":"SKWWebRTCStats","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStats\/fragments","value":[{"text":"SKWWebRTCStats","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStats\/navigatorTitle","value":[{"kind":"identifier","text":"SKWWebRTCStats"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}