{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/localdatastream\/write(_:completion:)-7xzhd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/localdatastream\/write(_:completion:)-7xzhd"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"write"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")? = nil)"}]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"送信するデータ","type":"text"}]}],"name":"data"},{"content":[{"type":"paragraph","inlineContent":[{"text":"完了コールバック","type":"text"}]}],"name":"completion"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Subscribe側で受け取ることができるのは、データ通信の接続完了以降に書き込まれたデータであることに注意してください。"},{"type":"text","text":" "},{"type":"text","text":"接続完了のタイミングを検知したい場合は以下のイベントをご利用ください。"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Core SDKをご利用の場合:"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"..\/Protocols\/SKWPublicationDelegate.html#\/c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:"}]},{"type":"paragraph","inlineContent":[{"text":"Room SDKをご利用の場合:","type":"text"},{"text":" ","type":"text"},{"identifier":"..\/..\/room\/Protocols\/RoomPublicationDelegate.html#\/c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:","type":"reference","isActive":true}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:objc(cs)SKWLocalDataStream(im)writeData:completion:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"write"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeData:completion:"}],"roleHeading":"Instance Method","symbolKind":"method","title":"write(_:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream\/write(_:completion:)-7xzhd","interfaceLanguage":"swift"},"abstract":[{"text":"データを送信します。","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStream/write(_:completion:)-7xzhd":{"url":"\/documentation\/skywayroom\/localdatastream\/write(_:completion:)-7xzhd","navigatorTitle":[{"kind":"identifier","text":"writeData:completion:"}],"type":"topic","kind":"symbol","title":"write(_:completion:)","abstract":[{"type":"text","text":"データを送信します。"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream\/write(_:completion:)-7xzhd","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"write"},{"kind":"text","text":"("},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"../Protocols/SKWPublicationDelegate.html#/c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:":{"identifier":"..\/Protocols\/SKWPublicationDelegate.html#\/c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:","title":"SKWPublicationDelegate.publication:connectionStateDidChange:","type":"link","titleInlineContent":[{"text":"SKWPublicationDelegate.publication:connectionStateDidChange:","type":"text"}],"url":"..\/Protocols\/SKWPublicationDelegate.html#\/c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStream":{"title":"LocalDataStream","abstract":[{"text":"LocalDataStreamクラス","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStream","kind":"identifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream","navigatorTitle":[{"text":"LocalDataStream","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/localdatastream","type":"topic"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWLocalDataStreamCompletion":{"url":"\/documentation\/skywayroom\/skwlocaldatastreamcompletion","navigatorTitle":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWLocalDataStreamCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWLocalDataStreamCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}]},"../../room/Protocols/RoomPublicationDelegate.html#/c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:":{"type":"link","identifier":"..\/..\/room\/Protocols\/RoomPublicationDelegate.html#\/c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:","url":"..\/..\/room\/Protocols\/RoomPublicationDelegate.html#\/c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:","title":"RoomPublicationDelegate.publication(_:connectionStateDidChange:)","titleInlineContent":[{"type":"text","text":"RoomPublicationDelegate.publication(_:connectionStateDidChange:)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"writeData:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeData:completion:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"writeData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKWLocalDataStreamCompletion","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWLocalDataStreamCompletion","preciseIdentifier":"c:SKWLocalDataStream.h@T@SKWLocalDataStreamCompletion"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"送信するデータ"}],"type":"paragraph"}],"name":"data"},{"content":[{"inlineContent":[{"type":"text","text":"完了コールバック"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream~1write(_:completion:)-7xzhd\/title","value":"writeData:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream~1write(_:completion:)-7xzhd\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeData:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/title","value":"SKWLocalDataStream"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/fragments","value":[{"text":"SKWLocalDataStream","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/navigatorTitle","value":[{"text":"SKWLocalDataStream","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalDataStreamCompletion\/title","value":"SKWLocalDataStreamCompletion","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalDataStreamCompletion\/fragments","value":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalDataStreamCompletion\/navigatorTitle","value":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}],"op":"replace"}]}]}