{"variants":[{"paths":["\/documentation\/skywayroom\/localdatastream\/write(_:)-9i6sd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/localdatastream\/write(_:)-9i6sd"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"文字列を送信します。"}],"deprecationSummary":[{"inlineContent":[{"text":"SkyWayRoom v3.0.0で非推奨となりました。`LocalDataStream.writeString(_:completion:)`をご利用ください。","type":"text"}],"type":"paragraph"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"string","content":[{"inlineContent":[{"text":"送信する文字列","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Subscribe側で受け取ることができるのは、データ通信の接続完了以降に書き込まれたデータであることに注意してください。","type":"text"},{"text":" ","type":"text"},{"text":"接続完了のタイミングを検知したい場合は以下のイベントをご利用ください。","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Core SDKをご利用の場合:","type":"text"},{"type":"text","text":" "},{"identifier":"..\/Protocols\/SKWPublicationDelegate.html#\/c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:","type":"reference","isActive":true}]},{"inlineContent":[{"text":"Room SDKをご利用の場合:","type":"text"},{"text":" ","type":"text"},{"identifier":"..\/..\/room\/Protocols\/RoomPublicationDelegate.html#\/c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:","type":"reference","isActive":true}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream\/write(_:)-9i6sd","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)SKWLocalDataStream(im)writeString:","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"write","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[{"deprecated":true,"beta":false,"message":"SkyWayRoom v3.0.0で非推奨となりました。`LocalDataStream.writeString(_:completion:)`をご利用ください。","unavailable":false}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"writeString:"}],"roleHeading":"Instance Method","symbolKind":"method","title":"write(_:)"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream"]]},"kind":"symbol","references":{"../Protocols/SKWPublicationDelegate.html#/c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:":{"titleInlineContent":[{"type":"text","text":"SKWPublicationDelegate.publication:connectionStateDidChange:"}],"url":"..\/Protocols\/SKWPublicationDelegate.html#\/c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:","type":"link","title":"SKWPublicationDelegate.publication:connectionStateDidChange:","identifier":"..\/Protocols\/SKWPublicationDelegate.html#\/c:objc(pl)SKWPublicationDelegate(im)publication:connectionStateDidChange:"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStream/write(_:)-9i6sd":{"url":"\/documentation\/skywayroom\/localdatastream\/write(_:)-9i6sd","deprecated":true,"title":"write(_:)","abstract":[{"text":"文字列を送信します。","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"write"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream\/write(_:)-9i6sd","type":"topic","navigatorTitle":[{"kind":"identifier","text":"writeString:"}]},"../../room/Protocols/RoomPublicationDelegate.html#/c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:":{"identifier":"..\/..\/room\/Protocols\/RoomPublicationDelegate.html#\/c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:","url":"..\/..\/room\/Protocols\/RoomPublicationDelegate.html#\/c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:","titleInlineContent":[{"type":"text","text":"RoomPublicationDelegate.publication(_:connectionStateDidChange:)"}],"title":"RoomPublicationDelegate.publication(_:connectionStateDidChange:)","type":"link"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStream":{"title":"LocalDataStream","abstract":[{"text":"LocalDataStreamクラス","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStream","kind":"identifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream","navigatorTitle":[{"text":"LocalDataStream","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/localdatastream","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"deprecated":true}],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"writeString:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"writeString:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"writeString:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"string","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"string","content":[{"inlineContent":[{"type":"text","text":"送信する文字列"}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":[{"inlineContent":[{"type":"text","text":"SkyWayRoom v3.0.0で非推奨となりました。`LocalDataStream.writeString(_:completion:)`をご利用ください。"}],"type":"paragraph"}],"path":"\/deprecationSummary","op":"replace"},{"value":"writeString:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream~1write(_:)-9i6sd\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream~1write(_:)-9i6sd\/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeString:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SKWLocalDataStream","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/fragments","value":[{"text":"SKWLocalDataStream","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/navigatorTitle","value":[{"text":"SKWLocalDataStream","kind":"identifier"}],"op":"replace"}]}]}