{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/webrtcstatsreport\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/webrtcstatsreport\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Type一覧はこちらをご確認ください。"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/w3c.github.io\/webrtc-stats\/#rtctatstype-*"}]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"SkyWayCore v2.0.0で非推奨となりました。"}],"type":"paragraph"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:objc(cs)SKWWebRTCStatsReport(py)type","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":[{"message":"SkyWayCore v2.0.0で非推奨となりました。","unavailable":false,"deprecated":true,"beta":false}],"role":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","title":"type"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStatsReport"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStatsReport\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"統計情報のType"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/WebRTCStatsReport/type":{"url":"\/documentation\/skywayroom\/webrtcstatsreport\/type","navigatorTitle":[{"kind":"identifier","text":"type"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"統計情報のType"}],"title":"type","deprecated":true,"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStatsReport\/type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/WebRTCStatsReport":{"url":"\/documentation\/skywayroom\/webrtcstatsreport","navigatorTitle":[{"kind":"identifier","text":"WebRTCStatsReport"}],"type":"topic","kind":"symbol","abstract":[],"title":"WebRTCStatsReport","deprecated":true,"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStatsReport","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebRTCStatsReport"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"deprecated":true,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SkyWayCore v2.0.0で非推奨となりました。"}]}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStatsReport~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStatsReport~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStatsReport\/title","value":"SKWWebRTCStatsReport"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStatsReport\/fragments","value":[{"text":"SKWWebRTCStatsReport","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStatsReport\/navigatorTitle","value":[{"text":"SKWWebRTCStatsReport","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}