{"variants":[{"paths":["\/documentation\/skywayroom\/roompublicationdelegate\/publication(_:connectionstatedidchange:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/roompublicationdelegate\/publication(_:connectionstatedidchange:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Publicationの接続状態が変化した後にコールされるイベント"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publication","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"publication"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication","text":"RoomPublication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionStateDidChange"},{"kind":"text","text":" "},{"text":"connectionState","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SKWConnectionState","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState","text":"ConnectionState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"RoomPublication"}]}],"name":"publication"},{"name":"connectionState","content":[{"inlineContent":[{"type":"text","text":"接続状態"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublicationDelegate\/publication(_:connectionStateDidChange:)"},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publication","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RoomPublication","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication"},{"text":", ","kind":"text"},{"text":"connectionStateDidChange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWConnectionState"},{"text":")","kind":"text"}],"externalID":"c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publication:connectionStateDidChange:","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"kind":"identifier","text":"publication:connectionStateDidChange:"}],"title":"publication(_:connectionStateDidChange:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublicationDelegate"]]},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ConnectionState":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionState"}],"url":"\/documentation\/skywayroom\/connectionstate","role":"symbol","navigatorTitle":[{"text":"ConnectionState","kind":"identifier"}],"type":"topic","title":"ConnectionState","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState","abstract":[{"type":"text","text":"接続状態"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublicationDelegate/publication(_:connectionStateDidChange:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"publication"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication","text":"RoomPublication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connectionStateDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWConnectionState","text":"ConnectionState"},{"kind":"text","text":")"}],"url":"\/documentation\/skywayroom\/roompublicationdelegate\/publication(_:connectionstatedidchange:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"publication:connectionStateDidChange:"}],"type":"topic","title":"publication(_:connectionStateDidChange:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublicationDelegate\/publication(_:connectionStateDidChange:)","abstract":[{"text":"Publicationの接続状態が変化した後にコールされるイベント","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublicationDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomPublicationDelegate"}],"url":"\/documentation\/skywayroom\/roompublicationdelegate","role":"symbol","navigatorTitle":[{"text":"RoomPublicationDelegate","kind":"identifier"}],"type":"topic","title":"RoomPublicationDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublicationDelegate","abstract":[{"type":"text","text":"RoomPublicationイベントデリゲート"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication":{"url":"\/documentation\/skywayroom\/roompublication","type":"topic","abstract":[{"type":"text","text":"Room SDKにおけるPublication"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomPublication"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication","title":"RoomPublication","navigatorTitle":[{"kind":"identifier","text":"RoomPublication"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"publication:connectionStateDidChange:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"publication:connectionStateDidChange:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"publication:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication","text":"RoomPublication"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"publication"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStateDidChange:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWConnectionState","text":"SKWConnectionState"},{"kind":"text","text":") "},{"kind":"internalParam","text":"connectionState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"RoomPublication"}],"type":"paragraph"}],"name":"publication"},{"content":[{"inlineContent":[{"type":"text","text":"接続状態"}],"type":"paragraph"}],"name":"connectionState"}]}},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/title","op":"replace","value":"SKWConnectionState"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/fragments","op":"replace","value":[{"text":"SKWConnectionState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ConnectionState\/navigatorTitle","op":"replace","value":[{"text":"SKWConnectionState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate~1publication(_:connectionStateDidChange:)\/title","op":"replace","value":"publication:connectionStateDidChange:"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate~1publication(_:connectionStateDidChange:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"publication:connectionStateDidChange:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate\/title","op":"replace","value":"RoomPublicationDelegate"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate\/fragments","op":"replace","value":[{"text":"RoomPublicationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate\/navigatorTitle","op":"replace","value":[{"text":"RoomPublicationDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/title","op":"replace","value":"RoomPublication"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/fragments","op":"replace","value":[{"text":"RoomPublication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/navigatorTitle","op":"replace","value":[{"text":"RoomPublication","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}