{
  "abstract": [
    {
      "text": "Publicationの状態(Enabled, Disabled, Canceled)が変化した後にコールされるイベント",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublicationDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublicationDelegate/publicationStateDidChange(_:)"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:@M@SkyWayRoom@objc(pl)RoomPublicationDelegate(im)publicationStateDidChange:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "publicationStateDidChange"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomPublication",
        "text": "RoomPublication"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "publicationStateDidChange:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "publicationStateDidChange(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@objc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "publicationStateDidChange"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "publication"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomPublication",
              "text": "RoomPublication"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "RoomPublication",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "publication"
        }
      ]
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.7.0",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication": {
      "abstract": [
        {
          "text": "Room SDKにおけるPublication",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomPublication"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomPublication"
        }
      ],
      "role": "symbol",
      "title": "RoomPublication",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublication"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublicationDelegate": {
      "abstract": [
        {
          "text": "RoomPublicationイベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomPublicationDelegate"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomPublicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "RoomPublicationDelegate",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublicationdelegate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublicationDelegate/publicationStateDidChange(_:)": {
      "abstract": [
        {
          "text": "Publicationの状態(Enabled, Disabled, Canceled)が変化した後にコールされるイベント",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationStateDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomPublication",
          "text": "RoomPublication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublicationDelegate/publicationStateDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationStateDidChange:"
        }
      ],
      "role": "symbol",
      "title": "publicationStateDidChange(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roompublicationdelegate/publicationstatedidchange(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "publicationStateDidChange:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publicationStateDidChange:"
            }
          ]
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "publicationStateDidChange:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomPublication",
                    "text": "RoomPublication"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "publication"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "RoomPublication",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "publication"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate/title",
          "value": "RoomPublicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomPublicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomPublicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate~1publicationStateDidChange(_:)/title",
          "value": "publicationStateDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublicationDelegate~1publicationStateDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "publicationStateDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication/title",
          "value": "RoomPublication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomPublication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomPublication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/roompublicationdelegate/publicationstatedidchange(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/roompublicationdelegate/publicationstatedidchange(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
