{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentCategoryOptions","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"CategoryOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions"}]}]},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"現在使用されている","type":"text"},{"code":"AVAudioSessionCategoryOptions","type":"codeVoice"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/skywayroom\/audiosettings\/currentcategoryoptions()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/audiosettings\/currentcategoryoptions()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"currentCategoryOptions","kind":"identifier"}],"title":"currentCategoryOptions()","externalID":"c:objc(cs)SKWAudioSettings(cm)currentCategoryOptions","symbolKind":"method","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentCategoryOptions"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"現在使用されている"},{"type":"codeVoice","code":"AVAudioSessionCategoryOptions"},{"type":"text","text":"設定を返します。"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/currentCategoryOptions()","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioSettings","kind":"identifier"}],"url":"\/documentation\/skywayroom\/audiosettings","role":"symbol","navigatorTitle":[{"text":"AudioSettings","kind":"identifier"}],"type":"topic","title":"AudioSettings","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings","abstract":[{"text":"音声入出力の設定クラス","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings/currentCategoryOptions()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentCategoryOptions"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions","kind":"typeIdentifier"}],"url":"\/documentation\/skywayroom\/audiosettings\/currentcategoryoptions()","role":"symbol","navigatorTitle":[{"text":"currentCategoryOptions","kind":"identifier"}],"type":"topic","title":"currentCategoryOptions()","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/currentCategoryOptions()","abstract":[{"type":"text","text":"現在使用されている"},{"type":"codeVoice","code":"AVAudioSessionCategoryOptions"},{"type":"text","text":"設定を返します。"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"currentCategoryOptions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"currentCategoryOptions","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"AVAudioSessionCategoryOptions","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions"},{"kind":"text","text":") "},{"kind":"identifier","text":"currentCategoryOptions"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"現在使用されている"},{"type":"codeVoice","code":"AVAudioSessionCategoryOptions"}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/title","value":"SKWAudioSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/fragments","value":[{"text":"SKWAudioSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/navigatorTitle","value":[{"text":"SKWAudioSettings","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1currentCategoryOptions()\/title","value":"currentCategoryOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1currentCategoryOptions()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"currentCategoryOptions","kind":"identifier"}]}]}]}