{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/audiosettings\/setcategoryoptions(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/audiosettings\/setcategoryoptions(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCategoryOptions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CategoryOptions","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AVAudioSessionCategoryOptions"}]}],"name":"options"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"設定の更新に成功したかどうか"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"デフォルトの値は"},{"type":"codeVoice","code":"AVAudioSessionCategoryOptionMixWithOthers"},{"type":"text","text":"ですが、音声が疎通すると"},{"type":"codeVoice","code":"AVAudioSessionCategoryOptionAllowBluetooth"},{"type":"text","text":"となります。"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"ビルトインスピーカに切り替えたい場合は、"},{"type":"codeVoice","code":"AVAudioSessionCategoryOptionsDefaultToSpeaker"},{"type":"text","text":"を指定してください。"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:objc(cs)SKWAudioSettings(cm)setCategoryOptions:","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCategoryOptions"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CategoryOptions","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setCategoryOptions:"}],"roleHeading":"Type Method","symbolKind":"method","title":"setCategoryOptions(_:)"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/setCategoryOptions(_:)"},"abstract":[{"type":"text","text":"音声出力先についての設定ができます。任意のタイミングで設定が可能です。"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings/setCategoryOptions(_:)":{"url":"\/documentation\/skywayroom\/audiosettings\/setcategoryoptions(_:)","title":"setCategoryOptions(_:)","abstract":[{"text":"音声出力先についての設定ができます。任意のタイミングで設定が可能です。","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCategoryOptions","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/setCategoryOptions(_:)","type":"topic","navigatorTitle":[{"text":"setCategoryOptions:","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioSettings","kind":"identifier"}],"url":"\/documentation\/skywayroom\/audiosettings","role":"symbol","navigatorTitle":[{"text":"AudioSettings","kind":"identifier"}],"type":"topic","title":"AudioSettings","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings","abstract":[{"text":"音声入出力の設定クラス","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setCategoryOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setCategoryOptions:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCategoryOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"AVAudioSessionCategoryOptions"},{"kind":"text","text":") "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AVAudioSessionCategoryOptions"}]}],"name":"options"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"設定の更新に成功したかどうか"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1setCategoryOptions(_:)\/title","value":"setCategoryOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1setCategoryOptions(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setCategoryOptions:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/title","value":"SKWAudioSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/fragments","value":[{"text":"SKWAudioSettings","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/navigatorTitle","value":[{"text":"SKWAudioSettings","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}