{"variants":[{"paths":["\/documentation\/skywayroom\/membertype\/bot"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/membertype\/bot"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bot","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/bot"},"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bot"}],"externalID":"c:@E@SKWMemberType@SKWMemberTypeBot","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"SKWMemberTypeBot","kind":"identifier"}],"title":"MemberType.bot","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType"]]},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberType"}],"url":"\/documentation\/skywayroom\/membertype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MemberType"}],"type":"topic","title":"MemberType","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType","abstract":[{"text":"メンバータイプ","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType/bot":{"url":"\/documentation\/skywayroom\/membertype\/bot","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bot","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/bot","title":"MemberType.bot","navigatorTitle":[{"text":"SKWMemberTypeBot","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SKWMemberTypeBot","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SKWMemberTypeBot","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SKWMemberTypeBot"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/title","value":"SKWMemberType"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/fragments","value":[{"text":"SKWMemberType","kind":"identifier"}]},{"op":"replace","value":[{"text":"SKWMemberType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/navigatorTitle"},{"op":"replace","value":"SKWMemberTypeBot","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType~1bot\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SKWMemberTypeBot"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType~1bot\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}