{"kind":"article","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/membertype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType"]]},"metadata":{"roleHeading":"API Collection","modules":[{"name":"SkyWayRoom"}],"role":"collectionGroup","title":"Equatable Implementations"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/!=(_:_:)"],"generated":true}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberType"}],"url":"\/documentation\/skywayroom\/membertype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MemberType"}],"type":"topic","title":"MemberType","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType","abstract":[{"text":"メンバータイプ","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType/!=(_:_:)":{"url":"\/documentation\/skywayroom\/membertype\/!=(_:_:)","type":"topic","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/title","value":"SKWMemberType"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/fragments","value":[{"kind":"identifier","text":"SKWMemberType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/navigatorTitle","value":[{"text":"SKWMemberType","kind":"identifier"}]}]}]}