{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/context\/setupfordev(withappid:secretkey:options:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/context\/setupfordev(withappid:secretkey:options:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupForDev","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secretKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContextOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions","preciseIdentifier":"c:objc(cs)SKWContextOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"]},{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupForDev","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAppId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secretKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContextOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions","preciseIdentifier":"c:objc(cs)SKWContextOptions","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"appId","content":[{"inlineContent":[{"text":"アプリケーションID","type":"text"}],"type":"paragraph"}]},{"name":"secretKey","content":[{"inlineContent":[{"text":"シークレットキー","type":"text"}],"type":"paragraph"}]},{"name":"options","content":[{"inlineContent":[{"text":"初期化オプション","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"完了コールバック","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"style":"warning","name":"Warning","content":[{"inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"このメソッドは、クイックスタートなどアプリの動作を確認する際に利用するためのものです。","type":"text"},{"text":" ","type":"text"},{"text":"認証情報の漏洩を防ぐため、このメソッドをリリース版アプリで利用することは控えてください。","type":"text"}],"type":"paragraph"}],"type":"aside"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Context"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:objc(cs)SKWContext(cm)setupForDevWithAppId:secretKey:options:completion:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupForDev","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAppId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secretKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContextOptions","preciseIdentifier":"c:objc(cs)SKWContextOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"setupForDevWithAppId:secretKey:options:completion:","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","title":"setupForDev(withAppId:secretKey:options:completion:)"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Context\/setupForDev(withAppId:secretKey:options:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"SkyWayの初期化をします。"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Context/setupForDev(withAppId:secretKey:options:completion:)":{"url":"\/documentation\/skywayroom\/context\/setupfordev(withappid:secretkey:options:completion:)","type":"topic","abstract":[{"type":"text","text":"SkyWayの初期化をします。"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupForDev"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAppId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secretKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWContextOptions","text":"ContextOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Context\/setupForDev(withAppId:secretKey:options:completion:)","title":"setupForDev(withAppId:secretKey:options:completion:)","navigatorTitle":[{"kind":"identifier","text":"setupForDevWithAppId:secretKey:options:completion:"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Context":{"url":"\/documentation\/skywayroom\/context","navigatorTitle":[{"kind":"identifier","text":"Context"}],"type":"topic","kind":"symbol","title":"Context","abstract":[{"text":"SkyWay全体の設定、取得を行うStaticなコンテキスト","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Context","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Context"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWContextSetupCompletion":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SKWContextSetupCompletion","kind":"identifier"}],"url":"\/documentation\/skywayroom\/skwcontextsetupcompletion","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SKWContextSetupCompletion"}],"type":"topic","title":"SKWContextSetupCompletion","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWContextSetupCompletion","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptions","kind":"identifier"}],"url":"\/documentation\/skywayroom\/contextoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContextOptions"}],"type":"topic","title":"ContextOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions","abstract":[{"type":"text","text":"コンテキストの初期化オプション"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setupForDevWithAppId:secretKey:options:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"setupForDevWithAppId:secretKey:options:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setupForDevWithAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"appId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"secretKey:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"secretKey","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions","text":"SKWContextOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWContextOptions"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWContextSetupCompletion","text":"SKWContextSetupCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SKWContext.h@T@SKWContextSetupCompletion"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"アプリケーションID"}],"type":"paragraph"}],"name":"appId"},{"content":[{"inlineContent":[{"type":"text","text":"シークレットキー"}],"type":"paragraph"}],"name":"secretKey"},{"content":[{"inlineContent":[{"type":"text","text":"初期化オプション"}],"type":"paragraph"}],"name":"options"},{"content":[{"inlineContent":[{"type":"text","text":"完了コールバック"}],"type":"paragraph"}],"name":"completion"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"setupForDevWithAppId:secretKey:options:completion:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Context~1setupForDev(withAppId:secretKey:options:completion:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"setupForDevWithAppId:secretKey:options:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Context~1setupForDev(withAppId:secretKey:options:completion:)\/fragments","op":"replace"},{"value":"SKWContext","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Context\/title","op":"replace"},{"value":[{"text":"SKWContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Context\/fragments","op":"replace"},{"value":[{"text":"SKWContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Context\/navigatorTitle","op":"replace"},{"value":"SKWContextSetupCompletion","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWContextSetupCompletion\/title","op":"replace"},{"value":[{"text":"SKWContextSetupCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWContextSetupCompletion\/fragments","op":"replace"},{"value":[{"text":"SKWContextSetupCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWContextSetupCompletion\/navigatorTitle","op":"replace"},{"value":"SKWContextOptions","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/title","op":"replace"},{"value":[{"text":"SKWContextOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/fragments","op":"replace"},{"value":[{"text":"SKWContextOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}