{"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Class","modules":[{"name":"SkyWayRoom"}],"title":"AudioSettings","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioSettings","kind":"identifier"}],"navigatorTitle":[{"text":"AudioSettings","kind":"identifier"}],"externalID":"c:objc(cs)SKWAudioSettings"},"sections":[],"kind":"symbol","abstract":[{"text":"音声入出力の設定クラス","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioSettings","kind":"identifier"}]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/audiosettings"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/audiosettings"]}],"topicSections":[{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/currentCategoryOptions()","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/currentPreferredSampleRate()","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/setCategoryOptions(_:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/setPreferredSampleRate(_:)"]}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings/currentPreferredSampleRate()":{"url":"\/documentation\/skywayroom\/audiosettings\/currentpreferredsamplerate()","type":"topic","abstract":[{"text":"現在設定されている優先サンプルレートを返します。","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentPreferredSampleRate","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/currentPreferredSampleRate()","title":"currentPreferredSampleRate()","navigatorTitle":[{"text":"currentPreferredSampleRate","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings/setCategoryOptions(_:)":{"url":"\/documentation\/skywayroom\/audiosettings\/setcategoryoptions(_:)","title":"setCategoryOptions(_:)","abstract":[{"text":"音声出力先についての設定ができます。任意のタイミングで設定が可能です。","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCategoryOptions","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/setCategoryOptions(_:)","type":"topic","navigatorTitle":[{"text":"setCategoryOptions:","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings/setPreferredSampleRate(_:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPreferredSampleRate","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/skywayroom\/audiosettings\/setpreferredsamplerate(_:)","role":"symbol","navigatorTitle":[{"text":"setPreferredSampleRate:","kind":"identifier"}],"type":"topic","title":"setPreferredSampleRate(_:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/setPreferredSampleRate(_:)","abstract":[{"text":"音声の優先サンプルレートを設定します。音声が疎通するタイミングで設定されている値が使用されます。","type":"text"}]},"doc://com.ntt.skyway.room/objc(cs)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudioSettings","kind":"identifier"}],"url":"\/documentation\/skywayroom\/audiosettings","role":"symbol","navigatorTitle":[{"text":"AudioSettings","kind":"identifier"}],"type":"topic","title":"AudioSettings","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings","abstract":[{"text":"音声入出力の設定クラス","type":"text"}]},"doc://com.ntt.skyway.room/s7CVarArgP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/AudioSettings/currentCategoryOptions()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentCategoryOptions"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions","kind":"typeIdentifier"}],"url":"\/documentation\/skywayroom\/audiosettings\/currentcategoryoptions()","role":"symbol","navigatorTitle":[{"text":"currentCategoryOptions","kind":"identifier"}],"type":"topic","title":"currentCategoryOptions()","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/currentCategoryOptions()","abstract":[{"type":"text","text":"現在使用されている"},{"type":"codeVoice","code":"AVAudioSessionCategoryOptions"},{"type":"text","text":"設定を返します。"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SKWAudioSettings","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SKWAudioSettings"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SKWAudioSettings","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/currentCategoryOptions()","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/currentPreferredSampleRate()","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/setCategoryOptions(_:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/AudioSettings\/setPreferredSampleRate(_:)"],"generated":true,"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWAudioSettings"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1currentPreferredSampleRate()\/title","value":"currentPreferredSampleRate","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1currentPreferredSampleRate()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"currentPreferredSampleRate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1setCategoryOptions(_:)\/title","value":"setCategoryOptions:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1setCategoryOptions(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setCategoryOptions:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1setPreferredSampleRate(_:)\/title","value":"setPreferredSampleRate:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1setPreferredSampleRate(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setPreferredSampleRate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/title","value":"SKWAudioSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/fragments","value":[{"kind":"identifier","text":"SKWAudioSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings\/navigatorTitle","value":[{"kind":"identifier","text":"SKWAudioSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1currentCategoryOptions()\/title","value":"currentCategoryOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1AudioSettings~1currentCategoryOptions()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"currentCategoryOptions"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}