{"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSCoding","doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/objc(pl)CALayerDelegate","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.ntt.skyway.room\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.ntt.skyway.room\/objc(pl)UIAppearance","doc:\/\/com.ntt.skyway.room\/objc(pl)UIAppearanceContainer","doc:\/\/com.ntt.skyway.room\/objc(pl)UIDynamicItem","doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusEnvironment","doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusItem","doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusItemContainer","doc:\/\/com.ntt.skyway.room\/objc(pl)UILargeContentViewerItem","doc:\/\/com.ntt.skyway.room\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.ntt.skyway.room\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.ntt.skyway.room\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.ntt.skyway.room\/5UIKit23UITraitChangeObservableP","doc:\/\/com.ntt.skyway.room\/objc(pl)UITraitEnvironment","doc:\/\/com.ntt.skyway.room\/objc(pl)UIUserActivityRestoring","doc:\/\/com.ntt.skyway.room\/objc(pl)UICoordinateSpace"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/skywayroom\/camerapreviewview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/camerapreviewview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"カメラプレビュー用View","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView\/rendererView","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView\/videoGravity"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewView","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"描画するためには","type":"text"},{"type":"codeVoice","code":"SKWCameraVideoSource"},{"text":"の","type":"text"},{"type":"codeVoice","code":"attachView(_)"},{"text":"に引数を渡してください。","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"StoryboardのCustom","type":"text"},{"text":" ","type":"text"},{"text":"Classを利用する場合は","type":"text"},{"type":"codeVoice","code":"CameraPreviewView"},{"text":"ではなく","type":"text"},{"type":"codeVoice","code":"SKWCameraPreviewView"},{"text":"を指定して下さい。","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewView","kind":"identifier"}],"externalID":"c:objc(cs)SKWCameraPreviewView","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"CameraPreviewView","kind":"identifier"}],"title":"CameraPreviewView","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"kind":"symbol","references":{"doc://com.ntt.skyway.room/s7CVarArgP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ntt.skyway.room/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://com.ntt.skyway.room/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.ntt.skyway.room/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIUtilities.UICoordinateSpace"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraPreviewView/rendererView":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/skywayroom\/camerapreviewview\/rendererview","role":"symbol","navigatorTitle":[{"text":"rendererView","kind":"identifier"}],"type":"topic","title":"rendererView","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView\/rendererView","abstract":[{"type":"text","text":"Wrapしているレンダラービュー"}]},"doc://com.ntt.skyway.room/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://com.ntt.skyway.room/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.ntt.skyway.room/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.ntt.skyway.room/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.ntt.skyway.room/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.ntt.skyway.room/objc(cs)UIView":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraPreviewView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewView","kind":"identifier"}],"url":"\/documentation\/skywayroom\/camerapreviewview","role":"symbol","navigatorTitle":[{"text":"CameraPreviewView","kind":"identifier"}],"type":"topic","title":"CameraPreviewView","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView","abstract":[{"type":"text","text":"カメラプレビュー用View"}]},"doc://com.ntt.skyway.room/objc(pl)NSCoding":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.ntt.skyway.room/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://com.ntt.skyway.room/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://com.ntt.skyway.room/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.ntt.skyway.room/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraPreviewView/videoGravity":{"url":"\/documentation\/skywayroom\/camerapreviewview\/videogravity","navigatorTitle":[{"kind":"identifier","text":"videoGravity"}],"type":"topic","kind":"symbol","abstract":[{"text":"映像の描画モード","type":"text"}],"title":"videoGravity","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView\/videoGravity","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoGravity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVLayerVideoGravity","text":"AVLayerVideoGravity"}]},"doc://com.ntt.skyway.room/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.ntt.skyway.room/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://com.ntt.skyway.room/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SKWCameraPreviewView","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SKWCameraPreviewView","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SKWCameraPreviewView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView\/rendererView","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView\/videoGravity"],"generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)UIView"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWCameraPreviewView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"rendererView","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView~1rendererView\/title"},{"op":"replace","value":[{"text":"rendererView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView~1rendererView\/fragments"},{"op":"replace","value":"SKWCameraPreviewView","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/title"},{"op":"replace","value":[{"text":"SKWCameraPreviewView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/fragments"},{"op":"replace","value":[{"text":"SKWCameraPreviewView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/navigatorTitle"},{"op":"replace","value":"videoGravity","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView~1videoGravity\/title"},{"op":"replace","value":[{"text":"videoGravity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView~1videoGravity\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}