{
  "abstract": [
    {
      "text": "チャンネル",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:objc(cs)SKWChannel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Channel"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Channel"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "Channel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Channel"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/SH": {
      "identifier": "doc://com.ntt.skyway.room/SH",
      "title": "Swift.Hashable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/SQ": {
      "identifier": "doc://com.ntt.skyway.room/SQ",
      "title": "Swift.Equatable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel": {
      "abstract": [
        {
          "text": "チャンネル",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Channel"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Channel"
        }
      ],
      "role": "symbol",
      "title": "Channel",
      "type": "topic",
      "url": "/documentation/skywayroom/channel"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/bots": {
      "abstract": [
        {
          "text": "Channelに参加しているBotの一覧",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bots"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWRemoteMember",
          "text": "RemoteMember"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/bots",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bots"
        }
      ],
      "role": "symbol",
      "title": "bots",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/bots"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/close(completion:)": {
      "abstract": [
        {
          "text": "Channelを閉じます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "close"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/close(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "closeWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "close(completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/close(completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/create(with:completion:)": {
      "abstract": [
        {
          "text": "Channelを新規作成します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "create"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWChannelInit",
          "text": "ChannelInit"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWChannel",
          "text": "Channel"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/create(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createWithInit:completion:"
        }
      ],
      "role": "symbol",
      "title": "create(with:completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/create(with:completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/delegate": {
      "abstract": [
        {
          "text": "イベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SKWChannelDelegate",
          "text": "ChannelDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/delegate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/dispose(completion:)": {
      "abstract": [
        {
          "text": "Channelを閉じずにChannelインスタンスを無効にし、非同期的にリソースを解放します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dispose"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/dispose(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disposeWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "dispose(completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/dispose(completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/find(with:completion:)": {
      "abstract": [
        {
          "text": "クエリからChannelを検索します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "find"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWChannelQuery",
          "text": "ChannelQuery"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWChannel",
          "text": "Channel"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/find(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findWithQuery:completion:"
        }
      ],
      "role": "symbol",
      "title": "find(with:completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/find(with:completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/findOrCreate(with:completion:)": {
      "abstract": [
        {
          "text": "Channelを名前から検索し、存在しない場合は新規作成します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findOrCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWChannelInit",
          "text": "ChannelInit"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWChannel",
          "text": "Channel"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/findOrCreate(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findOrCreateWithInit:completion:"
        }
      ],
      "role": "symbol",
      "title": "findOrCreate(with:completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/findorcreate(with:completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/id": {
      "abstract": [
        {
          "text": "Channel識別子",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/id",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "id"
        }
      ],
      "role": "symbol",
      "title": "id",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/id"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/join(with:completion:)": {
      "abstract": [
        {
          "text": "Channelに参加し、LocalPersonを作成します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "join"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWMemberInit",
          "text": "MemberInit"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWLocalPerson",
          "text": "LocalPerson"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/join(with:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "joinWithInit:completion:"
        }
      ],
      "role": "symbol",
      "title": "join(with:completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/join(with:completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/leaveMember(_:completion:)": {
      "abstract": [
        {
          "text": "ChannelからMemberを退出させます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leaveMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWMember",
          "text": "Member"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/leaveMember(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leaveMember:completion:"
        }
      ],
      "role": "symbol",
      "title": "leaveMember(_:completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/leavemember(_:completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/localPerson": {
      "abstract": [
        {
          "text": "ChannelインスタンスにこのSDKから参加したLocalPerson",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWLocalPerson",
          "text": "LocalPerson"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/localPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPerson"
        }
      ],
      "role": "symbol",
      "title": "localPerson",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/localperson"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/members": {
      "abstract": [
        {
          "text": "Channelに参加しているMemberの一覧",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "members"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWMember",
          "text": "Member"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/members",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "members"
        }
      ],
      "role": "symbol",
      "title": "members",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/members"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/metadata": {
      "abstract": [
        {
          "text": "Channelに付与されているメタデータ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/metadata"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/name": {
      "abstract": [
        {
          "text": "Channelの名前",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/name"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/publications": {
      "abstract": [
        {
          "text": "Channelに紐づく全てのPublicationの一覧",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publications"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/publications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publications"
        }
      ],
      "role": "symbol",
      "title": "publications",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/publications"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/state": {
      "abstract": [
        {
          "text": "Channelの状態",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKWChannelState",
          "text": "ChannelState"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/state"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/subscriptions": {
      "abstract": [
        {
          "text": "Channelに紐づく全てのSubscriptionの一覧",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWSubscription",
          "text": "Subscription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/subscriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptions"
        }
      ],
      "role": "symbol",
      "title": "subscriptions",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/subscriptions"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/updateMetadata(_:completion:)": {
      "abstract": [
        {
          "text": "メタデータを更新します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateMetadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/updateMetadata(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateMetadata:completion:"
        }
      ],
      "role": "symbol",
      "title": "updateMetadata(_:completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/channel/updatemetadata(_:completion:)"
    },
    "doc://com.ntt.skyway.room/objc(cs)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(cs)NSObject",
      "title": "NSObject",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/objc(pl)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(pl)NSObject",
      "title": "ObjectiveC.NSObjectProtocol",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s23CustomStringConvertibleP": {
      "identifier": "doc://com.ntt.skyway.room/s23CustomStringConvertibleP",
      "title": "Swift.CustomStringConvertible",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP": {
      "identifier": "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP",
      "title": "Swift.CustomDebugStringConvertible",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s7CVarArgP": {
      "identifier": "doc://com.ntt.skyway.room/s7CVarArgP",
      "title": "Swift.CVarArg",
      "type": "unresolvable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(pl)NSObject",
        "doc://com.ntt.skyway.room/s7CVarArgP",
        "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP",
        "doc://com.ntt.skyway.room/s23CustomStringConvertibleP",
        "doc://com.ntt.skyway.room/SQ",
        "doc://com.ntt.skyway.room/SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/bots",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/delegate",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/id",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/localPerson",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/members",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/metadata",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/name",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/publications",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/state",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/subscriptions"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/close(completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/dispose(completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/join(with:completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/leaveMember(_:completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/updateMetadata(_:completion:)"
      ],
      "title": "Instance Methods"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/create(with:completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/find(with:completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/findOrCreate(with:completion:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKWChannel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/bots",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/delegate",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/id",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/localPerson",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/members",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/metadata",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/name",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/publications",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/state",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/subscriptions"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/close(completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/dispose(completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/join(with:completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/leaveMember(_:completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/updateMetadata(_:completion:)"
              ],
              "title": "Instance Methods"
            },
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/create(with:completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/find(with:completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/findOrCreate(with:completion:)"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.ntt.skyway.room/objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKWChannel"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1bots/title",
          "value": "bots"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1bots/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bots"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1leaveMember(_:completion:)/title",
          "value": "leaveMember:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1leaveMember(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "leaveMember:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1updateMetadata(_:completion:)/title",
          "value": "updateMetadata:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1updateMetadata(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateMetadata:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1close(completion:)/title",
          "value": "closeWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1close(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "closeWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1subscriptions/title",
          "value": "subscriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1subscriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1create(with:completion:)/title",
          "value": "createWithInit:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1create(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "createWithInit:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1members/title",
          "value": "members"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1members/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "members"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1join(with:completion:)/title",
          "value": "joinWithInit:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1join(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "joinWithInit:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1id/title",
          "value": "id"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1id/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "id"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel/title",
          "value": "SKWChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1localPerson/title",
          "value": "localPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1localPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1publications/title",
          "value": "publications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1publications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "publications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1find(with:completion:)/title",
          "value": "findWithQuery:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1find(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "findWithQuery:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1dispose(completion:)/title",
          "value": "disposeWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1dispose(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "disposeWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1findOrCreate(with:completion:)/title",
          "value": "findOrCreateWithInit:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1findOrCreate(with:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "findOrCreateWithInit:completion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/channel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/channel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
