{"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/SY","doc:\/\/com.ntt.skyway.room\/s8SendableP","doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP"]}],"variants":[{"paths":["\/documentation\/skywayroom\/contenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/contenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"コンテントタイプ"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/audio","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/data","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/video"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/Equatable-Implementations","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContentType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:@E@SKWContentType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContentType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ContentType","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"ContentType"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContentType":{"url":"\/documentation\/skywayroom\/contenttype","type":"topic","abstract":[{"type":"text","text":"コンテントタイプ"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContentType","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType","title":"ContentType","navigatorTitle":[{"text":"ContentType","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s16SendableMetatypeP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.ntt.skyway.room/SY":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SY","title":"Swift.RawRepresentable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContentType/Equatable-Implementations":{"url":"\/documentation\/skywayroom\/contenttype\/equatable-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/Equatable-Implementations","title":"Equatable Implementations","kind":"article"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContentType/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/skywayroom\/contenttype\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/RawRepresentable-Implementations","abstract":[]},"doc://com.ntt.skyway.room/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.ntt.skyway.room/s8SendableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContentType/data":{"url":"\/documentation\/skywayroom\/contenttype\/data","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/data","title":"ContentType.data","navigatorTitle":[{"kind":"identifier","text":"SKWContentTypeData"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContentType/audio":{"url":"\/documentation\/skywayroom\/contenttype\/audio","title":"ContentType.audio","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"audio","kind":"identifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/audio","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SKWContentTypeAudio"}]},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContentType/init(rawValue:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"url":"\/documentation\/skywayroom\/contenttype\/init(rawvalue:)","role":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/init(rawValue:)","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContentType/video":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"video"}],"url":"\/documentation\/skywayroom\/contenttype\/video","role":"symbol","navigatorTitle":[{"text":"SKWContentTypeVideo","kind":"identifier"}],"type":"topic","title":"ContentType.video","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/video","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","value":"SKWContentType","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SKWContentType"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SKWContentType","kind":"identifier"}]},{"op":"replace","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/audio","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/data","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContentType\/video"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SKWContentType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SKWContentType","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType\/fragments","value":[{"text":"SKWContentType","kind":"identifier"}]},{"op":"replace","value":[{"text":"SKWContentType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType\/navigatorTitle"},{"op":"replace","value":"SKWContentTypeData","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType~1data\/title"},{"op":"replace","value":[{"text":"SKWContentTypeData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType~1data\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType~1audio\/title","value":"SKWContentTypeAudio"},{"op":"replace","value":[{"text":"SKWContentTypeAudio","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType~1audio\/fragments"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType~1video\/title","op":"replace","value":"SKWContentTypeVideo"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContentType~1video\/fragments","op":"replace","value":[{"text":"SKWContentTypeVideo","kind":"identifier"}]}]}]}