{"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Class","modules":[{"name":"SkyWayRoom"}],"title":"ContextOptionsICEParams","role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextOptionsICEParams"}],"navigatorTitle":[{"text":"ContextOptionsICEParams","kind":"identifier"}],"externalID":"c:objc(cs)SKWContextOptionsICEParams"},"sections":[],"kind":"symbol","abstract":[{"text":"内部向けオプション","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContextOptionsICEParams"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH"]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/skywayroom\/contextoptionsiceparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/contextoptionsiceparams"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/domain","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/secure","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/version"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsICEParams/domain":{"url":"\/documentation\/skywayroom\/contextoptionsiceparams\/domain","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"domain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/domain","title":"domain","navigatorTitle":[{"text":"domain","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsICEParams/secure":{"url":"\/documentation\/skywayroom\/contextoptionsiceparams\/secure","title":"secure","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"secure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/secure","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secure"}]},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.ntt.skyway.room/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject","title":"NSObject"},"doc://com.ntt.skyway.room/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ntt.skyway.room/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SQ","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.ntt.skyway.room/SH":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SH","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsICEParams":{"url":"\/documentation\/skywayroom\/contextoptionsiceparams","navigatorTitle":[{"text":"ContextOptionsICEParams","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ContextOptionsICEParams","abstract":[{"text":"内部向けオプション","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptionsICEParams","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsICEParams/version":{"url":"\/documentation\/skywayroom\/contextoptionsiceparams\/version","navigatorTitle":[{"kind":"identifier","text":"version"}],"type":"topic","kind":"symbol","title":"version","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/version","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SKWContextOptionsICEParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SKWContextOptionsICEParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SKWContextOptionsICEParams"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/domain","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/secure","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams\/version"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWContextOptionsICEParams","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams~1domain\/title","value":"domain"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams~1domain\/fragments","value":[{"kind":"identifier","text":"domain"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams~1secure\/title","value":"secure"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams~1secure\/fragments","value":[{"kind":"identifier","text":"secure"}]},{"op":"replace","value":"SKWContextOptionsICEParams","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams\/fragments","value":[{"kind":"identifier","text":"SKWContextOptionsICEParams"}]},{"op":"replace","value":[{"kind":"identifier","text":"SKWContextOptionsICEParams"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams\/navigatorTitle"},{"op":"replace","value":"version","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams~1version\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams~1version\/fragments","value":[{"text":"version","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}