{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptionsAnalytics","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/contextoptionsanalytics"]},{"paths":["\/documentation\/skywayroom\/contextoptionsanalytics"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptionsAnalytics","kind":"identifier"}],"externalID":"c:objc(cs)SKWContextOptionsAnalytics","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"kind":"identifier","text":"ContextOptionsAnalytics"}],"title":"ContextOptionsAnalytics","symbolKind":"class"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"内部向けオプション"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsAnalytics\/domain","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsAnalytics\/secure"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsAnalytics","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH"],"title":"Conforms To"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsAnalytics":{"url":"\/documentation\/skywayroom\/contextoptionsanalytics","navigatorTitle":[{"text":"ContextOptionsAnalytics","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"内部向けオプション","type":"text"}],"title":"ContextOptionsAnalytics","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsAnalytics","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptionsAnalytics","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SQ"},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP"},"doc://com.ntt.skyway.room/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"},"doc://com.ntt.skyway.room/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SH"},"doc://com.ntt.skyway.room/s7CVarArgP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsAnalytics/domain":{"url":"\/documentation\/skywayroom\/contextoptionsanalytics\/domain","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"domain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsAnalytics\/domain","title":"domain","navigatorTitle":[{"kind":"identifier","text":"domain"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsAnalytics/secure":{"url":"\/documentation\/skywayroom\/contextoptionsanalytics\/secure","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsAnalytics\/secure","title":"secure","navigatorTitle":[{"kind":"identifier","text":"secure"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"SKWContextOptionsAnalytics","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWContextOptionsAnalytics","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SKWContextOptionsAnalytics"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsAnalytics\/domain","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsAnalytics\/secure"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWContextOptionsAnalytics","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SKWContextOptionsAnalytics","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsAnalytics\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SKWContextOptionsAnalytics"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsAnalytics\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SKWContextOptionsAnalytics"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsAnalytics\/navigatorTitle"},{"op":"replace","value":"domain","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsAnalytics~1domain\/title"},{"op":"replace","value":[{"kind":"identifier","text":"domain"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsAnalytics~1domain\/fragments"},{"op":"replace","value":"secure","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsAnalytics~1secure\/title"},{"op":"replace","value":[{"kind":"identifier","text":"secure"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsAnalytics~1secure\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}