{"kind":"symbol","abstract":[{"text":"画像フレームの映像入力ソース","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoSource"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomFrameVideoSource","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"type":"codeVoice","code":"CMSampleBuffer"},{"text":"の画像フレームをループ内からアップデートして描画を行います。","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"ReplayKitと組み合わせることでアプリの画面をソースにして画面共有が行えます。","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["let source: CustomFrameVideoSource = .init()","RPScreenRecorder.shared().startCapture { buffer, _, err in","    guard err == nil else {","        return","    }","    source.updateFrame(with: buffer)","} completionHandler: { _ in }","","let stream = source.createStream()"]}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/customframevideosource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/customframevideosource"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"symbolKind":"class","title":"CustomFrameVideoSource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomFrameVideoSource","kind":"identifier"}],"navigatorTitle":[{"text":"CustomFrameVideoSource","kind":"identifier"}],"role":"symbol","roleHeading":"Class","externalID":"c:objc(cs)SKWCustomFrameVideoSource","modules":[{"name":"SkyWayRoom"}]},"topicSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/init()"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/createStream()","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/updateFrame(with:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CustomFrameVideoSource/createStream()":{"abstract":[{"type":"text","text":"Streamを作成します。"}],"title":"createStream()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createStream","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"LocalVideoStream","preciseIdentifier":"c:objc(cs)SKWLocalVideoStream","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/createStream()","navigatorTitle":[{"text":"createStream","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/customframevideosource\/createstream()","type":"topic"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CustomFrameVideoSource":{"url":"\/documentation\/skywayroom\/customframevideosource","type":"topic","abstract":[{"type":"text","text":"画像フレームの映像入力ソース"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomFrameVideoSource","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource","title":"CustomFrameVideoSource","navigatorTitle":[{"text":"CustomFrameVideoSource","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s7CVarArgP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CustomFrameVideoSource/updateFrame(with:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/customframevideosource\/updateframe(with:)","role":"symbol","navigatorTitle":[{"text":"updateFrameWithSampleBuffer:","kind":"identifier"}],"type":"topic","title":"updateFrame(with:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/updateFrame(with:)","abstract":[{"type":"text","text":"画像のサンプルバッファを更新します。"}]},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/VideoSource":{"url":"\/documentation\/skywayroom\/videosource","type":"topic","abstract":[{"text":"映像入力ソースの抽象クラス","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoSource"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoSource","title":"VideoSource","navigatorTitle":[{"kind":"identifier","text":"VideoSource"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CustomFrameVideoSource/init()":{"url":"\/documentation\/skywayroom\/customframevideosource\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol","title":"init()","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SKWCustomFrameVideoSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWCustomFrameVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SKWCustomFrameVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/createStream()","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/init()","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/updateFrame(with:)"],"anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoSource"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWCustomFrameVideoSource","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoSource","text":"SKWVideoSource","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWVideoSource"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource~1createStream()\/title","op":"replace","value":"createStream"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource~1createStream()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createStream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource\/title","value":"SKWCustomFrameVideoSource"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource\/fragments","op":"replace","value":[{"text":"SKWCustomFrameVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource\/navigatorTitle","value":[{"text":"SKWCustomFrameVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource~1updateFrame(with:)\/title","value":"updateFrameWithSampleBuffer:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource~1updateFrame(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateFrameWithSampleBuffer:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoSource\/title","value":"SKWVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoSource\/fragments","value":[{"text":"SKWVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoSource\/navigatorTitle","value":[{"text":"SKWVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}