{"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/configure","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/delegate","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/identifier","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/originPublication","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/relayingPublication","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/state"],"title":"Instance Properties"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/forwarding"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/forwarding"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Forwarding","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"text":"Botがフォワードした時に取得できます。","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"externalID":"c:objc(cs)SKWForwarding","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Forwarding","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Forwarding","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","title":"Forwarding"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding"},"abstract":[{"text":"フォワーディング","type":"text"}],"references":{"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding/delegate":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"ForwardingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SKWForwardingDelegate"},{"text":")?","kind":"text"}],"url":"\/documentation\/skywayroom\/forwarding\/delegate","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","title":"delegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/delegate","abstract":[{"text":"イベントデリデート","type":"text"}]},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding/relayingPublication":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relayingPublication","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Publication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication"}],"url":"\/documentation\/skywayroom\/forwarding\/relayingpublication","role":"symbol","navigatorTitle":[{"text":"relayingPublication","kind":"identifier"}],"type":"topic","title":"relayingPublication","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/relayingPublication","abstract":[{"text":"Forwardingを表すPublication","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding/identifier":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/skywayroom\/forwarding\/identifier","role":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic","title":"identifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/identifier","abstract":[{"text":"Forwarding識別子","type":"text"}]},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding/configure":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWForwardingConfigure","text":"ForwardingConfigure"}],"url":"\/documentation\/skywayroom\/forwarding\/configure","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"configure"}],"type":"topic","title":"configure","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/configure","abstract":[{"type":"text","text":"コンフィグ"}]},"doc://com.ntt.skyway.room/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"},"doc://com.ntt.skyway.room/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding/originPublication":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"originPublication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication"}],"url":"\/documentation\/skywayroom\/forwarding\/originpublication","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"originPublication"}],"type":"topic","title":"originPublication","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/originPublication","abstract":[{"type":"text","text":"Forwarding対象(オリジナル)のPublication"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Forwarding"}],"url":"\/documentation\/skywayroom\/forwarding","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Forwarding"}],"type":"topic","title":"Forwarding","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding","abstract":[{"type":"text","text":"フォワーディング"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Forwarding/state":{"url":"\/documentation\/skywayroom\/forwarding\/state","navigatorTitle":[{"kind":"identifier","text":"state"}],"type":"topic","kind":"symbol","title":"state","abstract":[{"text":"Forwardingの状態","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWForwardingState","text":"ForwardingState"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SKWForwarding","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWForwarding","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SKWForwarding","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/configure","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/delegate","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/identifier","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/originPublication","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/relayingPublication","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Forwarding\/state"],"anchor":"Instance-Properties"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWForwarding","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1relayingPublication\/title","value":"relayingPublication"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1relayingPublication\/fragments","value":[{"kind":"identifier","text":"relayingPublication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1configure\/title","value":"configure"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1configure\/fragments","value":[{"kind":"identifier","text":"configure"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1originPublication\/title","op":"replace","value":"originPublication"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1originPublication\/fragments","value":[{"text":"originPublication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding\/title","value":"SKWForwarding"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding\/fragments","value":[{"text":"SKWForwarding","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding\/navigatorTitle","value":[{"text":"SKWForwarding","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1state\/title","value":"state","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Forwarding~1state\/fragments","value":[{"kind":"identifier","text":"state"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}