{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStreamDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/localdatastreamdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/localdatastreamdelegate"]}],"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"text":"LocalDataStreamDelegate","kind":"identifier"}],"title":"LocalDataStreamDelegate","externalID":"c:objc(pl)SKWLocalDataStreamDelegate","symbolKind":"protocol","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStreamDelegate","kind":"identifier"}]},"kind":"symbol","sections":[],"abstract":[{"text":"LocalDataStreamイベントデリゲート","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeUnwritableFor:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeWritableFor:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate"},"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStreamDelegate/dataStream(_:didBecomeWritableFor:)":{"url":"\/documentation\/skywayroom\/localdatastreamdelegate\/datastream(_:didbecomewritablefor:)","navigatorTitle":[{"text":"dataStream:didBecomeWritableForSubscriber:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"dataStream(_:didBecomeWritableFor:)","abstract":[{"text":"データ送信が可能になった時にコールされるイベント","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeWritableFor:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWLocalDataStream","text":"LocalDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBecomeWritableFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DataStreamSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStreamDelegate":{"url":"\/documentation\/skywayroom\/localdatastreamdelegate","type":"topic","abstract":[{"text":"LocalDataStreamイベントデリゲート","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStreamDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate","title":"LocalDataStreamDelegate","navigatorTitle":[{"text":"LocalDataStreamDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStreamDelegate/dataStream(_:didBecomeUnwritableFor:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LocalDataStream","preciseIdentifier":"c:objc(cs)SKWLocalDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBecomeUnwritableFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DataStreamSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/localdatastreamdelegate\/datastream(_:didbecomeunwritablefor:)","role":"symbol","navigatorTitle":[{"text":"dataStream:didBecomeUnwritableForSubscriber:","kind":"identifier"}],"type":"topic","title":"dataStream(_:didBecomeUnwritableFor:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeUnwritableFor:)","abstract":[{"type":"text","text":"データ送信が不可能になった時にコールされるイベント"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SKWLocalDataStreamDelegate","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SKWLocalDataStreamDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SKWLocalDataStreamDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeUnwritableFor:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeWritableFor:)"],"anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWLocalDataStreamDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"dataStream:didBecomeWritableForSubscriber:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate~1dataStream(_:didBecomeWritableFor:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"dataStream:didBecomeWritableForSubscriber:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate~1dataStream(_:didBecomeWritableFor:)\/fragments","op":"replace"},{"value":"SKWLocalDataStreamDelegate","op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/fragments","value":[{"text":"SKWLocalDataStreamDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SKWLocalDataStreamDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate~1dataStream(_:didBecomeUnwritableFor:)\/title","value":"dataStream:didBecomeUnwritableForSubscriber:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate~1dataStream(_:didBecomeUnwritableFor:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataStream:didBecomeUnwritableForSubscriber:","kind":"identifier"}]}]}]}