{"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/delegate"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/publish(_:options:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/publish(_:options:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/subscribe(publicationId:options:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/subscribe(publicationId:options:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unpublish(publicationId:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unpublish(publicationId:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unsubscribe(subscriptionId:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unsubscribe(subscriptionId:completion:)"],"anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/LocalPersonDelegate-Implementations","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/MemberDelegate-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/localroommember"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/localroommember"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMember"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalP2PRoomMember","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalSFURoomMember"],"type":"inheritedBy"},{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPersonDelegate","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberDelegate","doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s8CopyableP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/s12IdentifiableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalRoomMember","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"inlineContent":[{"text":"このLocalMemberはRoomの","type":"text"},{"code":"join(with:)","type":"codeVoice"},{"text":"から生成できます。","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"一つのRoomインスタンスには一つのLocalRoomMemberがjoinでき、複数管理することはできません。","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"externalID":"c:@M@SkyWayRoom@objc(cs)LocalRoomMember","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalRoomMember","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"LocalRoomMember","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","title":"LocalRoomMember"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember","interfaceLanguage":"swift"},"abstract":[{"text":"RoomのLocalMember","type":"text"}],"references":{"doc://com.ntt.skyway.room/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/unsubscribe(subscriptionId:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"subscriptionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/skywayroom\/localroommember\/unsubscribe(subscriptionid:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unsubscribeWithSubscriptionId:completionHandler:"}],"type":"topic","title":"unsubscribe(subscriptionId:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unsubscribe(subscriptionId:)","abstract":[{"text":"Subscribeを中止します。","type":"text"}]},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/subscribe(publicationId:options:completion:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"publicationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SubscriptionOptions","preciseIdentifier":"c:objc(cs)SKWSubscriptionOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/skywayroom\/localroommember\/subscribe(publicationid:options:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"subscribeWithPublicationId:options:completion:"}],"type":"topic","title":"subscribe(publicationId:options:completion:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/subscribe(publicationId:options:completion:)","abstract":[{"text":"PublicationをSubscribeします。","type":"text"}]},"doc://com.ntt.skyway.room/SH":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SH","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/publish(_:options:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LocalStream","preciseIdentifier":"c:objc(cs)SKWLocalStream"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RoomPublicationOptions","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublicationOptions"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"RoomPublication","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication"}],"url":"\/documentation\/skywayroom\/localroommember\/publish(_:options:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"publish:options:completionHandler:"}],"type":"topic","title":"publish(_:options:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/publish(_:options:)","abstract":[{"text":"入室しているRoomにStreamをPublishします。","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/unpublish(publicationId:completion:)":{"url":"\/documentation\/skywayroom\/localroommember\/unpublish(publicationid:completion:)","type":"topic","abstract":[{"type":"text","text":"Publishを停止します。"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpublish"},{"kind":"text","text":"("},{"text":"publicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unpublish(publicationId:completion:)","title":"unpublish(publicationId:completion:)","navigatorTitle":[{"text":"unpublishWithPublicationId:completion:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/unpublish(publicationId:)":{"url":"\/documentation\/skywayroom\/localroommember\/unpublish(publicationid:)","type":"topic","abstract":[{"type":"text","text":"Publishを停止します。"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpublish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"publicationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unpublish(publicationId:)","title":"unpublish(publicationId:)","navigatorTitle":[{"kind":"identifier","text":"unpublishWithPublicationId:completionHandler:"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember":{"url":"\/documentation\/skywayroom\/localroommember","type":"topic","abstract":[{"text":"RoomのLocalMember","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalRoomMember"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember","title":"LocalRoomMember","navigatorTitle":[{"kind":"identifier","text":"LocalRoomMember"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberDelegate"}],"url":"\/documentation\/skywayroom\/memberdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MemberDelegate"}],"type":"topic","title":"MemberDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberDelegate","abstract":[{"type":"text","text":"Memberイベントデリゲート"}]},"doc://com.ntt.skyway.room/s12IdentifiableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s12IdentifiableP","title":"Swift.Identifiable","type":"unresolvable"},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalP2PRoomMember":{"url":"\/documentation\/skywayroom\/localp2proommember","navigatorTitle":[{"text":"LocalP2PRoomMember","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"P2PRoomのLocalMember"}],"title":"LocalP2PRoomMember","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalP2PRoomMember","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalP2PRoomMember"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/delegate":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LocalRoomMemberDelegate","preciseIdentifier":"c:@M@SkyWayRoom@objc(pl)LocalRoomMemberDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/skywayroom\/localroommember\/delegate","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","title":"delegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/delegate","abstract":[{"text":"イベントデリゲート","type":"text"}]},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/MemberDelegate-Implementations":{"kind":"article","title":"MemberDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/MemberDelegate-Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/skywayroom\/localroommember\/memberdelegate-implementations"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/subscribe(publicationId:options:)":{"url":"\/documentation\/skywayroom\/localroommember\/subscribe(publicationid:options:)","type":"topic","abstract":[{"text":"PublicationをSubscribeします。","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subscribe"},{"text":"(","kind":"text"},{"text":"publicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWSubscriptionOptions","text":"SubscriptionOptions","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/subscribe(publicationId:options:)","title":"subscribe(publicationId:options:)","navigatorTitle":[{"kind":"identifier","text":"subscribeWithPublicationId:options:completionHandler:"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s8CopyableP","title":"Swift.Copyable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/publish(_:options:completion:)":{"url":"\/documentation\/skywayroom\/localroommember\/publish(_:options:completion:)","type":"topic","abstract":[{"type":"text","text":"入室しているRoomにStreamをPublishします。"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"publish"},{"text":"(","kind":"text"},{"text":"LocalStream","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWLocalStream"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublicationOptions","text":"RoomPublicationOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"RoomPublication","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/publish(_:options:completion:)","title":"publish(_:options:completion:)","navigatorTitle":[{"kind":"identifier","text":"publish:options:completion:"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalSFURoomMember":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalSFURoomMember"}],"url":"\/documentation\/skywayroom\/localsfuroommember","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocalSFURoomMember"}],"type":"topic","title":"LocalSFURoomMember","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalSFURoomMember","abstract":[{"type":"text","text":"SFURoomのLocalMember"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMember":{"url":"\/documentation\/skywayroom\/roommember","navigatorTitle":[{"text":"RoomMember","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Roomに入室しているMemberの抽象クラス","type":"text"}],"title":"RoomMember","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMember","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomMember"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPersonDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalPersonDelegate"}],"url":"\/documentation\/skywayroom\/localpersondelegate","role":"symbol","navigatorTitle":[{"text":"LocalPersonDelegate","kind":"identifier"}],"type":"topic","title":"LocalPersonDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPersonDelegate","abstract":[{"type":"text","text":"LocalPersonイベントデリゲート"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/unsubscribe(subscriptionId:completion:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"subscriptionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/skywayroom\/localroommember\/unsubscribe(subscriptionid:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unsubscribeWithSubscriptionId:completion:"}],"type":"topic","title":"unsubscribe(subscriptionId:completion:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unsubscribe(subscriptionId:completion:)","abstract":[{"type":"text","text":"Subscribeを中止します。"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/LocalPersonDelegate-Implementations":{"url":"\/documentation\/skywayroom\/localroommember\/localpersondelegate-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/LocalPersonDelegate-Implementations","title":"LocalPersonDelegate Implementations","kind":"article"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"LocalRoomMember","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LocalRoomMember"}]},{"op":"replace","value":[{"kind":"identifier","text":"LocalRoomMember"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/delegate"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/publish(_:options:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/publish(_:options:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/subscribe(publicationId:options:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/subscribe(publicationId:options:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unpublish(publicationId:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unpublish(publicationId:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unsubscribe(subscriptionId:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/unsubscribe(subscriptionId:completion:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/LocalPersonDelegate-Implementations","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalRoomMember\/MemberDelegate-Implementations"],"anchor":"Default-Implementations","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMember"],"title":"Inherits From","kind":"relationships"},{"type":"inheritedBy","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalP2PRoomMember","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalSFURoomMember"],"title":"Inherited By","kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPersonDelegate"],"type":"conformsTo"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalRoomMember"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMember","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomMember","text":"RoomMember","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1unsubscribe(subscriptionId:)\/title","value":"unsubscribeWithSubscriptionId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1unsubscribe(subscriptionId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unsubscribeWithSubscriptionId:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1subscribe(publicationId:options:completion:)\/title","value":"subscribeWithPublicationId:options:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1subscribe(publicationId:options:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"subscribeWithPublicationId:options:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1publish(_:options:)\/title","value":"publish:options:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1publish(_:options:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"publish:options:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1unpublish(publicationId:completion:)\/title","value":"unpublishWithPublicationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1unpublish(publicationId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unpublishWithPublicationId:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1unpublish(publicationId:)\/title","value":"unpublishWithPublicationId:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1unpublish(publicationId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unpublishWithPublicationId:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember\/title","value":"LocalRoomMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember\/fragments","value":[{"text":"LocalRoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember\/navigatorTitle","value":[{"text":"LocalRoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate\/title","value":"SKWMemberDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate\/fragments","value":[{"text":"SKWMemberDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate\/navigatorTitle","value":[{"text":"SKWMemberDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalP2PRoomMember\/title","value":"LocalP2PRoomMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalP2PRoomMember\/fragments","value":[{"text":"LocalP2PRoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalP2PRoomMember\/navigatorTitle","value":[{"text":"LocalP2PRoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1subscribe(publicationId:options:)\/title","value":"subscribeWithPublicationId:options:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1subscribe(publicationId:options:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"subscribeWithPublicationId:options:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1publish(_:options:completion:)\/title","value":"publish:options:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1publish(_:options:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"publish:options:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalSFURoomMember\/title","value":"LocalSFURoomMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalSFURoomMember\/fragments","value":[{"text":"LocalSFURoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalSFURoomMember\/navigatorTitle","value":[{"text":"LocalSFURoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMember\/title","value":"RoomMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMember\/fragments","value":[{"text":"RoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMember\/navigatorTitle","value":[{"text":"RoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPersonDelegate\/title","value":"SKWLocalPersonDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPersonDelegate\/fragments","value":[{"text":"SKWLocalPersonDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPersonDelegate\/navigatorTitle","value":[{"text":"SKWLocalPersonDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1unsubscribe(subscriptionId:completion:)\/title","value":"unsubscribeWithSubscriptionId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1unsubscribe(subscriptionId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unsubscribeWithSubscriptionId:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}