{
  "abstract": [
    {
      "text": "LocalRoomMemberイベントデリゲート",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:@M@SkyWayRoom@objc(pl)LocalRoomMemberDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LocalRoomMemberDelegate"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LocalRoomMemberDelegate"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "LocalRoomMemberDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@objc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LocalRoomMemberDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@M@SkyWayRoom@objc(pl)RoomMemberDelegate",
              "text": "RoomMemberDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate": {
      "abstract": [
        {
          "text": "LocalRoomMemberイベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalRoomMemberDelegate"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalRoomMemberDelegate"
        }
      ],
      "role": "symbol",
      "title": "LocalRoomMemberDelegate",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommemberdelegate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didPublishStreamOf:)": {
      "abstract": [
        {
          "text": "LocalRoomMemberがStreamをPublishした後にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localRoomMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)LocalRoomMember",
          "text": "LocalRoomMember"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didPublishStreamOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomPublication",
          "text": "RoomPublication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didPublishStreamOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localRoomMember:didPublishStreamOf:"
        }
      ],
      "role": "symbol",
      "title": "localRoomMember(_:didPublishStreamOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommemberdelegate/localroommember(_:didpublishstreamof:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didSubscribePublicationOf:)": {
      "abstract": [
        {
          "text": "LocalRoomMemberがPublicationをSubscribeした後にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localRoomMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)LocalRoomMember",
          "text": "LocalRoomMember"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSubscribePublicationOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomSubscription",
          "text": "RoomSubscription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didSubscribePublicationOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localRoomMember:didSubscribePublicationOf:"
        }
      ],
      "role": "symbol",
      "title": "localRoomMember(_:didSubscribePublicationOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommemberdelegate/localroommember(_:didsubscribepublicationof:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnpublishStreamOf:)": {
      "abstract": [
        {
          "text": "LocalRoomMemberがStreamをUnpublishした後にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localRoomMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)LocalRoomMember",
          "text": "LocalRoomMember"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUnpublishStreamOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomPublication",
          "text": "RoomPublication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnpublishStreamOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localRoomMember:didUnpublishStreamOf:"
        }
      ],
      "role": "symbol",
      "title": "localRoomMember(_:didUnpublishStreamOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommemberdelegate/localroommember(_:didunpublishstreamof:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnsubscribePublicationOf:)": {
      "abstract": [
        {
          "text": "LocalRoomMemberがPublicationをUnsubscribeした後にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localRoomMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)LocalRoomMember",
          "text": "LocalRoomMember"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUnsubscribePublicationOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomSubscription",
          "text": "RoomSubscription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnsubscribePublicationOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localRoomMember:didUnsubscribePublicationOf:"
        }
      ],
      "role": "symbol",
      "title": "localRoomMember(_:didUnsubscribePublicationOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommemberdelegate/localroommember(_:didunsubscribepublicationof:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate": {
      "abstract": [
        {
          "text": "RoomMemberイベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomMemberDelegate"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomMemberDelegate"
        }
      ],
      "role": "symbol",
      "title": "RoomMemberDelegate",
      "type": "topic",
      "url": "/documentation/skywayroom/roommemberdelegate"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didPublishStreamOf:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didSubscribePublicationOf:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnpublishStreamOf:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnsubscribePublicationOf:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "LocalRoomMemberDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didPublishStreamOf:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didSubscribePublicationOf:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnpublishStreamOf:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnsubscribePublicationOf:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "LocalRoomMemberDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@M@SkyWayRoom@objc(pl)RoomMemberDelegate",
                    "text": "RoomMemberDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didUnsubscribePublicationOf:)/title",
          "value": "localRoomMember:didUnsubscribePublicationOf:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didUnsubscribePublicationOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localRoomMember:didUnsubscribePublicationOf:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate/title",
          "value": "RoomMemberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didSubscribePublicationOf:)/title",
          "value": "localRoomMember:didSubscribePublicationOf:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didSubscribePublicationOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localRoomMember:didSubscribePublicationOf:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didPublishStreamOf:)/title",
          "value": "localRoomMember:didPublishStreamOf:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didPublishStreamOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localRoomMember:didPublishStreamOf:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didUnpublishStreamOf:)/title",
          "value": "localRoomMember:didUnpublishStreamOf:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didUnpublishStreamOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localRoomMember:didUnpublishStreamOf:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate/title",
          "value": "LocalRoomMemberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMemberDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/localroommemberdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/localroommemberdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
