{"kind":"symbol","topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LoggerDelegate\/didReceiveLog(_:at:)"],"anchor":"Instance-Methods"}],"sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/loggerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/loggerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"],"type":"inheritsFrom"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"text":"LoggerDelegate","kind":"identifier"}],"title":"LoggerDelegate","externalID":"c:objc(pl)SKWLoggerDelegate","symbolKind":"protocol","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggerDelegate"}]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LoggerDelegate","interfaceLanguage":"swift"},"abstract":[{"text":"Loggerイベントデリゲート","type":"text"}],"references":{"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LoggerDelegate/didReceiveLog(_:at:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didReceiveLog","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWLogLevel","text":"LogLevel"},{"kind":"text","text":")"}],"url":"\/documentation\/skywayroom\/loggerdelegate\/didreceivelog(_:at:)","role":"symbol","navigatorTitle":[{"text":"didReceiveLog:atLevel:","kind":"identifier"}],"type":"topic","title":"didReceiveLog(_:at:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LoggerDelegate\/didReceiveLog(_:at:)","abstract":[{"text":"SkyWay内部で出力したログのハンドラです。","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LoggerDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerDelegate","kind":"identifier"}],"url":"\/documentation\/skywayroom\/loggerdelegate","role":"symbol","navigatorTitle":[{"text":"LoggerDelegate","kind":"identifier"}],"type":"topic","title":"LoggerDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LoggerDelegate","abstract":[{"type":"text","text":"Loggerイベントデリゲート"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SKWLoggerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SKWLoggerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SKWLoggerDelegate","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LoggerDelegate\/didReceiveLog(_:at:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWLoggerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"didReceiveLog:atLevel:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LoggerDelegate~1didReceiveLog(_:at:)\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LoggerDelegate~1didReceiveLog(_:at:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didReceiveLog:atLevel:","kind":"identifier"}],"op":"replace"},{"value":"SKWLoggerDelegate","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LoggerDelegate\/title","op":"replace"},{"value":[{"text":"SKWLoggerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LoggerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LoggerDelegate\/navigatorTitle","op":"replace","value":[{"text":"SKWLoggerDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}