{"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/SY","doc:\/\/com.ntt.skyway.room\/s8SendableP","doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/skywayroom\/loglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"ログのレベル一覧"}],"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/debug","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/error","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/info","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/off","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/trace","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/warn"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/Equatable-Implementations","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"externalID":"c:@E@SKWLogLevel","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"title":"LogLevel","symbolKind":"enum"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/init(rawValue:)":{"url":"\/documentation\/skywayroom\/loglevel\/init(rawvalue:)","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel":{"url":"\/documentation\/skywayroom\/loglevel","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"ログのレベル一覧"}],"title":"LogLevel","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}]},"doc://com.ntt.skyway.room/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/Equatable-Implementations":{"url":"\/documentation\/skywayroom\/loglevel\/equatable-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/Equatable-Implementations","title":"Equatable Implementations","kind":"article"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/warn":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warn","kind":"identifier"}],"url":"\/documentation\/skywayroom\/loglevel\/warn","role":"symbol","navigatorTitle":[{"text":"SKWLogLevelWarn","kind":"identifier"}],"type":"topic","title":"LogLevel.warn","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/warn","abstract":[{"text":"SDK内部で発生した一時的なエラーに関する情報を出力します。","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/s16SendableMetatypeP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.ntt.skyway.room/SY":{"identifier":"doc:\/\/com.ntt.skyway.room\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.ntt.skyway.room/s8SendableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/error":{"url":"\/documentation\/skywayroom\/loglevel\/error","type":"topic","abstract":[{"text":"デフォルト値。異常に関する情報を出力します。このエラーが発生したメソッドからは無効値が返されます。","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/error","title":"LogLevel.error","navigatorTitle":[{"text":"SKWLogLevelError","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/trace":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trace"}],"url":"\/documentation\/skywayroom\/loglevel\/trace","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SKWLogLevelTrace"}],"type":"topic","title":"LogLevel.trace","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/trace","abstract":[{"type":"text","text":"メモリの破棄など、最も詳細なログを出力します。"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/RawRepresentable-Implementations":{"url":"\/documentation\/skywayroom\/loglevel\/rawrepresentable-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/debug":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"url":"\/documentation\/skywayroom\/loglevel\/debug","role":"symbol","navigatorTitle":[{"text":"SKWLogLevelDebug","kind":"identifier"}],"type":"topic","title":"LogLevel.debug","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/debug","abstract":[{"text":"イベントの発火やリクエスト・レスポンスに関する情報など、デバッグ時に参考となる情報を出力します。","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/info":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"url":"\/documentation\/skywayroom\/loglevel\/info","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SKWLogLevelInfo"}],"type":"topic","title":"LogLevel.info","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/info","abstract":[{"text":"SDK が提供しているメソッドの呼び出しに関する情報を出力します。","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LogLevel/off":{"url":"\/documentation\/skywayroom\/loglevel\/off","navigatorTitle":[{"text":"SKWLogLevelOff","kind":"identifier"}],"type":"topic","kind":"symbol","title":"LogLevel.off","abstract":[{"type":"text","text":"ログを出力しません。"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/off","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"off","kind":"identifier"}]},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SKWLogLevel","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SKWLogLevel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SKWLogLevel","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/debug","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/error","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/info","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/off","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/trace","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LogLevel\/warn"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWLogLevel","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SKWLogLevel","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel\/fragments","op":"replace","value":[{"text":"SKWLogLevel","kind":"identifier"}]},{"op":"replace","value":[{"text":"SKWLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1warn\/title","op":"replace","value":"SKWLogLevelWarn"},{"op":"replace","value":[{"text":"SKWLogLevelWarn","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1warn\/fragments"},{"op":"replace","value":"SKWLogLevelError","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1error\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1error\/fragments","value":[{"text":"SKWLogLevelError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1trace\/title","value":"SKWLogLevelTrace","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1trace\/fragments","value":[{"kind":"identifier","text":"SKWLogLevelTrace"}],"op":"replace"},{"op":"replace","value":"SKWLogLevelDebug","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1debug\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"SKWLogLevelDebug"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1info\/title","value":"SKWLogLevelInfo"},{"op":"replace","value":[{"text":"SKWLogLevelInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1info\/fragments"},{"op":"replace","value":"SKWLogLevelOff","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1off\/title"},{"op":"replace","value":[{"text":"SKWLogLevelOff","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LogLevel~1off\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}