{"kind":"symbol","abstract":[{"type":"text","text":"メンバータイプ"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/SY","doc:\/\/com.ntt.skyway.room\/s8SendableP","doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MemberType","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/membertype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/membertype"]}],"metadata":{"symbolKind":"enum","title":"MemberType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MemberType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MemberType"}],"role":"symbol","roleHeading":"Enumeration","externalID":"c:@E@SKWMemberType","modules":[{"name":"SkyWayRoom"}]},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/bot","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/person"],"generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/Equatable-Implementations","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"references":{"doc://com.ntt.skyway.room/s16SendableMetatypeP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberType"}],"url":"\/documentation\/skywayroom\/membertype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MemberType"}],"type":"topic","title":"MemberType","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType","abstract":[{"text":"メンバータイプ","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType/RawRepresentable-Implementations":{"url":"\/documentation\/skywayroom\/membertype\/rawrepresentable-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType/bot":{"url":"\/documentation\/skywayroom\/membertype\/bot","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bot","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/bot","title":"MemberType.bot","navigatorTitle":[{"text":"SKWMemberTypeBot","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType/person":{"url":"\/documentation\/skywayroom\/membertype\/person","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"person","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/person","title":"MemberType.person","navigatorTitle":[{"kind":"identifier","text":"SKWMemberTypePerson"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.ntt.skyway.room/s8SendableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"url":"\/documentation\/skywayroom\/membertype\/init(rawvalue:)","role":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/init(rawValue:)","abstract":[]},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberType/Equatable-Implementations":{"url":"\/documentation\/skywayroom\/membertype\/equatable-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/Equatable-Implementations","title":"Equatable Implementations","kind":"article"},"doc://com.ntt.skyway.room/SY":{"identifier":"doc:\/\/com.ntt.skyway.room\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SKWMemberType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWMemberType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SKWMemberType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/bot","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberType\/person"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWMemberType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/title","value":"SKWMemberType"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/fragments","value":[{"text":"SKWMemberType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType\/navigatorTitle","value":[{"text":"SKWMemberType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType~1bot\/title","value":"SKWMemberTypeBot"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType~1bot\/fragments","value":[{"text":"SKWMemberTypeBot","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType~1person\/title","value":"SKWMemberTypePerson"},{"op":"replace","value":[{"kind":"identifier","text":"SKWMemberTypePerson"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberType~1person\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}