{
  "abstract": [
    {
      "text": "Memberイベントデリゲート",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:objc(pl)SKWMemberDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MemberDelegate"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MemberDelegate"
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "MemberDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MemberDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.7.0",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalP2PRoomMember": {
      "abstract": [
        {
          "text": "P2PRoomのLocalMember",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalP2PRoomMember"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalP2PRoomMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalP2PRoomMember"
        }
      ],
      "role": "symbol",
      "title": "LocalP2PRoomMember",
      "type": "topic",
      "url": "/documentation/skywayroom/localp2proommember"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPersonDelegate": {
      "abstract": [
        {
          "text": "LocalPersonイベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalPersonDelegate"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPersonDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalPersonDelegate"
        }
      ],
      "role": "symbol",
      "title": "LocalPersonDelegate",
      "type": "topic",
      "url": "/documentation/skywayroom/localpersondelegate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember": {
      "abstract": [
        {
          "text": "RoomのLocalMember",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalRoomMember"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalRoomMember"
        }
      ],
      "role": "symbol",
      "title": "LocalRoomMember",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommember"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalSFURoomMember": {
      "abstract": [
        {
          "text": "SFURoomのLocalMember",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalSFURoomMember"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalSFURoomMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalSFURoomMember"
        }
      ],
      "role": "symbol",
      "title": "LocalSFURoomMember",
      "type": "topic",
      "url": "/documentation/skywayroom/localsfuroommember"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate": {
      "abstract": [
        {
          "text": "Memberイベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MemberDelegate"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MemberDelegate"
        }
      ],
      "role": "symbol",
      "title": "MemberDelegate",
      "type": "topic",
      "url": "/documentation/skywayroom/memberdelegate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/member(_:didUpdateMetadata:)": {
      "abstract": [
        {
          "text": "Memberのメタデータが更新された時にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "member"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWMember",
          "text": "Member"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/member(_:didUpdateMetadata:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "member:didUpdateMetadata:"
        }
      ],
      "role": "symbol",
      "title": "member(_:didUpdateMetadata:)",
      "type": "topic",
      "url": "/documentation/skywayroom/memberdelegate/member(_:didupdatemetadata:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberDidLeave(_:)": {
      "abstract": [
        {
          "text": "MemberがChannelから退出した時にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memberDidLeave"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWMember",
          "text": "Member"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberDidLeave(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "memberDidLeave:"
        }
      ],
      "role": "symbol",
      "title": "memberDidLeave(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/memberdelegate/memberdidleave(_:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberPublicationListDidChange(_:)": {
      "abstract": [
        {
          "text": "MemberがPublishしているStreamの数が変化した時にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memberPublicationListDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWMember",
          "text": "Member"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberPublicationListDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "memberPublicationListDidChange:"
        }
      ],
      "role": "symbol",
      "title": "memberPublicationListDidChange(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/memberdelegate/memberpublicationlistdidchange(_:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberSubscriptionListDidChange(_:)": {
      "abstract": [
        {
          "text": "MemberがSubscribeしているStreamの数が変化した時にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memberSubscriptionListDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWMember",
          "text": "Member"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberSubscriptionListDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "memberSubscriptionListDidChange:"
        }
      ],
      "role": "symbol",
      "title": "memberSubscriptionListDidChange(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/memberdelegate/membersubscriptionlistdidchange(_:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemotePersonDelegate": {
      "abstract": [
        {
          "text": "RemotePersonイベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RemotePersonDelegate"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemotePersonDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RemotePersonDelegate"
        }
      ],
      "role": "symbol",
      "title": "RemotePersonDelegate",
      "type": "topic",
      "url": "/documentation/skywayroom/remotepersondelegate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember": {
      "abstract": [
        {
          "text": "他のSDKで生成されたRoomMember",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RemoteRoomMember"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RemoteRoomMember"
        }
      ],
      "role": "symbol",
      "title": "RemoteRoomMember",
      "type": "topic",
      "url": "/documentation/skywayroom/remoteroommember"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFUBotMemberDelegate": {
      "abstract": [
        {
          "text": "イベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFUBotMemberDelegate"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFUBotMemberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFUBotMemberDelegate"
        }
      ],
      "role": "symbol",
      "title": "SFUBotMemberDelegate",
      "type": "topic",
      "url": "/documentation/skywayroom/sfubotmemberdelegate"
    },
    "doc://com.ntt.skyway.room/objc(pl)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(pl)NSObject",
      "title": "NSObject",
      "type": "unresolvable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPersonDelegate",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemotePersonDelegate",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFUBotMemberDelegate"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalP2PRoomMember",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalSFURoomMember",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/member(_:didUpdateMetadata:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberDidLeave(_:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberPublicationListDidChange(_:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberSubscriptionListDidChange(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKWMemberDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/member(_:didUpdateMetadata:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberDidLeave(_:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberPublicationListDidChange(_:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/memberSubscriptionListDidChange(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.ntt.skyway.room/objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPersonDelegate",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemotePersonDelegate",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFUBotMemberDelegate"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKWMemberDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1memberPublicationListDidChange(_:)/title",
          "value": "memberPublicationListDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1memberPublicationListDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "memberPublicationListDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/title",
          "value": "LocalRoomMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1memberDidLeave(_:)/title",
          "value": "memberDidLeave:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1memberDidLeave(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "memberDidLeave:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotMemberDelegate/title",
          "value": "SKWSFUBotMemberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotMemberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWSFUBotMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotMemberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWSFUBotMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePersonDelegate/title",
          "value": "SKWRemotePersonDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePersonDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWRemotePersonDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePersonDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWRemotePersonDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPersonDelegate/title",
          "value": "SKWLocalPersonDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPersonDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWLocalPersonDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPersonDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWLocalPersonDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1memberSubscriptionListDidChange(_:)/title",
          "value": "memberSubscriptionListDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1memberSubscriptionListDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "memberSubscriptionListDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember/title",
          "value": "RemoteRoomMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RemoteRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RemoteRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalP2PRoomMember/title",
          "value": "LocalP2PRoomMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalP2PRoomMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalP2PRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalP2PRoomMember/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalP2PRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalSFURoomMember/title",
          "value": "LocalSFURoomMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalSFURoomMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalSFURoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalSFURoomMember/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalSFURoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1member(_:didUpdateMetadata:)/title",
          "value": "member:didUpdateMetadata:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1member(_:didUpdateMetadata:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "member:didUpdateMetadata:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate/title",
          "value": "SKWMemberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWMemberDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/memberdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/memberdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
