{"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH"],"kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/memberinit"]},{"paths":["\/documentation\/skywayroom\/memberinit"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Member初期化オプション","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/keepaliveIntervalGapSec","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/keepaliveIntervalSec","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/metadata","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/name"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MemberInit","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit"},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MemberInit","kind":"identifier"}],"externalID":"c:objc(cs)SKWMemberInit","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"MemberInit","kind":"identifier"}],"title":"MemberInit","symbolKind":"class"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberInit/metadata":{"url":"\/documentation\/skywayroom\/memberinit\/metadata","type":"topic","abstract":[{"type":"text","text":"Memberのメタデータ"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/metadata","title":"metadata","navigatorTitle":[{"text":"metadata","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberInit":{"url":"\/documentation\/skywayroom\/memberinit","type":"topic","abstract":[{"type":"text","text":"Member初期化オプション"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MemberInit","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit","title":"MemberInit","navigatorTitle":[{"text":"MemberInit","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberInit/keepaliveIntervalGapSec":{"url":"\/documentation\/skywayroom\/memberinit\/keepaliveintervalgapsec","type":"topic","abstract":[{"type":"text","text":"MemberのKeepAliveの更新間隔時間を超えてChannelからMemberが削除されるまでの時間"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keepaliveIntervalGapSec","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/keepaliveIntervalGapSec","title":"keepaliveIntervalGapSec","navigatorTitle":[{"kind":"identifier","text":"keepaliveIntervalGapSec"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberInit/name":{"url":"\/documentation\/skywayroom\/memberinit\/name","type":"topic","abstract":[{"type":"text","text":"Member名"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/name","title":"name","navigatorTitle":[{"kind":"identifier","text":"name"}],"kind":"symbol"},"doc://com.ntt.skyway.room/objc(cs)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ntt.skyway.room/s7CVarArgP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberInit/keepaliveIntervalSec":{"url":"\/documentation\/skywayroom\/memberinit\/keepaliveintervalsec","type":"topic","abstract":[{"type":"text","text":"MemberのKeepAliveの更新間隔時間"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keepaliveIntervalSec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/keepaliveIntervalSec","title":"keepaliveIntervalSec","navigatorTitle":[{"kind":"identifier","text":"keepaliveIntervalSec"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SKWMemberInit","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWMemberInit","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SKWMemberInit","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/keepaliveIntervalGapSec","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/keepaliveIntervalSec","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/metadata","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit\/name"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWMemberInit","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit~1metadata\/title","value":"metadata"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit~1metadata\/fragments","value":[{"text":"metadata","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit\/title","value":"SKWMemberInit"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit\/fragments","value":[{"text":"SKWMemberInit","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit\/navigatorTitle","value":[{"kind":"identifier","text":"SKWMemberInit"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit~1keepaliveIntervalGapSec\/title","value":"keepaliveIntervalGapSec","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit~1keepaliveIntervalGapSec\/fragments","value":[{"text":"keepaliveIntervalGapSec","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit~1name\/title","value":"name"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit~1name\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit~1keepaliveIntervalSec\/title","value":"keepaliveIntervalSec"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit~1keepaliveIntervalSec\/fragments","value":[{"text":"keepaliveIntervalSec","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}