{
  "abstract": [
    {
      "text": "Channelに入室しているMemberの抽象クラス",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:objc(cs)SKWMember",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Member"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Member"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "Member"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Member"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/SH": {
      "identifier": "doc://com.ntt.skyway.room/SH",
      "title": "Swift.Hashable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/SQ": {
      "identifier": "doc://com.ntt.skyway.room/SQ",
      "title": "Swift.Equatable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPerson": {
      "abstract": [
        {
          "text": "このSDKで生成されたLocalMember",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalPerson"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalPerson"
        }
      ],
      "role": "symbol",
      "title": "LocalPerson",
      "type": "topic",
      "url": "/documentation/skywayroom/localperson"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member": {
      "abstract": [
        {
          "text": "Channelに入室しているMemberの抽象クラス",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Member"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Member"
        }
      ],
      "role": "symbol",
      "title": "Member",
      "type": "topic",
      "url": "/documentation/skywayroom/member"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/id": {
      "abstract": [
        {
          "text": "Memberを識別するためのID",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/id",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "id"
        }
      ],
      "role": "symbol",
      "title": "id",
      "type": "topic",
      "url": "/documentation/skywayroom/member/id"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/leave(completion:)": {
      "abstract": [
        {
          "text": "Channelから退出します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leave"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/leave(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leaveWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "leave(completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/member/leave(completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/metadata": {
      "abstract": [
        {
          "text": "メタデータ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/skywayroom/member/metadata"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/name": {
      "abstract": [
        {
          "text": "Memberの名前",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/skywayroom/member/name"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/publications": {
      "abstract": [
        {
          "text": "Publish中のPublication一覧",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publications"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/publications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publications"
        }
      ],
      "role": "symbol",
      "title": "publications",
      "type": "topic",
      "url": "/documentation/skywayroom/member/publications"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/side": {
      "abstract": [
        {
          "text": "メンバーサイド",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "side"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKWSide",
          "text": "Side"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/side",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "side"
        }
      ],
      "role": "symbol",
      "title": "side",
      "type": "topic",
      "url": "/documentation/skywayroom/member/side"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/state": {
      "abstract": [
        {
          "text": "ステート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKWMemberState",
          "text": "MemberState"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/skywayroom/member/state"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/subscriptions": {
      "abstract": [
        {
          "text": "Subscribe中のSubscription一覧",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWSubscription",
          "text": "Subscription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/subscriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptions"
        }
      ],
      "role": "symbol",
      "title": "subscriptions",
      "type": "topic",
      "url": "/documentation/skywayroom/member/subscriptions"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/subtype": {
      "abstract": [
        {
          "text": "サブタイプ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/subtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtype"
        }
      ],
      "role": "symbol",
      "title": "subtype",
      "type": "topic",
      "url": "/documentation/skywayroom/member/subtype"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/type": {
      "abstract": [
        {
          "text": "メンバータイプ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKWMemberType",
          "text": "MemberType"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/skywayroom/member/type"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/updateMetadata(_:completion:)": {
      "abstract": [
        {
          "text": "メタデータを更新します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateMetadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/updateMetadata(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateMetadata:completion:"
        }
      ],
      "role": "symbol",
      "title": "updateMetadata(_:completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/member/updatemetadata(_:completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteMember": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RemoteMember"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RemoteMember"
        }
      ],
      "role": "symbol",
      "title": "RemoteMember",
      "type": "topic",
      "url": "/documentation/skywayroom/remotemember"
    },
    "doc://com.ntt.skyway.room/objc(cs)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(cs)NSObject",
      "title": "NSObject",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/objc(pl)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(pl)NSObject",
      "title": "ObjectiveC.NSObjectProtocol",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s23CustomStringConvertibleP": {
      "identifier": "doc://com.ntt.skyway.room/s23CustomStringConvertibleP",
      "title": "Swift.CustomStringConvertible",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP": {
      "identifier": "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP",
      "title": "Swift.CustomDebugStringConvertible",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s7CVarArgP": {
      "identifier": "doc://com.ntt.skyway.room/s7CVarArgP",
      "title": "Swift.CVarArg",
      "type": "unresolvable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPerson",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteMember"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(pl)NSObject",
        "doc://com.ntt.skyway.room/s7CVarArgP",
        "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP",
        "doc://com.ntt.skyway.room/s23CustomStringConvertibleP",
        "doc://com.ntt.skyway.room/SQ",
        "doc://com.ntt.skyway.room/SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/id",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/metadata",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/name",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/publications",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/side",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/state",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/subscriptions",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/subtype",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/type"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/leave(completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/updateMetadata(_:completion:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKWMember"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/id",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/metadata",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/name",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/publications",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/side",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/state",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/subscriptions",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/subtype",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/type"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/leave(completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member/updateMetadata(_:completion:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.ntt.skyway.room/objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPerson",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteMember"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKWMember"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteMember/title",
          "value": "SKWRemoteMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWRemoteMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteMember/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWRemoteMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1publications/title",
          "value": "publications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1publications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "publications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1subtype/title",
          "value": "subtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1subtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member/title",
          "value": "SKWMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1side/title",
          "value": "side"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1side/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "side"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1subscriptions/title",
          "value": "subscriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1subscriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1leave(completion:)/title",
          "value": "leaveWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1leave(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "leaveWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson/title",
          "value": "SKWLocalPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWLocalPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWLocalPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1id/title",
          "value": "id"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1id/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "id"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1updateMetadata(_:completion:)/title",
          "value": "updateMetadata:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member~1updateMetadata(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateMetadata:completion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/member"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/member"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
