{
  "abstract": [
    {
      "text": "Publicationの状態",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:@E@SKWPublicationState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "PublicationState"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PublicationState"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "PublicationState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PublicationState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/SH": {
      "identifier": "doc://com.ntt.skyway.room/SH",
      "title": "Swift.Hashable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/SQ": {
      "identifier": "doc://com.ntt.skyway.room/SQ",
      "title": "Swift.Equatable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/SY": {
      "identifier": "doc://com.ntt.skyway.room/SY",
      "title": "Swift.RawRepresentable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState": {
      "abstract": [
        {
          "text": "Publicationの状態",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PublicationState"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PublicationState"
        }
      ],
      "role": "symbol",
      "title": "PublicationState",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationstate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationstate/equatable-implementations"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationstate/rawrepresentable-implementations"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/canceled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceled"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/canceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKWPublicationStateCanceled"
        }
      ],
      "role": "symbol",
      "title": "PublicationState.canceled",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationstate/canceled"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/disabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKWPublicationStateDisabled"
        }
      ],
      "role": "symbol",
      "title": "PublicationState.disabled",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationstate/disabled"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/enabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/enabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKWPublicationStateEnabled"
        }
      ],
      "role": "symbol",
      "title": "PublicationState.enabled",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationstate/enabled"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/skywayroom/publicationstate/init(rawvalue:)"
    },
    "doc://com.ntt.skyway.room/s15BitwiseCopyableP": {
      "identifier": "doc://com.ntt.skyway.room/s15BitwiseCopyableP",
      "title": "Swift.BitwiseCopyable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s16SendableMetatypeP": {
      "identifier": "doc://com.ntt.skyway.room/s16SendableMetatypeP",
      "title": "Swift.SendableMetatype",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s8SendableP": {
      "identifier": "doc://com.ntt.skyway.room/s8SendableP",
      "title": "Swift.Sendable",
      "type": "unresolvable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/s15BitwiseCopyableP",
        "doc://com.ntt.skyway.room/SQ",
        "doc://com.ntt.skyway.room/SH",
        "doc://com.ntt.skyway.room/SY",
        "doc://com.ntt.skyway.room/s8SendableP",
        "doc://com.ntt.skyway.room/s16SendableMetatypeP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/canceled",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/disabled",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/enabled"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/Equatable-Implementations",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKWPublicationState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/canceled",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/disabled",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/PublicationState/enabled"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKWPublicationState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState~1canceled/title",
          "value": "SKWPublicationStateCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState~1canceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationStateCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState/title",
          "value": "SKWPublicationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState~1disabled/title",
          "value": "SKWPublicationStateDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationStateDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState~1enabled/title",
          "value": "SKWPublicationStateEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1PublicationState~1enabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublicationStateEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/publicationstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/publicationstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
