{
  "abstract": [
    {
      "text": "Publication",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:objc(cs)SKWPublication",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Publication"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Publication"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "Publication"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Publication"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "PublicationはLocalMemberがPublishした時に取得でき、Roomに参加している他クライアント(RemoteMember)がSubscribeされると通信を行います。",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Roomなどから他の人のPublicationも取得することはできますが、その場合Streamは含まれません。",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/SH": {
      "identifier": "doc://com.ntt.skyway.room/SH",
      "title": "Swift.Hashable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/SQ": {
      "identifier": "doc://com.ntt.skyway.room/SQ",
      "title": "Swift.Equatable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.7.0",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication": {
      "abstract": [
        {
          "text": "Publication",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Publication"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Publication"
        }
      ],
      "role": "symbol",
      "title": "Publication",
      "type": "topic",
      "url": "/documentation/skywayroom/publication"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/codecCapabilities": {
      "abstract": [
        {
          "text": "コーデック指定",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "codecCapabilities"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWCodec",
          "text": "Codec"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/codecCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "codecCapabilities"
        }
      ],
      "role": "symbol",
      "title": "codecCapabilities",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/codeccapabilities"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/contentType": {
      "abstract": [
        {
          "text": "PublishしているStreamのコンテントタイプ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKWContentType",
          "text": "ContentType"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/contentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentType"
        }
      ],
      "role": "symbol",
      "title": "contentType",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/contenttype"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/delegate": {
      "abstract": [
        {
          "text": "イベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SKWPublicationDelegate",
          "text": "PublicationDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/delegate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/disable(completion:)": {
      "abstract": [
        {
          "text": "Publicationを無効状態にします。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/disable(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "disableWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "disable(completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/disable(completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/enable(completion:)": {
      "abstract": [
        {
          "text": "Publicationを有効状態にします。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/enable(completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enableWithCompletion:"
        }
      ],
      "role": "symbol",
      "title": "enable(completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/enable(completion:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/encodings": {
      "abstract": [
        {
          "text": "エンコーディング設定",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWEncoding",
          "text": "Encoding"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/encodings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encodings"
        }
      ],
      "role": "symbol",
      "title": "encodings",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/encodings"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/getStats(withMemberId:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getStats"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMemberId"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWWebRTCStats",
          "text": "WebRTCStats"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/getStats(withMemberId:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getStatsWithMemberId:"
        }
      ],
      "role": "symbol",
      "title": "getStats(withMemberId:)",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/getstats(withmemberid:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/id": {
      "abstract": [
        {
          "text": "Publicationを識別するためのID",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "id"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/id",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "id"
        }
      ],
      "role": "symbol",
      "title": "id",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/id"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/metadata": {
      "abstract": [
        {
          "text": "メタデータ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/metadata"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/origin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "origin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/origin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "origin"
        }
      ],
      "role": "symbol",
      "title": "origin",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/origin"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/publisher": {
      "abstract": [
        {
          "text": "このPublicationを生成したMember",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publisher"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWMember",
          "text": "Member"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/publisher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publisher"
        }
      ],
      "role": "symbol",
      "title": "publisher",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/publisher"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/replaceStream(_:)": {
      "abstract": [
        {
          "text": "送信するストリームを切り替えます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceStream"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWLocalStream",
          "text": "LocalStream"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/replaceStream(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceStream:"
        }
      ],
      "role": "symbol",
      "title": "replaceStream(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/replacestream(_:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/state": {
      "abstract": [
        {
          "text": "ステート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKWPublicationState",
          "text": "PublicationState"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/state",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/state"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/stream": {
      "abstract": [
        {
          "text": "このPublicationに紐づくStream",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWLocalStream",
          "text": "LocalStream"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/stream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stream"
        }
      ],
      "role": "symbol",
      "title": "stream",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/stream"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/subscriptions": {
      "abstract": [
        {
          "text": "このPublicationに紐づくSubscription一覧",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWSubscription",
          "text": "Subscription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/subscriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptions"
        }
      ],
      "role": "symbol",
      "title": "subscriptions",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/subscriptions"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/type": {
      "abstract": [
        {
          "text": "このPublicationの通信タイプ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SKWPublicationType",
          "text": "PublicationType"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/type"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/updateEncodings(_:)": {
      "abstract": [
        {
          "text": "エンコーディング設定を更新します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateEncodings"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWEncoding",
          "text": "Encoding"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/updateEncodings(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateEncodings:"
        }
      ],
      "role": "symbol",
      "title": "updateEncodings(_:)",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/updateencodings(_:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/updateMetadata(_:completion:)": {
      "abstract": [
        {
          "text": "メタデータを更新します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateMetadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/updateMetadata(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateMetadata:completion:"
        }
      ],
      "role": "symbol",
      "title": "updateMetadata(_:completion:)",
      "type": "topic",
      "url": "/documentation/skywayroom/publication/updatemetadata(_:completion:)"
    },
    "doc://com.ntt.skyway.room/objc(cs)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(cs)NSObject",
      "title": "NSObject",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/objc(pl)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(pl)NSObject",
      "title": "ObjectiveC.NSObjectProtocol",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s23CustomStringConvertibleP": {
      "identifier": "doc://com.ntt.skyway.room/s23CustomStringConvertibleP",
      "title": "Swift.CustomStringConvertible",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP": {
      "identifier": "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP",
      "title": "Swift.CustomDebugStringConvertible",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s7CVarArgP": {
      "identifier": "doc://com.ntt.skyway.room/s7CVarArgP",
      "title": "Swift.CVarArg",
      "type": "unresolvable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(pl)NSObject",
        "doc://com.ntt.skyway.room/s7CVarArgP",
        "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP",
        "doc://com.ntt.skyway.room/s23CustomStringConvertibleP",
        "doc://com.ntt.skyway.room/SQ",
        "doc://com.ntt.skyway.room/SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/codecCapabilities",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/contentType",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/delegate",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/encodings",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/id",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/metadata",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/origin",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/publisher",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/state",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/stream",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/subscriptions",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/type"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/disable(completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/enable(completion:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/getStats(withMemberId:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/replaceStream(_:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/updateEncodings(_:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/updateMetadata(_:completion:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKWPublication"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/codecCapabilities",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/contentType",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/delegate",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/encodings",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/id",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/metadata",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/origin",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/publisher",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/state",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/stream",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/subscriptions",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/type"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/disable(completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/enable(completion:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/getStats(withMemberId:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/replaceStream(_:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/updateEncodings(_:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/updateMetadata(_:completion:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.ntt.skyway.room/objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKWPublication"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1enable(completion:)/title",
          "value": "enableWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1enable(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enableWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1state/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1state/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1contentType/title",
          "value": "contentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1contentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1publisher/title",
          "value": "publisher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1publisher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "publisher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1updateEncodings(_:)/title",
          "value": "updateEncodings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1updateEncodings(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateEncodings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1id/title",
          "value": "id"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1id/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "id"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1codecCapabilities/title",
          "value": "codecCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1codecCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "codecCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1disable(completion:)/title",
          "value": "disableWithCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1disable(completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "disableWithCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1updateMetadata(_:completion:)/title",
          "value": "updateMetadata:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1updateMetadata(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateMetadata:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1origin/title",
          "value": "origin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1origin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "origin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication/title",
          "value": "SKWPublication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWPublication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1getStats(withMemberId:)/title",
          "value": "getStatsWithMemberId:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1getStats(withMemberId:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getStatsWithMemberId:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1replaceStream(_:)/title",
          "value": "replaceStream:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1replaceStream(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replaceStream:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1encodings/title",
          "value": "encodings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1encodings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encodings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1stream/title",
          "value": "stream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1stream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "stream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1subscriptions/title",
          "value": "subscriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1subscriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subscriptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/publication"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/publication"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
