{"kind":"symbol","topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate\/dataStream(_:didReceive:)-6un1e","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate\/dataStream(_:didReceive:)-7f2zw"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/remotedatastreamdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/remotedatastreamdelegate"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteDataStreamDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:objc(pl)SKWRemoteDataStreamDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteDataStreamDelegate","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"RemoteDataStreamDelegate","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"RemoteDataStreamDelegate"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"RemoteDataStreamイベントデリゲート"}],"references":{"doc://com.ntt.skyway.room/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","title":"NSObject"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteDataStreamDelegate/dataStream(_:didReceive:)-7f2zw":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWRemoteDataStream","text":"RemoteDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/remotedatastreamdelegate\/datastream(_:didreceive:)-7f2zw","role":"symbol","navigatorTitle":[{"text":"dataStream:didReceiveString:","kind":"identifier"}],"type":"topic","title":"dataStream(_:didReceive:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate\/dataStream(_:didReceive:)-7f2zw","abstract":[{"text":"文字列情報を受信した時にコールされるイベント","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteDataStreamDelegate/dataStream(_:didReceive:)-6un1e":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RemoteDataStream","preciseIdentifier":"c:objc(cs)SKWRemoteDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/remotedatastreamdelegate\/datastream(_:didreceive:)-6un1e","role":"symbol","navigatorTitle":[{"text":"dataStream:didReceiveData:","kind":"identifier"}],"type":"topic","title":"dataStream(_:didReceive:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate\/dataStream(_:didReceive:)-6un1e","abstract":[{"type":"text","text":"バイナリを受信した時にコールされるイベント"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteDataStreamDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteDataStreamDelegate","kind":"identifier"}],"url":"\/documentation\/skywayroom\/remotedatastreamdelegate","role":"symbol","navigatorTitle":[{"text":"RemoteDataStreamDelegate","kind":"identifier"}],"type":"topic","title":"RemoteDataStreamDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate","abstract":[{"type":"text","text":"RemoteDataStreamイベントデリゲート"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SKWRemoteDataStreamDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWRemoteDataStreamDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SKWRemoteDataStreamDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate\/dataStream(_:didReceive:)-6un1e","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate\/dataStream(_:didReceive:)-7f2zw"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWRemoteDataStreamDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate~1dataStream(_:didReceive:)-7f2zw\/title","op":"replace","value":"dataStream:didReceiveString:"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate~1dataStream(_:didReceive:)-7f2zw\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"dataStream:didReceiveString:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate~1dataStream(_:didReceive:)-6un1e\/title","value":"dataStream:didReceiveData:"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate~1dataStream(_:didReceive:)-6un1e\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataStream:didReceiveData:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate\/title","value":"SKWRemoteDataStreamDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate\/fragments","value":[{"text":"SKWRemoteDataStreamDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate\/navigatorTitle","value":[{"text":"SKWRemoteDataStreamDelegate","kind":"identifier"}]}]}]}