{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteRoomMemberDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"RoomMemberDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate","preciseIdentifier":"c:@M@SkyWayRoom@objc(pl)RoomMemberDelegate"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/skywayroom\/remoteroommemberdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/remoteroommemberdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteRoomMemberDelegate","kind":"identifier"}],"externalID":"c:@M@SkyWayRoom@objc(pl)RemoteRoomMemberDelegate","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"RemoteRoomMemberDelegate","kind":"identifier"}],"title":"RemoteRoomMemberDelegate","symbolKind":"protocol"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"RemoteRoomMemberイベントデリゲート"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate\/remoteRoomMember(_:didSubscribePublicationOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate\/remoteRoomMember(_:didUnsubscribePublicationOf:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate"},"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMemberDelegate/remoteRoomMember(_:didSubscribePublicationOf:)":{"url":"\/documentation\/skywayroom\/remoteroommemberdelegate\/remoteroommember(_:didsubscribepublicationof:)","type":"topic","abstract":[{"type":"text","text":"RemoteRoomMemberがPublicationをSubscribeした時にコールされます。"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remoteRoomMember","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RemoteRoomMember","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RemoteRoomMember"},{"text":", ","kind":"text"},{"text":"didSubscribePublicationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate\/remoteRoomMember(_:didSubscribePublicationOf:)","title":"remoteRoomMember(_:didSubscribePublicationOf:)","navigatorTitle":[{"text":"remoteRoomMember:didSubscribePublicationOf:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMemberDelegate/remoteRoomMember(_:didUnsubscribePublicationOf:)":{"url":"\/documentation\/skywayroom\/remoteroommemberdelegate\/remoteroommember(_:didunsubscribepublicationof:)","navigatorTitle":[{"text":"remoteRoomMember:didUnsubscribePublicationOf:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"remoteRoomMember(_:didUnsubscribePublicationOf:)","abstract":[{"type":"text","text":"RemoteRoomMemberがPublicationをUnsubscribeした時にコールされます。"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate\/remoteRoomMember(_:didUnsubscribePublicationOf:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteRoomMember"},{"kind":"text","text":"("},{"text":"RemoteRoomMember","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RemoteRoomMember","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUnsubscribePublicationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomMemberDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoomMemberDelegate","kind":"identifier"}],"url":"\/documentation\/skywayroom\/roommemberdelegate","role":"symbol","navigatorTitle":[{"text":"RoomMemberDelegate","kind":"identifier"}],"type":"topic","title":"RoomMemberDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate","abstract":[{"text":"RoomMemberイベントデリゲート","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMemberDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"RemoteRoomMemberイベントデリゲート"}],"title":"RemoteRoomMemberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteRoomMemberDelegate"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate","navigatorTitle":[{"kind":"identifier","text":"RemoteRoomMemberDelegate"}],"role":"symbol","url":"\/documentation\/skywayroom\/remoteroommemberdelegate","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"RemoteRoomMemberDelegate"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"RemoteRoomMemberDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"RemoteRoomMemberDelegate","kind":"identifier"}]},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate\/remoteRoomMember(_:didSubscribePublicationOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate\/remoteRoomMember(_:didUnsubscribePublicationOf:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteRoomMemberDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomMemberDelegate","text":"RoomMemberDelegate","preciseIdentifier":"c:@M@SkyWayRoom@objc(pl)RoomMemberDelegate","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"remoteRoomMember:didSubscribePublicationOf:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate~1remoteRoomMember(_:didSubscribePublicationOf:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"remoteRoomMember:didSubscribePublicationOf:"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate~1remoteRoomMember(_:didSubscribePublicationOf:)\/fragments","op":"replace"},{"op":"replace","value":"remoteRoomMember:didUnsubscribePublicationOf:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate~1remoteRoomMember(_:didUnsubscribePublicationOf:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"remoteRoomMember:didUnsubscribePublicationOf:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate~1remoteRoomMember(_:didUnsubscribePublicationOf:)\/fragments"},{"op":"replace","value":"RoomMemberDelegate","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"RoomMemberDelegate"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomMemberDelegate\/navigatorTitle","op":"replace","value":[{"text":"RoomMemberDelegate","kind":"identifier"}]},{"op":"replace","value":"RemoteRoomMemberDelegate","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/fragments","op":"replace","value":[{"text":"RemoteRoomMemberDelegate","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"RemoteRoomMemberDelegate"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}