{
  "abstract": [
    {
      "text": "ルームの状態",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:@M@SkyWayRoom@E@RoomState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RoomState"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RoomState"
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "RoomState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@objc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RoomState"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/SH": {
      "identifier": "doc://com.ntt.skyway.room/SH",
      "title": "Swift.Hashable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/SQ": {
      "identifier": "doc://com.ntt.skyway.room/SQ",
      "title": "Swift.Equatable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/SY": {
      "identifier": "doc://com.ntt.skyway.room/SY",
      "title": "Swift.RawRepresentable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr": {
      "abstract": [
        {
          "text": "ルームの状態",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomState"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomState"
        }
      ],
      "role": "symbol",
      "title": "RoomState",
      "type": "topic",
      "url": "/documentation/skywayroom/roomstate-26agr"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/Equatable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/Equatable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Equatable Implementations",
      "type": "topic",
      "url": "/documentation/skywayroom/roomstate-26agr/equatable-implementations"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/RawRepresentable-Implementations": {
      "abstract": [],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/RawRepresentable-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "RawRepresentable Implementations",
      "type": "topic",
      "url": "/documentation/skywayroom/roomstate-26agr/rawrepresentable-implementations"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/closed": {
      "abstract": [
        {
          "text": "クローズ状態",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closed"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/closed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomStateClosed"
        }
      ],
      "role": "symbol",
      "title": "RoomState.closed",
      "type": "topic",
      "url": "/documentation/skywayroom/roomstate-26agr/closed"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/skywayroom/roomstate-26agr/init(rawvalue:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/opened": {
      "abstract": [
        {
          "text": "オープン状態",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opened"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/opened",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomStateOpened"
        }
      ],
      "role": "symbol",
      "title": "RoomState.opened",
      "type": "topic",
      "url": "/documentation/skywayroom/roomstate-26agr/opened"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/SQ",
        "doc://com.ntt.skyway.room/SH",
        "doc://com.ntt.skyway.room/SY"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/closed",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/opened"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/Equatable-Implementations",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/RawRepresentable-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "RoomState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/closed",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-26agr/opened"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "RoomState"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-26agr/title",
          "value": "RoomState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-26agr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-26agr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-26agr~1closed/title",
          "value": "RoomStateClosed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-26agr~1closed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomStateClosed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-26agr~1opened/title",
          "value": "RoomStateOpened"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-26agr~1opened/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomStateOpened"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/roomstate-26agr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/roomstate-26agr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
