{"relationshipsSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/SY","doc:\/\/com.ntt.skyway.room\/s8SendableP","doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/skywayroom\/roomstate-377on"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/roomstate-377on"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"ルームステート","type":"text"}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/closed","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/opened"]},{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/Equatable-Implementations","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoomState","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomState"}],"externalID":"c:@E@SKWRoomState","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"RoomState","kind":"identifier"}],"title":"RoomState","symbolKind":"enum"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-377on":{"url":"\/documentation\/skywayroom\/roomstate-377on","navigatorTitle":[{"text":"RoomState","kind":"identifier"}],"type":"topic","kind":"symbol","title":"RoomState","abstract":[{"type":"text","text":"ルームステート"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoomState","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-377on/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/skywayroom\/roomstate-377on\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/RawRepresentable-Implementations","abstract":[]},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.ntt.skyway.room/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-377on/opened":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"opened","kind":"identifier"}],"url":"\/documentation\/skywayroom\/roomstate-377on\/opened","role":"symbol","navigatorTitle":[{"text":"SKWRoomStateOpened","kind":"identifier"}],"type":"topic","title":"RoomState.opened","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/opened","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-377on/closed":{"url":"\/documentation\/skywayroom\/roomstate-377on\/closed","navigatorTitle":[{"text":"SKWRoomStateClosed","kind":"identifier"}],"type":"topic","kind":"symbol","title":"RoomState.closed","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/closed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closed","kind":"identifier"}]},"doc://com.ntt.skyway.room/s16SendableMetatypeP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.ntt.skyway.room/SY":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SY","title":"Swift.RawRepresentable"},"doc://com.ntt.skyway.room/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s8SendableP","title":"Swift.Sendable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-377on/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"url":"\/documentation\/skywayroom\/roomstate-377on\/init(rawvalue:)","role":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/init(rawValue:)","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomState-377on/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/Equatable-Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/skywayroom\/roomstate-377on\/equatable-implementations"},"doc://com.ntt.skyway.room/SH":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","value":"SKWRoomState","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SKWRoomState","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SKWRoomState"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/closed","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomState-377on\/opened"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWRoomState","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-377on\/title","op":"replace","value":"SKWRoomState"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-377on\/fragments","op":"replace","value":[{"text":"SKWRoomState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-377on\/navigatorTitle","op":"replace","value":[{"text":"SKWRoomState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-377on~1opened\/title","op":"replace","value":"SKWRoomStateOpened"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-377on~1opened\/fragments","op":"replace","value":[{"text":"SKWRoomStateOpened","kind":"identifier"}]},{"op":"replace","value":"SKWRoomStateClosed","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-377on~1closed\/title"},{"op":"replace","value":[{"text":"SKWRoomStateClosed","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomState-377on~1closed\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}