{"kind":"symbol","abstract":[{"text":"SFUサーバを介して通信を行うRoom","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ChannelDelegate","doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/s12IdentifiableP"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFURoom","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/skywayroom\/sfuroom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/sfuroom"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","title":"SFURoom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFURoom"}],"navigatorTitle":[{"kind":"identifier","text":"SFURoom"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@SkyWayRoom@objc(cs)SFURoom","modules":[{"name":"SkyWayRoom"}]},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/publications","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/type"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:didPublishStreamOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:didUnpublishStreamOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publication:metadataDidUpdate:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publicationDidChangeToDisabled:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publicationDidChangeToEnabled:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/join(with:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/join(with:completion:)"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:sfuOptions:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:sfuOptions:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:sfuOption:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:sfuOptions:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:sfuOptions:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:sfuOptions:completion:)"]}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/find(by:sfuOption:)":{"url":"\/documentation\/skywayroom\/sfuroom\/find(by:sfuoption:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"find","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"text":"Query","kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C5QueryC"},{"text":", ","kind":"text"},{"text":"sfuOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SFUBotPluginOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions"},{"kind":"text","text":"?) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"SFURoom","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:sfuOption:)","title":"find(by:sfuOption:)","navigatorTitle":[{"kind":"identifier","text":"findBy:sfuOption:completionHandler:"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s7CVarArgP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/findOrCreate(with:sfuOptions:completion:)":{"kind":"symbol","title":"findOrCreate(with:sfuOptions:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findOrCreate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sfuOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","text":"SFUBotPluginOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:sfuOptions:completion:)","navigatorTitle":[{"kind":"identifier","text":"findOrCreateWith:sfuOptions:completion:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/findorcreate(with:sfuoptions:completion:)","deprecated":true},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ChannelDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelDelegate"}],"url":"\/documentation\/skywayroom\/channeldelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChannelDelegate"}],"type":"topic","title":"ChannelDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ChannelDelegate","abstract":[{"type":"text","text":"Channelイベントデリゲート"}]},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/publications":{"kind":"symbol","title":"publications","abstract":[{"type":"text","text":"このRoomでPublishされているStreamのPublication一覧"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"publications"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication","text":"RoomPublication"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/publications","navigatorTitle":[{"kind":"identifier","text":"publications"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/publications"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/create(with:completion:)":{"kind":"symbol","title":"create(with:completion:)","abstract":[{"type":"text","text":"Roomを作成します。"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:completion:)","navigatorTitle":[{"kind":"identifier","text":"createWith:completion:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/create(with:completion:)"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/channel(_:publicationDidChangeToEnabled:)":{"kind":"symbol","title":"channel(_:publicationDidChangeToEnabled:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publicationDidChangeToEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publicationDidChangeToEnabled:)","navigatorTitle":[{"kind":"identifier","text":"channel:publicationDidChangeToEnabled:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/channel(_:publicationdidchangetoenabled:)"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/findOrCreate(with:completion:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findOrCreate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InitOptions","kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"SFURoom","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/skywayroom\/sfuroom\/findorcreate(with:completion:)","role":"symbol","navigatorTitle":[{"text":"findOrCreateWith:completion:","kind":"identifier"}],"type":"topic","title":"findOrCreate(with:completion:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:completion:)","abstract":[{"text":"Roomを名前から検索し、存在しない場合は作成します。","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/create(with:sfuOptions:)":{"kind":"symbol","title":"create(with:sfuOptions:)","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"sfuOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","text":"SFUBotPluginOptions"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:sfuOptions:)","navigatorTitle":[{"kind":"identifier","text":"createWith:sfuOptions:completionHandler:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/create(with:sfuoptions:)","deprecated":true},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/create(with:)":{"kind":"symbol","title":"create(with:)","abstract":[{"type":"text","text":"Roomを作成します。"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:)","navigatorTitle":[{"kind":"identifier","text":"createWith:completionHandler:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/create(with:)"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/type":{"kind":"symbol","title":"type","abstract":[{"type":"text","text":"Roomのタイプ"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWRoomType","text":"RoomType"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/type","navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/type"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/join(with:completion:)":{"url":"\/documentation\/skywayroom\/sfuroom\/join(with:completion:)","navigatorTitle":[{"text":"joinWith:completion:","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"RoomにLocalRoomMemberを作成し、入室させます。"}],"title":"join(with:completion:)","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/join(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room","text":"Room"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C17MemberInitOptionsC","text":"MemberInitOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)LocalSFURoomMember","text":"LocalSFURoomMember"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/find(by:sfuOptions:completion:)":{"url":"\/documentation\/skywayroom\/sfuroom\/find(by:sfuoptions:completion:)","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"find","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Query","kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C5QueryC"},{"text":", ","kind":"text"},{"text":"sfuOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SFUBotPluginOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"SFURoom","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:sfuOptions:completion:)","title":"find(by:sfuOptions:completion:)","navigatorTitle":[{"text":"findBy:sfuOptions:completion:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/channel(_:publicationDidChangeToDisabled:)":{"url":"\/documentation\/skywayroom\/sfuroom\/channel(_:publicationdidchangetodisabled:)","navigatorTitle":[{"kind":"identifier","text":"channel:publicationDidChangeToDisabled:"}],"type":"topic","kind":"symbol","title":"channel(_:publicationDidChangeToDisabled:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publicationDidChangeToDisabled:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Channel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel"},{"text":", ","kind":"text"},{"text":"publicationDidChangeToDisabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Publication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/s12IdentifiableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s12IdentifiableP","type":"unresolvable","title":"Swift.Identifiable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/find(by:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"find"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10SkyWayRoom0C0C5QueryC","text":"Query","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"SFURoom","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"}],"url":"\/documentation\/skywayroom\/sfuroom\/find(by:)","role":"symbol","navigatorTitle":[{"text":"findBy:completionHandler:","kind":"identifier"}],"type":"topic","title":"find(by:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:)","abstract":[{"text":"Roomクエリを元にRoomを検索します。","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/channel(_:didPublishStreamOf:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPublishStreamOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication"},{"kind":"text","text":")"}],"url":"\/documentation\/skywayroom\/sfuroom\/channel(_:didpublishstreamof:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"channel:didPublishStreamOfPublication:"}],"type":"topic","title":"channel(_:didPublishStreamOf:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:didPublishStreamOf:)","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/join(with:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"join","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room","text":"Room","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"MemberInitOptions","kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C17MemberInitOptionsC"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"LocalSFURoomMember","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)LocalSFURoomMember"}],"url":"\/documentation\/skywayroom\/sfuroom\/join(with:)","role":"symbol","navigatorTitle":[{"text":"joinWith:completionHandler:","kind":"identifier"}],"type":"topic","title":"join(with:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/join(with:)","abstract":[{"type":"text","text":"RoomにLocalRoomMemberを作成し、入室させます。"}]},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/create(with:sfuOptions:completion:)":{"url":"\/documentation\/skywayroom\/sfuroom\/create(with:sfuoptions:completion:)","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"sfuOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","text":"SFUBotPluginOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:sfuOptions:completion:)","title":"create(with:sfuOptions:completion:)","navigatorTitle":[{"text":"createWith:sfuOptions:completion:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/find(by:completion:)":{"kind":"symbol","title":"find(by:completion:)","abstract":[{"type":"text","text":"Roomクエリを元にRoomを検索します。"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"find"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C5QueryC","text":"Query"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:completion:)","navigatorTitle":[{"kind":"identifier","text":"findBy:completion:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/find(by:completion:)"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Room"}],"url":"\/documentation\/skywayroom\/room","role":"symbol","navigatorTitle":[{"text":"Room","kind":"identifier"}],"type":"topic","title":"Room","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room","abstract":[{"text":"Roomクラス","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/channel(_:publication:metadataDidUpdate:)":{"url":"\/documentation\/skywayroom\/sfuroom\/channel(_:publication:metadatadidupdate:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publication"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadataDidUpdate"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publication:metadataDidUpdate:)","title":"channel(_:publication:metadataDidUpdate:)","navigatorTitle":[{"text":"channel:publication:metadataDidUpdate:","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/channel(_:didUnpublishStreamOf:)":{"url":"\/documentation\/skywayroom\/sfuroom\/channel(_:didunpublishstreamof:)","navigatorTitle":[{"kind":"identifier","text":"channel:didUnpublishStreamOfPublication:"}],"type":"topic","kind":"symbol","abstract":[],"title":"channel(_:didUnpublishStreamOf:)","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:didUnpublishStreamOf:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWChannel","text":"Channel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUnpublishStreamOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWPublication","text":"Publication"},{"kind":"text","text":")"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/findOrCreate(with:sfuOptions:)":{"kind":"symbol","title":"findOrCreate(with:sfuOptions:)","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findOrCreate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sfuOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","text":"SFUBotPluginOptions"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:sfuOptions:)","navigatorTitle":[{"kind":"identifier","text":"findOrCreateWith:sfuOptions:completionHandler:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/findorcreate(with:sfuoptions:)","deprecated":true},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/findOrCreate(with:)":{"url":"\/documentation\/skywayroom\/sfuroom\/findorcreate(with:)","navigatorTitle":[{"kind":"identifier","text":"findOrCreateWith:completionHandler:"}],"type":"topic","kind":"symbol","title":"findOrCreate(with:)","abstract":[{"text":"Roomを名前から検索し、存在しない場合は作成します。","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findOrCreate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InitOptions","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SFURoom","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom":{"url":"\/documentation\/skywayroom\/sfuroom","type":"topic","abstract":[{"text":"SFUサーバを介して通信を行うRoom","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFURoom","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","title":"SFURoom","navigatorTitle":[{"text":"SFURoom","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SFURoom","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SFURoom"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SFURoom"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/publications","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/type"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:didPublishStreamOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:didUnpublishStreamOf:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publication:metadataDidUpdate:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publicationDidChangeToDisabled:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/channel(_:publicationDidChangeToEnabled:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/join(with:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/join(with:completion:)"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:sfuOptions:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:sfuOptions:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:sfuOption:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:sfuOptions:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:completion:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:sfuOptions:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:sfuOptions:completion:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFURoom","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Room","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:sfuOption:)\/title","value":"findBy:sfuOption:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:sfuOption:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"findBy:sfuOption:completionHandler:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:sfuOptions:completion:)\/title","value":"findOrCreateWith:sfuOptions:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:sfuOptions:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"findOrCreateWith:sfuOptions:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ChannelDelegate\/title","value":"SKWChannelDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ChannelDelegate\/fragments","value":[{"kind":"identifier","text":"SKWChannelDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ChannelDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"SKWChannelDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1publications\/title","value":"publications","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1publications\/fragments","value":[{"text":"publications","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:completion:)\/title","value":"createWith:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWith:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:publicationDidChangeToEnabled:)\/title","value":"channel:publicationDidChangeToEnabled:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:publicationDidChangeToEnabled:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"channel:publicationDidChangeToEnabled:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:completion:)\/title","value":"findOrCreateWith:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"findOrCreateWith:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:sfuOptions:)\/title","value":"createWith:sfuOptions:completionHandler:"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:sfuOptions:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWith:sfuOptions:completionHandler:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:)\/title","value":"createWith:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWith:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1join(with:completion:)\/title","value":"joinWith:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1join(with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinWith:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:sfuOptions:completion:)\/title","value":"findBy:sfuOptions:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:sfuOptions:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"findBy:sfuOptions:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:publicationDidChangeToDisabled:)\/title","value":"channel:publicationDidChangeToDisabled:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:publicationDidChangeToDisabled:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"channel:publicationDidChangeToDisabled:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:)\/title","value":"findBy:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"findBy:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:didPublishStreamOf:)\/title","value":"channel:didPublishStreamOfPublication:"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:didPublishStreamOf:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"channel:didPublishStreamOfPublication:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"joinWith:completionHandler:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1join(with:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"joinWith:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1join(with:)\/fragments"},{"op":"replace","value":"createWith:sfuOptions:completion:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:sfuOptions:completion:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWith:sfuOptions:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:sfuOptions:completion:)\/fragments"},{"op":"replace","value":"findBy:completion:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"findBy:completion:"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:completion:)\/fragments"},{"op":"replace","value":"Room","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Room"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/fragments"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/navigatorTitle","value":[{"text":"Room","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:publication:metadataDidUpdate:)\/title","value":"channel:publication:metadataDidUpdate:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:publication:metadataDidUpdate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"channel:publication:metadataDidUpdate:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:didUnpublishStreamOf:)\/title","value":"channel:didUnpublishStreamOfPublication:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1channel(_:didUnpublishStreamOf:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"channel:didUnpublishStreamOfPublication:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:sfuOptions:)\/title","value":"findOrCreateWith:sfuOptions:completionHandler:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"findOrCreateWith:sfuOptions:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:sfuOptions:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:)\/title","value":"findOrCreateWith:completionHandler:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"findOrCreateWith:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:)\/fragments"},{"op":"replace","value":"SFURoom","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/title"},{"op":"replace","value":[{"text":"SFURoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/navigatorTitle","value":[{"text":"SFURoom","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}