{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/skwcameravideosourcesetcameracompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwcameravideosourcesetcameracompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWCameraVideoSourceSetCameraCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Type Alias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SKWCameraVideoSourceSetCameraCompletion"}],"externalID":"c:SKWCameraVideoSource.h@T@SKWCameraVideoSourceSetCameraCompletion","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"SKWCameraVideoSourceSetCameraCompletion","kind":"identifier"}],"title":"SKWCameraVideoSourceSetCameraCompletion","symbolKind":"typealias"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWCameraVideoSourceSetCameraCompletion"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWCameraVideoSourceSetCameraCompletion":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWCameraVideoSourceSetCameraCompletion"}],"url":"\/documentation\/skywayroom\/skwcameravideosourcesetcameracompletion","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SKWCameraVideoSourceSetCameraCompletion"}],"type":"topic","title":"SKWCameraVideoSourceSetCameraCompletion","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWCameraVideoSourceSetCameraCompletion","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SKWCameraVideoSourceSetCameraCompletion","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SKWCameraVideoSourceSetCameraCompletion","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SKWCameraVideoSourceSetCameraCompletion","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SKWCameraVideoSourceSetCameraCompletion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SKWCameraVideoSourceSetCameraCompletion","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceSetCameraCompletion\/title"},{"op":"replace","value":[{"text":"SKWCameraVideoSourceSetCameraCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceSetCameraCompletion\/fragments"},{"op":"replace","value":[{"text":"SKWCameraVideoSourceSetCameraCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceSetCameraCompletion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}