{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/skwchannelclosecompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwchannelclosecompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWChannelCloseCompletion"},{"kind":"text","text":" = ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:SKWChannel.h@T@SKWChannelCloseCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWChannelCloseCompletion","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SKWChannelCloseCompletion","kind":"identifier"}],"roleHeading":"Type Alias","symbolKind":"typealias","title":"SKWChannelCloseCompletion"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelCloseCompletion"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWChannelCloseCompletion":{"url":"\/documentation\/skywayroom\/skwchannelclosecompletion","navigatorTitle":[{"kind":"identifier","text":"SKWChannelCloseCompletion"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWChannelCloseCompletion","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelCloseCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SKWChannelCloseCompletion","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SKWChannelCloseCompletion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWChannelCloseCompletion","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SKWChannelCloseCompletion","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SKWChannelCloseCompletion","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelCloseCompletion\/title","value":"SKWChannelCloseCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelCloseCompletion\/fragments","value":[{"text":"SKWChannelCloseCompletion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelCloseCompletion\/navigatorTitle","value":[{"text":"SKWChannelCloseCompletion","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}