{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWChannelLeaveMemberCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/skywayroom\/skwchannelleavemembercompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwchannelleavemembercompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"SKWChannelLeaveMemberCompletion"}],"title":"SKWChannelLeaveMemberCompletion","symbolKind":"typealias","externalID":"c:SKWChannel.h@T@SKWChannelLeaveMemberCompletion","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWChannelLeaveMemberCompletion","kind":"identifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelLeaveMemberCompletion","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWChannelLeaveMemberCompletion":{"url":"\/documentation\/skywayroom\/skwchannelleavemembercompletion","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWChannelLeaveMemberCompletion"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelLeaveMemberCompletion","title":"SKWChannelLeaveMemberCompletion","navigatorTitle":[{"kind":"identifier","text":"SKWChannelLeaveMemberCompletion"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SKWChannelLeaveMemberCompletion","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWChannelLeaveMemberCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SKWChannelLeaveMemberCompletion","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":" ","kind":"text"},{"text":"SKWChannelLeaveMemberCompletion","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelLeaveMemberCompletion\/title","value":"SKWChannelLeaveMemberCompletion","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelLeaveMemberCompletion\/fragments","value":[{"kind":"identifier","text":"SKWChannelLeaveMemberCompletion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelLeaveMemberCompletion\/navigatorTitle","op":"replace","value":[{"text":"SKWChannelLeaveMemberCompletion","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}