{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/skwchanneldisposecompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwchanneldisposecompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWChannelDisposeCompletion"},{"kind":"text","text":" = ((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:SKWChannel.h@T@SKWChannelDisposeCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWChannelDisposeCompletion","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SKWChannelDisposeCompletion","kind":"identifier"}],"roleHeading":"Type Alias","symbolKind":"typealias","title":"SKWChannelDisposeCompletion"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelDisposeCompletion","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWChannelDisposeCompletion":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWChannelDisposeCompletion"}],"url":"\/documentation\/skywayroom\/skwchanneldisposecompletion","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SKWChannelDisposeCompletion"}],"type":"topic","title":"SKWChannelDisposeCompletion","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelDisposeCompletion","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SKWChannelDisposeCompletion","path":"\/metadata\/title","op":"replace"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SKWChannelDisposeCompletion","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SKWChannelDisposeCompletion","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":" ","kind":"text"},{"text":"SKWChannelDisposeCompletion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SKWChannelDisposeCompletion","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelDisposeCompletion\/title","op":"replace"},{"value":[{"text":"SKWChannelDisposeCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelDisposeCompletion\/fragments","op":"replace"},{"value":[{"text":"SKWChannelDisposeCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelDisposeCompletion\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}