{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWChannelUpdateMetadataCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/skwchannelupdatemetadatacompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwchannelupdatemetadatacompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Alias","navigatorTitle":[{"text":"SKWChannelUpdateMetadataCompletion","kind":"identifier"}],"title":"SKWChannelUpdateMetadataCompletion","externalID":"c:SKWChannel.h@T@SKWChannelUpdateMetadataCompletion","symbolKind":"typealias","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWChannelUpdateMetadataCompletion"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelUpdateMetadataCompletion","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWChannelUpdateMetadataCompletion":{"url":"\/documentation\/skywayroom\/skwchannelupdatemetadatacompletion","navigatorTitle":[{"kind":"identifier","text":"SKWChannelUpdateMetadataCompletion"}],"type":"topic","kind":"symbol","title":"SKWChannelUpdateMetadataCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelUpdateMetadataCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWChannelUpdateMetadataCompletion"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SKWChannelUpdateMetadataCompletion","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWChannelUpdateMetadataCompletion","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SKWChannelUpdateMetadataCompletion"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":" ","kind":"text"},{"text":"SKWChannelUpdateMetadataCompletion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelUpdateMetadataCompletion\/title","value":"SKWChannelUpdateMetadataCompletion"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelUpdateMetadataCompletion\/fragments","value":[{"text":"SKWChannelUpdateMetadataCompletion","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelUpdateMetadataCompletion\/navigatorTitle","value":[{"kind":"identifier","text":"SKWChannelUpdateMetadataCompletion"}]}]}]}