{"variants":[{"paths":["\/documentation\/skywayroom\/skwcontextsetupcompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/skwcontextsetupcompletion"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWContextSetupCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWContextSetupCompletion","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:SKWContext.h@T@SKWContextSetupCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWContextSetupCompletion","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SKWContextSetupCompletion","kind":"identifier"}],"roleHeading":"Type Alias","symbolKind":"typealias","title":"SKWContextSetupCompletion"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWContextSetupCompletion":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SKWContextSetupCompletion","kind":"identifier"}],"url":"\/documentation\/skywayroom\/skwcontextsetupcompletion","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SKWContextSetupCompletion"}],"type":"topic","title":"SKWContextSetupCompletion","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWContextSetupCompletion","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Type Alias","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SKWContextSetupCompletion","path":"\/metadata\/title"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SKWContextSetupCompletion","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SKWContextSetupCompletion"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SKWContextSetupCompletion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"SKWContextSetupCompletion","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWContextSetupCompletion\/title"},{"op":"replace","value":[{"text":"SKWContextSetupCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWContextSetupCompletion\/fragments"},{"op":"replace","value":[{"text":"SKWContextSetupCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWContextSetupCompletion\/navigatorTitle"}]}]}