{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWCameraVideoSourceChangeDeviceCompletion"},{"kind":"text","text":" = ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/skwcameravideosourcechangedevicecompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwcameravideosourcechangedevicecompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Alias","navigatorTitle":[{"text":"SKWCameraVideoSourceChangeDeviceCompletion","kind":"identifier"}],"title":"SKWCameraVideoSourceChangeDeviceCompletion","symbolKind":"typealias","externalID":"c:SKWCameraVideoSource.h@T@SKWCameraVideoSourceChangeDeviceCompletion","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWCameraVideoSourceChangeDeviceCompletion","kind":"identifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWCameraVideoSourceChangeDeviceCompletion","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWCameraVideoSourceChangeDeviceCompletion":{"url":"\/documentation\/skywayroom\/skwcameravideosourcechangedevicecompletion","navigatorTitle":[{"kind":"identifier","text":"SKWCameraVideoSourceChangeDeviceCompletion"}],"type":"topic","kind":"symbol","title":"SKWCameraVideoSourceChangeDeviceCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWCameraVideoSourceChangeDeviceCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWCameraVideoSourceChangeDeviceCompletion"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SKWCameraVideoSourceChangeDeviceCompletion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWCameraVideoSourceChangeDeviceCompletion","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SKWCameraVideoSourceChangeDeviceCompletion","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SKWCameraVideoSourceChangeDeviceCompletion","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceChangeDeviceCompletion\/title","value":"SKWCameraVideoSourceChangeDeviceCompletion"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceChangeDeviceCompletion\/fragments","value":[{"kind":"identifier","text":"SKWCameraVideoSourceChangeDeviceCompletion"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceChangeDeviceCompletion\/navigatorTitle","value":[{"text":"SKWCameraVideoSourceChangeDeviceCompletion","kind":"identifier"}]}]}]}