{
  "abstract": [
    {
      "text": "エラーファクトリー",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:objc(cs)SKWErrorFactory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SKWErrorFactory"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKWErrorFactory"
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "SKWErrorFactory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SKWErrorFactory"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/SH": {
      "identifier": "doc://com.ntt.skyway.room/SH",
      "title": "Swift.Hashable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/SQ": {
      "identifier": "doc://com.ntt.skyway.room/SQ",
      "title": "Swift.Equatable",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory": {
      "abstract": [
        {
          "text": "エラーファクトリー",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKWErrorFactory"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKWErrorFactory"
        }
      ],
      "role": "symbol",
      "title": "SKWErrorFactory",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/availableCameraIsMissing()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableCameraIsMissing"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/availableCameraIsMissing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableCameraIsMissing"
        }
      ],
      "role": "symbol",
      "title": "availableCameraIsMissing()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/availablecameraismissing()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/cameraIsNotSet()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraIsNotSet"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/cameraIsNotSet()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraIsNotSet"
        }
      ],
      "role": "symbol",
      "title": "cameraIsNotSet()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/cameraisnotset()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelCloseError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelCloseError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelCloseError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelCloseError"
        }
      ],
      "role": "symbol",
      "title": "channelCloseError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/channelcloseerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelCreateError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelCreateError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelCreateError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelCreateError"
        }
      ],
      "role": "symbol",
      "title": "channelCreateError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/channelcreateerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelFindError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelFindError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelFindError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelFindError"
        }
      ],
      "role": "symbol",
      "title": "channelFindError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/channelfinderror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelFindOrCreateError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelFindOrCreateError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelFindOrCreateError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelFindOrCreateError"
        }
      ],
      "role": "symbol",
      "title": "channelFindOrCreateError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/channelfindorcreateerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelJoinError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelJoinError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelJoinError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelJoinError"
        }
      ],
      "role": "symbol",
      "title": "channelJoinError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/channeljoinerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelLeaveError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelLeaveError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelLeaveError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelLeaveError"
        }
      ],
      "role": "symbol",
      "title": "channelLeaveError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/channelleaveerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelUpdateMetadataError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelUpdateMetadataError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelUpdateMetadataError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelUpdateMetadataError"
        }
      ],
      "role": "symbol",
      "title": "channelUpdateMetadataError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/channelupdatemetadataerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/contextDisposeError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextDisposeError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/contextDisposeError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contextDisposeError"
        }
      ],
      "role": "symbol",
      "title": "contextDisposeError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/contextdisposeerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/contextSetupError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contextSetupError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/contextSetupError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contextSetupError"
        }
      ],
      "role": "symbol",
      "title": "contextSetupError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/contextsetuperror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/fatalErrorRAPIReconnectFailedError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fatalErrorRAPIReconnectFailedError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/fatalErrorRAPIReconnectFailedError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fatalErrorRAPIReconnectFailedError"
        }
      ],
      "role": "symbol",
      "title": "fatalErrorRAPIReconnectFailedError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/fatalerrorrapireconnectfailederror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localDataStreamWriteError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localDataStreamWriteError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localDataStreamWriteError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localDataStreamWriteError"
        }
      ],
      "role": "symbol",
      "title": "localDataStreamWriteError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/localdatastreamwriteerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonPublishError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPersonPublishError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonPublishError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPersonPublishError"
        }
      ],
      "role": "symbol",
      "title": "localPersonPublishError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/localpersonpublisherror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonSubscribeError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPersonSubscribeError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonSubscribeError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPersonSubscribeError"
        }
      ],
      "role": "symbol",
      "title": "localPersonSubscribeError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/localpersonsubscribeerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonUnpublishError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPersonUnpublishError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonUnpublishError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPersonUnpublishError"
        }
      ],
      "role": "symbol",
      "title": "localPersonUnpublishError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/localpersonunpublisherror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonUnsubscribeError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPersonUnsubscribeError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonUnsubscribeError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPersonUnsubscribeError"
        }
      ],
      "role": "symbol",
      "title": "localPersonUnsubscribeError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/localpersonunsubscribeerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/memberLeaveError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memberLeaveError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/memberLeaveError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "memberLeaveError"
        }
      ],
      "role": "symbol",
      "title": "memberLeaveError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/memberleaveerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/memberUpdateMetadataError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memberUpdateMetadataError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/memberUpdateMetadataError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "memberUpdateMetadataError"
        }
      ],
      "role": "symbol",
      "title": "memberUpdateMetadataError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/memberupdatemetadataerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationCancelError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationCancelError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationCancelError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationCancelError"
        }
      ],
      "role": "symbol",
      "title": "publicationCancelError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/publicationcancelerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationDisableError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationDisableError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationDisableError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationDisableError"
        }
      ],
      "role": "symbol",
      "title": "publicationDisableError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/publicationdisableerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationEnableError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationEnableError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationEnableError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationEnableError"
        }
      ],
      "role": "symbol",
      "title": "publicationEnableError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/publicationenableerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationUpdateMetadataError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "publicationUpdateMetadataError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationUpdateMetadataError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "publicationUpdateMetadataError"
        }
      ],
      "role": "symbol",
      "title": "publicationUpdateMetadataError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/publicationupdatemetadataerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/remotePersonSubscribeError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remotePersonSubscribeError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/remotePersonSubscribeError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remotePersonSubscribeError"
        }
      ],
      "role": "symbol",
      "title": "remotePersonSubscribeError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/remotepersonsubscribeerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/remotePersonUnsubscribeError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remotePersonUnsubscribeError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/remotePersonUnsubscribeError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "remotePersonUnsubscribeError"
        }
      ],
      "role": "symbol",
      "title": "remotePersonUnsubscribeError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/remotepersonunsubscribeerror()"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/subscriptionCancelError()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscriptionCancelError"
        },
        {
          "kind": "text",
          "text": "() -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/subscriptionCancelError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscriptionCancelError"
        }
      ],
      "role": "symbol",
      "title": "subscriptionCancelError()",
      "type": "topic",
      "url": "/documentation/skywayroom/skwerrorfactory/subscriptioncancelerror()"
    },
    "doc://com.ntt.skyway.room/objc(cs)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(cs)NSObject",
      "title": "NSObject",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/objc(pl)NSObject": {
      "identifier": "doc://com.ntt.skyway.room/objc(pl)NSObject",
      "title": "ObjectiveC.NSObjectProtocol",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s23CustomStringConvertibleP": {
      "identifier": "doc://com.ntt.skyway.room/s23CustomStringConvertibleP",
      "title": "Swift.CustomStringConvertible",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP": {
      "identifier": "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP",
      "title": "Swift.CustomDebugStringConvertible",
      "type": "unresolvable"
    },
    "doc://com.ntt.skyway.room/s7CVarArgP": {
      "identifier": "doc://com.ntt.skyway.room/s7CVarArgP",
      "title": "Swift.CVarArg",
      "type": "unresolvable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.ntt.skyway.room/objc(pl)NSObject",
        "doc://com.ntt.skyway.room/s7CVarArgP",
        "doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP",
        "doc://com.ntt.skyway.room/s23CustomStringConvertibleP",
        "doc://com.ntt.skyway.room/SQ",
        "doc://com.ntt.skyway.room/SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/availableCameraIsMissing()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/cameraIsNotSet()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelCloseError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelCreateError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelFindError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelFindOrCreateError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelJoinError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelLeaveError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelUpdateMetadataError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/contextDisposeError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/contextSetupError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/fatalErrorRAPIReconnectFailedError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localDataStreamWriteError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonPublishError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonSubscribeError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonUnpublishError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonUnsubscribeError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/memberLeaveError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/memberUpdateMetadataError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationCancelError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationDisableError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationEnableError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationUpdateMetadataError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/remotePersonSubscribeError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/remotePersonUnsubscribeError()",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/subscriptionCancelError()"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKWErrorFactory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWErrorFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWErrorFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/availableCameraIsMissing()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/cameraIsNotSet()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelCloseError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelCreateError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelFindError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelFindOrCreateError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelJoinError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelLeaveError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/channelUpdateMetadataError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/contextDisposeError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/contextSetupError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/fatalErrorRAPIReconnectFailedError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localDataStreamWriteError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonPublishError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonSubscribeError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonUnpublishError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonUnsubscribeError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/memberLeaveError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/memberUpdateMetadataError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationCancelError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationDisableError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationEnableError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/publicationUpdateMetadataError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/remotePersonSubscribeError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/remotePersonUnsubscribeError()",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/subscriptionCancelError()"
              ],
              "title": "Type Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.ntt.skyway.room/objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "SKWErrorFactory"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1subscriptionCancelError()/title",
          "value": "subscriptionCancelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1subscriptionCancelError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "subscriptionCancelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonPublishError()/title",
          "value": "localPersonPublishError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonPublishError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localPersonPublishError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonSubscribeError()/title",
          "value": "localPersonSubscribeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonSubscribeError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localPersonSubscribeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelLeaveError()/title",
          "value": "channelLeaveError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelLeaveError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "channelLeaveError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory/title",
          "value": "SKWErrorFactory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWErrorFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKWErrorFactory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1publicationDisableError()/title",
          "value": "publicationDisableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1publicationDisableError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "publicationDisableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1remotePersonUnsubscribeError()/title",
          "value": "remotePersonUnsubscribeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1remotePersonUnsubscribeError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "remotePersonUnsubscribeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1publicationUpdateMetadataError()/title",
          "value": "publicationUpdateMetadataError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1publicationUpdateMetadataError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "publicationUpdateMetadataError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelFindOrCreateError()/title",
          "value": "channelFindOrCreateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelFindOrCreateError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "channelFindOrCreateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1fatalErrorRAPIReconnectFailedError()/title",
          "value": "fatalErrorRAPIReconnectFailedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1fatalErrorRAPIReconnectFailedError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fatalErrorRAPIReconnectFailedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1cameraIsNotSet()/title",
          "value": "cameraIsNotSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1cameraIsNotSet()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "cameraIsNotSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonUnpublishError()/title",
          "value": "localPersonUnpublishError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonUnpublishError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localPersonUnpublishError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelJoinError()/title",
          "value": "channelJoinError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelJoinError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "channelJoinError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1memberLeaveError()/title",
          "value": "memberLeaveError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1memberLeaveError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "memberLeaveError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelUpdateMetadataError()/title",
          "value": "channelUpdateMetadataError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelUpdateMetadataError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "channelUpdateMetadataError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1publicationCancelError()/title",
          "value": "publicationCancelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1publicationCancelError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "publicationCancelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelFindError()/title",
          "value": "channelFindError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelFindError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "channelFindError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localDataStreamWriteError()/title",
          "value": "localDataStreamWriteError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localDataStreamWriteError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localDataStreamWriteError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelCreateError()/title",
          "value": "channelCreateError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelCreateError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "channelCreateError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelCloseError()/title",
          "value": "channelCloseError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1channelCloseError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "channelCloseError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonUnsubscribeError()/title",
          "value": "localPersonUnsubscribeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonUnsubscribeError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "localPersonUnsubscribeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1contextDisposeError()/title",
          "value": "contextDisposeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1contextDisposeError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "contextDisposeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1publicationEnableError()/title",
          "value": "publicationEnableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1publicationEnableError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "publicationEnableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1availableCameraIsMissing()/title",
          "value": "availableCameraIsMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1availableCameraIsMissing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "availableCameraIsMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1memberUpdateMetadataError()/title",
          "value": "memberUpdateMetadataError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1memberUpdateMetadataError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "memberUpdateMetadataError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1remotePersonSubscribeError()/title",
          "value": "remotePersonSubscribeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1remotePersonSubscribeError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "remotePersonSubscribeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1contextSetupError()/title",
          "value": "contextSetupError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1contextSetupError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "contextSetupError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/skwerrorfactory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/skwerrorfactory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
