{"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/SY","doc:\/\/com.ntt.skyway.room\/s8SendableP","doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/skwerrorcode"]},{"paths":["\/documentation\/skywayroom\/skwerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"エラーコード","type":"text"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/availableCameraIsMissing","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/cameraIsNotSet","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelCloseError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelCreateError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelFindError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelFindOrCreateError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelJoinError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelLeaveError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelUpdateMetadataError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/contextDisposeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/contextSetupError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/fatalErrorRAPIReconnectFailed","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localDataStreamWriteError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonPublishError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonSubscribeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonUnpublishError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonUnsubscribeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/memberLeaveError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/memberUpdateMetadataError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationCancelError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationDisableError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationEnableError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationUpdateMetadataError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/remotePersonSubscribeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/remotePersonUnsubscribeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/subscriptionCancelError"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/Equatable-Implementations","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWErrorCode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:@E@SKWErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWErrorCode","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SKWErrorCode","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"SKWErrorCode"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/localDataStreamWriteError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/localdatastreamwriteerror","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localDataStreamWriteError"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localDataStreamWriteError","title":"SKWErrorCode.localDataStreamWriteError","navigatorTitle":[{"kind":"identifier","text":"SKWLocalDataStreamWriteError"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/subscriptionCancelError":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscriptionCancelError","kind":"identifier"}],"url":"\/documentation\/skywayroom\/skwerrorcode\/subscriptioncancelerror","role":"symbol","navigatorTitle":[{"text":"SKWSubscriptionCancelError","kind":"identifier"}],"type":"topic","title":"SKWErrorCode.subscriptionCancelError","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/subscriptionCancelError","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/contextDisposeError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/contextdisposeerror","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextDisposeError"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/contextDisposeError","title":"SKWErrorCode.contextDisposeError","navigatorTitle":[{"text":"SKWContextDisposeError","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/channelFindOrCreateError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/channelfindorcreateerror","navigatorTitle":[{"kind":"identifier","text":"SKWChannelFindOrCreateError"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.channelFindOrCreateError","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelFindOrCreateError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelFindOrCreateError"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/publicationEnableError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/publicationenableerror","navigatorTitle":[{"kind":"identifier","text":"SKWPublicationEnableError"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.publicationEnableError","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationEnableError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicationEnableError"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/publicationCancelError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/publicationcancelerror","navigatorTitle":[{"text":"SKWPublicationCancelError","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.publicationCancelError","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationCancelError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publicationCancelError","kind":"identifier"}]},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/publicationUpdateMetadataError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/publicationupdatemetadataerror","navigatorTitle":[{"kind":"identifier","text":"SKWPublicationUpdateMetadataError"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.publicationUpdateMetadataError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationUpdateMetadataError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicationUpdateMetadataError"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/memberUpdateMetadataError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/memberupdatemetadataerror","navigatorTitle":[{"text":"SKWMemberUpdateMetadataError","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.memberUpdateMetadataError","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/memberUpdateMetadataError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberUpdateMetadataError","kind":"identifier"}]},"doc://com.ntt.skyway.room/SY":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SY","title":"Swift.RawRepresentable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/channelCreateError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/channelcreateerror","navigatorTitle":[{"kind":"identifier","text":"SKWChannelCreateError"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.channelCreateError","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelCreateError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelCreateError","kind":"identifier"}]},"doc://com.ntt.skyway.room/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/localPersonUnpublishError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/localpersonunpublisherror","navigatorTitle":[{"kind":"identifier","text":"SKWLocalPersonUnpublishError"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.localPersonUnpublishError","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonUnpublishError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localPersonUnpublishError"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/contextSetupError":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextSetupError"}],"url":"\/documentation\/skywayroom\/skwerrorcode\/contextsetuperror","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SKWContextSetupError"}],"type":"topic","title":"SKWErrorCode.contextSetupError","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/contextSetupError","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/Equatable-Implementations":{"url":"\/documentation\/skywayroom\/skwerrorcode\/equatable-implementations","type":"topic","kind":"article","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/Equatable-Implementations"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/cameraIsNotSet":{"url":"\/documentation\/skywayroom\/skwerrorcode\/cameraisnotset","navigatorTitle":[{"text":"SKWCameraIsNotSet","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.cameraIsNotSet","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/cameraIsNotSet","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraIsNotSet","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/fatalErrorRAPIReconnectFailed":{"url":"\/documentation\/skywayroom\/skwerrorcode\/fatalerrorrapireconnectfailed","navigatorTitle":[{"kind":"identifier","text":"SKWFatalErrorRAPIReconnectFailed"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.fatalErrorRAPIReconnectFailed","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/fatalErrorRAPIReconnectFailed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fatalErrorRAPIReconnectFailed"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/RawRepresentable-Implementations":{"url":"\/documentation\/skywayroom\/skwerrorcode\/rawrepresentable-implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/RawRepresentable-Implementations"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/remotePersonUnsubscribeError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/remotepersonunsubscribeerror","navigatorTitle":[{"text":"SKWRemotePersonUnsubscribeError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.remotePersonUnsubscribeError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/remotePersonUnsubscribeError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remotePersonUnsubscribeError","kind":"identifier"}]},"doc://com.ntt.skyway.room/s16SendableMetatypeP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/memberLeaveError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/memberleaveerror","navigatorTitle":[{"text":"SKWMemberLeaveError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.memberLeaveError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/memberLeaveError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberLeaveError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/availableCameraIsMissing":{"url":"\/documentation\/skywayroom\/skwerrorcode\/availablecameraismissing","navigatorTitle":[{"text":"SKWAvailableCameraIsMissing","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode.availableCameraIsMissing","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/availableCameraIsMissing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableCameraIsMissing","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/init(rawValue:)":{"url":"\/documentation\/skywayroom\/skwerrorcode\/init(rawvalue:)","type":"topic","kind":"symbol","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/s8SendableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/localPersonPublishError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/localpersonpublisherror","navigatorTitle":[{"text":"SKWLocalPersonPublishError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.localPersonPublishError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonPublishError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localPersonPublishError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/publicationDisableError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/publicationdisableerror","navigatorTitle":[{"text":"SKWPublicationDisableError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.publicationDisableError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationDisableError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publicationDisableError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/localPersonSubscribeError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/localpersonsubscribeerror","navigatorTitle":[{"text":"SKWLocalPersonSubscribeError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.localPersonSubscribeError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonSubscribeError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localPersonSubscribeError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/channelFindError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/channelfinderror","navigatorTitle":[{"text":"SKWChannelFindError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.channelFindError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelFindError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelFindError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/localPersonUnsubscribeError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/localpersonunsubscribeerror","navigatorTitle":[{"text":"SKWLocalPersonUnsubscribeError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.localPersonUnsubscribeError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonUnsubscribeError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localPersonUnsubscribeError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/channelJoinError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/channeljoinerror","navigatorTitle":[{"text":"SKWChannelJoinError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.channelJoinError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelJoinError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelJoinError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/channelLeaveError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/channelleaveerror","navigatorTitle":[{"kind":"identifier","text":"SKWChannelLeaveError"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.channelLeaveError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelLeaveError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"channelLeaveError"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode":{"url":"\/documentation\/skywayroom\/skwerrorcode","navigatorTitle":[{"text":"SKWErrorCode","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWErrorCode","abstract":[{"type":"text","text":"エラーコード"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWErrorCode","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/channelUpdateMetadataError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/channelupdatemetadataerror","navigatorTitle":[{"text":"SKWChannelUpdateMetadataError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.channelUpdateMetadataError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelUpdateMetadataError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelUpdateMetadataError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/remotePersonSubscribeError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/remotepersonsubscribeerror","navigatorTitle":[{"text":"SKWRemotePersonSubscribeError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.remotePersonSubscribeError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/remotePersonSubscribeError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remotePersonSubscribeError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorCode/channelCloseError":{"url":"\/documentation\/skywayroom\/skwerrorcode\/channelcloseerror","navigatorTitle":[{"text":"SKWChannelCloseError","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"title":"SKWErrorCode.channelCloseError","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelCloseError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"channelCloseError","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"SKWErrorCode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SKWErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/availableCameraIsMissing","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/cameraIsNotSet","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelCloseError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelCreateError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelFindError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelFindOrCreateError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelJoinError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelLeaveError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/channelUpdateMetadataError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/contextDisposeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/contextSetupError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/fatalErrorRAPIReconnectFailed","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localDataStreamWriteError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonPublishError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonSubscribeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonUnpublishError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/localPersonUnsubscribeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/memberLeaveError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/memberUpdateMetadataError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationCancelError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationDisableError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationEnableError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/publicationUpdateMetadataError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/remotePersonSubscribeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/remotePersonUnsubscribeError","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorCode\/subscriptionCancelError"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWErrorCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localDataStreamWriteError\/title","value":"SKWLocalDataStreamWriteError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localDataStreamWriteError\/fragments","value":[{"text":"SKWLocalDataStreamWriteError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1subscriptionCancelError\/title","value":"SKWSubscriptionCancelError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1subscriptionCancelError\/fragments","value":[{"text":"SKWSubscriptionCancelError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1contextDisposeError\/title","value":"SKWContextDisposeError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1contextDisposeError\/fragments","value":[{"text":"SKWContextDisposeError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelFindOrCreateError\/title","value":"SKWChannelFindOrCreateError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelFindOrCreateError\/fragments","value":[{"text":"SKWChannelFindOrCreateError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1publicationEnableError\/title","value":"SKWPublicationEnableError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1publicationEnableError\/fragments","value":[{"text":"SKWPublicationEnableError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1publicationCancelError\/title","value":"SKWPublicationCancelError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1publicationCancelError\/fragments","value":[{"text":"SKWPublicationCancelError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1publicationUpdateMetadataError\/title","value":"SKWPublicationUpdateMetadataError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1publicationUpdateMetadataError\/fragments","value":[{"text":"SKWPublicationUpdateMetadataError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1memberUpdateMetadataError\/title","value":"SKWMemberUpdateMetadataError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1memberUpdateMetadataError\/fragments","value":[{"text":"SKWMemberUpdateMetadataError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelCreateError\/title","value":"SKWChannelCreateError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelCreateError\/fragments","value":[{"text":"SKWChannelCreateError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonUnpublishError\/title","value":"SKWLocalPersonUnpublishError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonUnpublishError\/fragments","value":[{"text":"SKWLocalPersonUnpublishError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1contextSetupError\/title","value":"SKWContextSetupError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1contextSetupError\/fragments","value":[{"text":"SKWContextSetupError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1cameraIsNotSet\/title","value":"SKWCameraIsNotSet","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1cameraIsNotSet\/fragments","value":[{"text":"SKWCameraIsNotSet","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1fatalErrorRAPIReconnectFailed\/title","value":"SKWFatalErrorRAPIReconnectFailed","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1fatalErrorRAPIReconnectFailed\/fragments","value":[{"text":"SKWFatalErrorRAPIReconnectFailed","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1remotePersonUnsubscribeError\/title","value":"SKWRemotePersonUnsubscribeError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1remotePersonUnsubscribeError\/fragments","value":[{"text":"SKWRemotePersonUnsubscribeError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1memberLeaveError\/title","value":"SKWMemberLeaveError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1memberLeaveError\/fragments","value":[{"text":"SKWMemberLeaveError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1availableCameraIsMissing\/title","value":"SKWAvailableCameraIsMissing","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1availableCameraIsMissing\/fragments","value":[{"text":"SKWAvailableCameraIsMissing","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonPublishError\/title","value":"SKWLocalPersonPublishError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonPublishError\/fragments","value":[{"text":"SKWLocalPersonPublishError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1publicationDisableError\/title","value":"SKWPublicationDisableError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1publicationDisableError\/fragments","value":[{"text":"SKWPublicationDisableError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonSubscribeError\/title","value":"SKWLocalPersonSubscribeError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonSubscribeError\/fragments","value":[{"text":"SKWLocalPersonSubscribeError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelFindError\/title","value":"SKWChannelFindError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelFindError\/fragments","value":[{"text":"SKWChannelFindError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonUnsubscribeError\/title","value":"SKWLocalPersonUnsubscribeError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1localPersonUnsubscribeError\/fragments","value":[{"text":"SKWLocalPersonUnsubscribeError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelJoinError\/title","value":"SKWChannelJoinError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelJoinError\/fragments","value":[{"text":"SKWChannelJoinError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelLeaveError\/title","value":"SKWChannelLeaveError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelLeaveError\/fragments","value":[{"text":"SKWChannelLeaveError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/title","value":"SKWErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/fragments","value":[{"text":"SKWErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode\/navigatorTitle","value":[{"text":"SKWErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelUpdateMetadataError\/title","value":"SKWChannelUpdateMetadataError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelUpdateMetadataError\/fragments","value":[{"text":"SKWChannelUpdateMetadataError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1remotePersonSubscribeError\/title","value":"SKWRemotePersonSubscribeError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1remotePersonSubscribeError\/fragments","value":[{"text":"SKWRemotePersonSubscribeError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelCloseError\/title","value":"SKWChannelCloseError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorCode~1channelCloseError\/fragments","value":[{"text":"SKWChannelCloseError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}