{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/skywayroom\/skwfilevideosourcestartcapturingonerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwfilevideosourcestartcapturingonerror"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Alias","navigatorTitle":[{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"}],"title":"SKWFileVideoSourceStartCapturingOnError","externalID":"c:SKWFileVideoSource.h@T@SKWFileVideoSourceStartCapturingOnError","symbolKind":"typealias","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWFileVideoSourceStartCapturingOnError","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWFileVideoSourceStartCapturingOnError":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"}],"url":"\/documentation\/skywayroom\/skwfilevideosourcestartcapturingonerror","role":"symbol","navigatorTitle":[{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"}],"type":"topic","title":"SKWFileVideoSourceStartCapturingOnError","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWFileVideoSourceStartCapturingOnError","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SKWFileVideoSourceStartCapturingOnError","op":"replace"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SKWFileVideoSourceStartCapturingOnError","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWFileVideoSourceStartCapturingOnError\/title","op":"replace"},{"op":"replace","value":[{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWFileVideoSourceStartCapturingOnError\/fragments"},{"op":"replace","value":[{"text":"SKWFileVideoSourceStartCapturingOnError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWFileVideoSourceStartCapturingOnError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}