{"variants":[{"paths":["\/documentation\/skywayroom\/skwlocaldatastreamcompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwlocaldatastreamcompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWLocalDataStreamCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWLocalDataStreamCompletion","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"roleHeading":"Type Alias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}],"externalID":"c:SKWLocalDataStream.h@T@SKWLocalDataStreamCompletion","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}],"title":"SKWLocalDataStreamCompletion","symbolKind":"typealias"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWLocalDataStreamCompletion":{"url":"\/documentation\/skywayroom\/skwlocaldatastreamcompletion","navigatorTitle":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWLocalDataStreamCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWLocalDataStreamCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SKWLocalDataStreamCompletion"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWLocalDataStreamCompletion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalDataStreamCompletion\/title","value":"SKWLocalDataStreamCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalDataStreamCompletion\/fragments","value":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalDataStreamCompletion\/navigatorTitle","value":[{"text":"SKWLocalDataStreamCompletion","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}