{"variants":[{"paths":["\/documentation\/skywayroom\/skwlocalpersonunsubscribecompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwlocalpersonunsubscribecompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWLocalPersonUnsubscribeCompletion","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"externalID":"c:SKWLocalPerson.h@T@SKWLocalPersonUnsubscribeCompletion","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}],"roleHeading":"Type Alias","symbolKind":"typealias","title":"SKWLocalPersonUnsubscribeCompletion"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWLocalPersonUnsubscribeCompletion":{"url":"\/documentation\/skywayroom\/skwlocalpersonunsubscribecompletion","navigatorTitle":[{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SKWLocalPersonUnsubscribeCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWLocalPersonUnsubscribeCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SKWLocalPersonUnsubscribeCompletion"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SKWLocalPersonUnsubscribeCompletion"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":" ","kind":"text"},{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SKWLocalPersonUnsubscribeCompletion","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalPersonUnsubscribeCompletion\/title"},{"op":"replace","value":[{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalPersonUnsubscribeCompletion\/fragments"},{"op":"replace","value":[{"text":"SKWLocalPersonUnsubscribeCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWLocalPersonUnsubscribeCompletion\/navigatorTitle"}]}]}