{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWPublicationCancelCompletion","kind":"identifier"},{"text":" = ((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/skywayroom\/skwpublicationcancelcompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/skwpublicationcancelcompletion"]}],"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:SKWPublication.h@T@SKWPublicationCancelCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWPublicationCancelCompletion"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SKWPublicationCancelCompletion"}],"roleHeading":"Type Alias","symbolKind":"typealias","title":"SKWPublicationCancelCompletion"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWPublicationCancelCompletion","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWPublicationCancelCompletion":{"url":"\/documentation\/skywayroom\/skwpublicationcancelcompletion","navigatorTitle":[{"kind":"identifier","text":"SKWPublicationCancelCompletion"}],"type":"topic","kind":"symbol","title":"SKWPublicationCancelCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWPublicationCancelCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWPublicationCancelCompletion","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SKWPublicationCancelCompletion","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWPublicationCancelCompletion","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SKWPublicationCancelCompletion"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SKWPublicationCancelCompletion","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"SKWPublicationCancelCompletion","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWPublicationCancelCompletion\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SKWPublicationCancelCompletion"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWPublicationCancelCompletion\/fragments"},{"op":"replace","value":[{"text":"SKWPublicationCancelCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWPublicationCancelCompletion\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}