{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/skwremotepersonsubscribepublicationcompletion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/skwremotepersonsubscribepublicationcompletion"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWRemotePersonSubscribePublicationCompletion"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"Subscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription","preciseIdentifier":"c:objc(cs)SKWSubscription"},{"kind":"text","text":"?, (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"roleHeading":"Type Alias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWRemotePersonSubscribePublicationCompletion","kind":"identifier"}],"externalID":"c:SKWRemotePerson.h@T@SKWRemotePersonSubscribePublicationCompletion","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"kind":"identifier","text":"SKWRemotePersonSubscribePublicationCompletion"}],"title":"SKWRemotePersonSubscribePublicationCompletion","symbolKind":"typealias"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWRemotePersonSubscribePublicationCompletion"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Subscription":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Subscription","kind":"identifier"}],"url":"\/documentation\/skywayroom\/subscription","role":"symbol","navigatorTitle":[{"text":"Subscription","kind":"identifier"}],"type":"topic","title":"Subscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription","abstract":[{"type":"text","text":"SubscriptionはLocalMemberがSubscribeした時に取得でき、Subscriptionに含まれるStreamを利用して映像を描画したりします。"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWRemotePersonSubscribePublicationCompletion":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWRemotePersonSubscribePublicationCompletion","kind":"identifier"}],"url":"\/documentation\/skywayroom\/skwremotepersonsubscribepublicationcompletion","role":"symbol","navigatorTitle":[{"text":"SKWRemotePersonSubscribePublicationCompletion","kind":"identifier"}],"type":"topic","title":"SKWRemotePersonSubscribePublicationCompletion","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWRemotePersonSubscribePublicationCompletion","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SKWRemotePersonSubscribePublicationCompletion","op":"replace","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SKWRemotePersonSubscribePublicationCompletion"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SKWRemotePersonSubscribePublicationCompletion","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"void (^)(SKWSubscription *, NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)SKWSubscription#*$objc(cs)NSError)"},{"text":" ","kind":"text"},{"text":"SKWRemotePersonSubscribePublicationCompletion","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/title","value":"SKWSubscription"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/fragments","value":[{"kind":"identifier","text":"SKWSubscription"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/navigatorTitle","value":[{"text":"SKWSubscription","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWRemotePersonSubscribePublicationCompletion\/title","value":"SKWRemotePersonSubscribePublicationCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWRemotePersonSubscribePublicationCompletion\/fragments","value":[{"kind":"identifier","text":"SKWRemotePersonSubscribePublicationCompletion"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWRemotePersonSubscribePublicationCompletion\/navigatorTitle","value":[{"kind":"identifier","text":"SKWRemotePersonSubscribePublicationCompletion"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}