{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/skwremotepersonunsubscribecompletion"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwremotepersonunsubscribecompletion"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWRemotePersonUnsubscribeCompletion"},{"kind":"text","text":" = ((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"roleHeading":"Type Alias","navigatorTitle":[{"text":"SKWRemotePersonUnsubscribeCompletion","kind":"identifier"}],"title":"SKWRemotePersonUnsubscribeCompletion","externalID":"c:SKWRemotePerson.h@T@SKWRemotePersonUnsubscribeCompletion","symbolKind":"typealias","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SKWRemotePersonUnsubscribeCompletion","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWRemotePersonUnsubscribeCompletion"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWRemotePersonUnsubscribeCompletion":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWRemotePersonUnsubscribeCompletion","kind":"identifier"}],"url":"\/documentation\/skywayroom\/skwremotepersonunsubscribecompletion","role":"symbol","navigatorTitle":[{"text":"SKWRemotePersonUnsubscribeCompletion","kind":"identifier"}],"type":"topic","title":"SKWRemotePersonUnsubscribeCompletion","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWRemotePersonUnsubscribeCompletion","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"path":"\/metadata\/title","value":"SKWRemotePersonUnsubscribeCompletion","op":"replace"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SKWRemotePersonUnsubscribeCompletion"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SKWRemotePersonUnsubscribeCompletion"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SKWRemotePersonUnsubscribeCompletion","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWRemotePersonUnsubscribeCompletion\/title","value":"SKWRemotePersonUnsubscribeCompletion","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWRemotePersonUnsubscribeCompletion\/fragments","value":[{"kind":"identifier","text":"SKWRemotePersonUnsubscribeCompletion"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWRemotePersonUnsubscribeCompletion\/navigatorTitle","value":[{"text":"SKWRemotePersonUnsubscribeCompletion","kind":"identifier"}],"op":"replace"}]}]}