{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"],"type":"inheritsFrom"},{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription"]}],"variants":[{"paths":["\/documentation\/skywayroom\/subscriptiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/subscriptiondelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Subscriptionイベントデリゲート","type":"text"}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SubscriptionDelegate\/subscription(_:connectionStateDidChange:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SubscriptionDelegate\/subscription(_:didAttach:)"],"generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SubscriptionDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SubscriptionDelegate","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SubscriptionDelegate","kind":"identifier"}],"externalID":"c:objc(pl)SKWSubscriptionDelegate","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"SubscriptionDelegate","kind":"identifier"}],"title":"SubscriptionDelegate","symbolKind":"protocol"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SubscriptionDelegate":{"url":"\/documentation\/skywayroom\/subscriptiondelegate","navigatorTitle":[{"text":"SubscriptionDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SubscriptionDelegate","abstract":[{"type":"text","text":"Subscriptionイベントデリゲート"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SubscriptionDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SubscriptionDelegate","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SubscriptionDelegate/subscription(_:connectionStateDidChange:)":{"url":"\/documentation\/skywayroom\/subscriptiondelegate\/subscription(_:connectionstatedidchange:)","navigatorTitle":[{"text":"subscription:connectionStateDidChange:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"subscription(_:connectionStateDidChange:)","abstract":[{"type":"text","text":"RoomSubscriptionの接続状態が変化した後にコールされるイベント"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SubscriptionDelegate\/subscription(_:connectionStateDidChange:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscription","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Subscription","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSubscription"},{"text":", ","kind":"text"},{"text":"connectionStateDidChange","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConnectionState","kind":"typeIdentifier","preciseIdentifier":"c:@E@SKWConnectionState"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscription":{"url":"\/documentation\/skywayroom\/roomsubscription","navigatorTitle":[{"kind":"identifier","text":"RoomSubscription"}],"type":"topic","kind":"symbol","title":"RoomSubscription","abstract":[{"text":"Room SDK におけるSubscription","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RoomSubscription","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SubscriptionDelegate/subscription(_:didAttach:)":{"url":"\/documentation\/skywayroom\/subscriptiondelegate\/subscription(_:didattach:)","navigatorTitle":[{"kind":"identifier","text":"subscription:didAttach:"}],"type":"topic","kind":"symbol","title":"subscription(_:didAttach:)","abstract":[{"text":"RoomSubscriptionにRemoteStreamが追加された時にコールされるイベント","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SubscriptionDelegate\/subscription(_:didAttach:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscription","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWSubscription","text":"Subscription","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didAttach","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RemoteStream","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWRemoteStream"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SKWSubscriptionDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"SKWSubscriptionDelegate"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SKWSubscriptionDelegate","kind":"identifier"}]},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SubscriptionDelegate\/subscription(_:connectionStateDidChange:)","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SubscriptionDelegate\/subscription(_:didAttach:)"],"anchor":"Instance-Methods"}],"op":"replace"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription"],"type":"conformingTypes"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"SKWSubscriptionDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SKWSubscriptionDelegate","op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SubscriptionDelegate\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SubscriptionDelegate\/fragments","value":[{"text":"SKWSubscriptionDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SubscriptionDelegate\/navigatorTitle","value":[{"text":"SKWSubscriptionDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SubscriptionDelegate~1subscription(_:connectionStateDidChange:)\/title","value":"subscription:connectionStateDidChange:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SubscriptionDelegate~1subscription(_:connectionStateDidChange:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"subscription:connectionStateDidChange:","kind":"identifier"}],"op":"replace"},{"value":"RoomSubscription","op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/fragments","value":[{"text":"RoomSubscription","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"RoomSubscription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SubscriptionDelegate~1subscription(_:didAttach:)\/title","op":"replace","value":"subscription:didAttach:"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SubscriptionDelegate~1subscription(_:didAttach:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"subscription:didAttach:","kind":"identifier"}]}]}]}