{"kind":"symbol","topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/disable","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/enable","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/turnOnly"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/Equatable-Implementations","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/RawRepresentable-Implementations"],"generated":true}],"sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/turnpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/turnpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/SY","doc:\/\/com.ntt.skyway.room\/s8SendableP","doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TurnPolicy","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"text":"TURNについてはこちらをご覧ください。","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"https:\/\/skyway.ntt.com\/ja\/docs\/user-guide\/turn\/","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:@E@SKWTurnPolicy","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TurnPolicy","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TurnPolicy","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"TurnPolicy"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy","interfaceLanguage":"swift"},"abstract":[{"text":"TURNサーバに関するポリシー","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/TurnPolicy/enable":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"enable","kind":"identifier"}],"url":"\/documentation\/skywayroom\/turnpolicy\/enable","role":"symbol","navigatorTitle":[{"text":"SKWTurnPolicyEnable","kind":"identifier"}],"type":"topic","title":"TurnPolicy.enable","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/enable","abstract":[{"text":"TURNが有効なモード","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/TurnPolicy/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/skywayroom\/turnpolicy\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/RawRepresentable-Implementations","abstract":[]},"doc://com.ntt.skyway.room/SQ":{"identifier":"doc:\/\/com.ntt.skyway.room\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/TurnPolicy":{"url":"\/documentation\/skywayroom\/turnpolicy","type":"topic","abstract":[{"type":"text","text":"TURNサーバに関するポリシー"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TurnPolicy"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy","title":"TurnPolicy","navigatorTitle":[{"kind":"identifier","text":"TurnPolicy"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/TurnPolicy/turnOnly":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"turnOnly","kind":"identifier"}],"url":"\/documentation\/skywayroom\/turnpolicy\/turnonly","role":"symbol","navigatorTitle":[{"text":"SKWTurnPolicyTurnOnly","kind":"identifier"}],"type":"topic","title":"TurnPolicy.turnOnly","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/turnOnly","abstract":[{"text":"TURNサーバ経由を強制するモード","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/TurnPolicy/init(rawValue:)":{"url":"\/documentation\/skywayroom\/turnpolicy\/init(rawvalue:)","type":"topic","kind":"symbol","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/TurnPolicy/disable":{"url":"\/documentation\/skywayroom\/turnpolicy\/disable","navigatorTitle":[{"text":"SKWTurnPolicyDisable","kind":"identifier"}],"type":"topic","kind":"symbol","title":"TurnPolicy.disable","abstract":[{"text":"TURNが無効なモード","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/disable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disable","kind":"identifier"}]},"doc://com.ntt.skyway.room/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.ntt.skyway.room/SY":{"identifier":"doc:\/\/com.ntt.skyway.room\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.ntt.skyway.room/s16SendableMetatypeP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP","type":"unresolvable","title":"Swift.SendableMetatype"},"doc://com.ntt.skyway.room/s8SendableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/TurnPolicy/Equatable-Implementations":{"kind":"article","url":"\/documentation\/skywayroom\/turnpolicy\/equatable-implementations","role":"collectionGroup","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/Equatable-Implementations","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SKWTurnPolicy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SKWTurnPolicy","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SKWTurnPolicy","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/disable","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/enable","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/TurnPolicy\/turnOnly"],"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWTurnPolicy","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy~1enable\/title","value":"SKWTurnPolicyEnable"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy~1enable\/fragments","value":[{"text":"SKWTurnPolicyEnable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy\/title","value":"SKWTurnPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy\/fragments","value":[{"text":"SKWTurnPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy\/navigatorTitle","value":[{"text":"SKWTurnPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy~1turnOnly\/title","value":"SKWTurnPolicyTurnOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy~1turnOnly\/fragments","value":[{"text":"SKWTurnPolicyTurnOnly","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy~1disable\/title","value":"SKWTurnPolicyDisable"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1TurnPolicy~1disable\/fragments","value":[{"text":"SKWTurnPolicyDisable","kind":"identifier"}]}]}]}