{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)UIView"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.ntt.skyway.room\/objc(pl)NSCoding","doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","doc:\/\/com.ntt.skyway.room\/objc(pl)CALayerDelegate","doc:\/\/com.ntt.skyway.room\/s7CVarArgP","doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP","doc:\/\/com.ntt.skyway.room\/SQ","doc:\/\/com.ntt.skyway.room\/SH","doc:\/\/com.ntt.skyway.room\/s8SendableP","doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP","doc:\/\/com.ntt.skyway.room\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.ntt.skyway.room\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.ntt.skyway.room\/objc(pl)UIAppearance","doc:\/\/com.ntt.skyway.room\/objc(pl)UIAppearanceContainer","doc:\/\/com.ntt.skyway.room\/objc(pl)UIDynamicItem","doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusEnvironment","doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusItem","doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusItemContainer","doc:\/\/com.ntt.skyway.room\/objc(pl)UILargeContentViewerItem","doc:\/\/com.ntt.skyway.room\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.ntt.skyway.room\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.ntt.skyway.room\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.ntt.skyway.room\/5UIKit23UITraitChangeObservableP","doc:\/\/com.ntt.skyway.room\/objc(pl)UITraitEnvironment","doc:\/\/com.ntt.skyway.room\/objc(pl)UIUserActivityRestoring","doc:\/\/com.ntt.skyway.room\/objc(pl)UICoordinateSpace"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/skywayroom\/videoview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/videoview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Videoを描画するView","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView\/rendererView","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView\/videoContentMode"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoView","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"描画するためには"},{"code":"SKWLocalVideoStream","type":"codeVoice"},{"type":"text","text":"または"},{"code":"SKWRemoteVideoStream","type":"codeVoice"},{"type":"text","text":"の"},{"code":"attach(_:)","type":"codeVoice"},{"type":"text","text":"に引数を渡してください。"}],"type":"paragraph"},{"inlineContent":[{"text":"StoryboardのCustom Classを利用する場合は","type":"text"},{"code":"VideoView","type":"codeVoice"},{"text":"ではなく","type":"text"},{"code":"SKWVideoView","type":"codeVoice"},{"text":"を指定して下さい。","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"グラフィックスAPIはMetalを利用しています。","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom"]]},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoView","kind":"identifier"}],"externalID":"c:objc(cs)SKWVideoView","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"VideoView","kind":"identifier"}],"title":"VideoView","symbolKind":"class"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/objc(pl)NSObject":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.ntt.skyway.room/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://com.ntt.skyway.room/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.ntt.skyway.room/SH":{"identifier":"doc:\/\/com.ntt.skyway.room\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.ntt.skyway.room/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.ntt.skyway.room/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIUtilities.UICoordinateSpace"},"doc://com.ntt.skyway.room/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/VideoView/videoContentMode":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoContentMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ContentMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIViewContentMode"}],"url":"\/documentation\/skywayroom\/videoview\/videocontentmode","role":"symbol","navigatorTitle":[{"text":"videoContentMode","kind":"identifier"}],"type":"topic","title":"videoContentMode","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView\/videoContentMode","abstract":[{"text":"描画するVideoのContentMode","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/VideoView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoView"}],"url":"\/documentation\/skywayroom\/videoview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoView"}],"type":"topic","title":"VideoView","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView","abstract":[{"type":"text","text":"Videoを描画するView"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/VideoView/rendererView":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rendererView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"url":"\/documentation\/skywayroom\/videoview\/rendererview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rendererView"}],"type":"topic","title":"rendererView","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView\/rendererView","abstract":[{"type":"text","text":"映像をWrapしているレンダラービュー"}]},"doc://com.ntt.skyway.room/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusEnvironment"},"doc://com.ntt.skyway.room/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.ntt.skyway.room/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIAccessibilityIdentification"},"doc://com.ntt.skyway.room/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s23CustomStringConvertibleP"},"doc://com.ntt.skyway.room/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(cs)UIView"},"doc://com.ntt.skyway.room/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIAppearanceContainer"},"doc://com.ntt.skyway.room/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s16SendableMetatypeP"},"doc://com.ntt.skyway.room/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.ntt.skyway.room/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/s8SendableP"},"doc://com.ntt.skyway.room/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://com.ntt.skyway.room/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/SQ"},"doc://com.ntt.skyway.room/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)NSCoding"},"doc://com.ntt.skyway.room/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.ntt.skyway.room/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://com.ntt.skyway.room/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.ntt.skyway.room/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.ntt.skyway.room/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.ntt.skyway.room\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.ntt.skyway.room/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UIFocusItemContainer"},"doc://com.ntt.skyway.room/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.ntt.skyway.room\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.ntt.skyway.room/s7CVarArgP":{"identifier":"doc:\/\/com.ntt.skyway.room\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"SKWVideoView","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SKWVideoView","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SKWVideoView","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView\/rendererView","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView\/videoContentMode"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.ntt.skyway.room\/objc(cs)UIView"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWVideoView","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView~1videoContentMode\/title","value":"videoContentMode"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView~1videoContentMode\/fragments","value":[{"text":"videoContentMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView\/title","value":"SKWVideoView"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView\/fragments","value":[{"text":"SKWVideoView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView\/navigatorTitle","value":[{"kind":"identifier","text":"SKWVideoView"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView~1rendererView\/title","value":"rendererView","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView~1rendererView\/fragments","value":[{"text":"rendererView","kind":"identifier"}],"op":"replace"}]}]}