{"kind":"symbol","abstract":[{"text":"Roomを作成します。","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"InitOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/InitOptions","kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"SFURoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"初期化オプション"}]}],"name":"options"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"完了コールバック"}]}],"name":"completion"}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"codeVoice","code":"options"},{"type":"text","text":"でRoomの名前を指定して作成できますが、同じ名前のRoomは作成することができません。"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/skywayroom\/sfuroom\/create(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/sfuroom\/create(with:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"symbolKind":"method","title":"create(with:completion:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"SFURoom","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"createWith:completion:","kind":"identifier"}],"externalID":"c:@M@SkyWayRoom@objc(cs)SFURoom(cm)createWith:completion:","roleHeading":"Type Method","role":"symbol","modules":[{"name":"SkyWayRoom"}]},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom"]]},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/InitOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InitOptions","kind":"identifier"}],"url":"\/documentation\/skywayroom\/room\/initoptions","role":"symbol","navigatorTitle":[{"text":"InitOptions","kind":"identifier"}],"type":"topic","title":"Room.InitOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/InitOptions","abstract":[{"type":"text","text":"Room初期化オプション"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/InitOptions":{"url":"\/documentation\/skywayroom\/initoptions","type":"topic","abstract":[{"text":"Room初期化オプション","type":"text"}],"fragments":[{"text":"InitOptions","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/InitOptions","title":"InitOptions","kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/create(with:completion:)":{"kind":"symbol","title":"create(with:completion:)","abstract":[{"type":"text","text":"Roomを作成します。"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/create(with:completion:)","navigatorTitle":[{"kind":"identifier","text":"createWith:completion:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/create(with:completion:)"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom":{"url":"\/documentation\/skywayroom\/sfuroom","type":"topic","abstract":[{"text":"SFUサーバを介して通信を行うRoom","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFURoom","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","title":"SFURoom","navigatorTitle":[{"text":"SFURoom","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createWith:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWith:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"createWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"InitOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/InitOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)InitOptions"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"SFURoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"options","content":[{"inlineContent":[{"type":"text","text":"初期化オプション"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"完了コールバック"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"createWith:completion:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:completion:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWith:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1create(with:completion:)\/fragments"},{"op":"replace","value":"SFURoom","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/title"},{"op":"replace","value":[{"text":"SFURoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/fragments"},{"op":"replace","value":[{"text":"SFURoom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}