{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findOrCreate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/InitOptions","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sfuOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","text":"SFUBotPluginOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFUBotPluginOptions","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"style":"warning","type":"aside","content":[{"inlineContent":[{"text":"SkyWayRoom v3.1.0で非推奨となりました。","type":"text"}],"type":"paragraph"}],"name":"Warning"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/skywayroom\/sfuroom\/findorcreate(with:sfuoptions:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/sfuroom\/findorcreate(with:sfuoptions:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:sfuOptions:completion:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"SkyWayRoom v3.1.0で非推奨となりました。"}],"type":"paragraph"}],"metadata":{"symbolKind":"method","title":"findOrCreate(with:sfuOptions:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"findOrCreate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InitOptions","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sfuOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SFUBotPluginOptions","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"SFURoom","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"findOrCreateWith:sfuOptions:completion:","kind":"identifier"}],"externalID":"c:@M@SkyWayRoom@objc(cs)SFURoom(cm)findOrCreateWith:sfuOptions:completion:","role":"symbol","roleHeading":"Type Method","platforms":[{"unavailable":false,"beta":false,"deprecated":true,"message":"SkyWayRoom v3.1.0で非推奨となりました。"}],"modules":[{"name":"SkyWayRoom"}]},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom"]]},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/InitOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InitOptions","kind":"identifier"}],"url":"\/documentation\/skywayroom\/room\/initoptions","role":"symbol","navigatorTitle":[{"text":"InitOptions","kind":"identifier"}],"type":"topic","title":"Room.InitOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/InitOptions","abstract":[{"type":"text","text":"Room初期化オプション"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom":{"url":"\/documentation\/skywayroom\/sfuroom","type":"topic","abstract":[{"text":"SFUサーバを介して通信を行うRoom","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFURoom","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","title":"SFURoom","navigatorTitle":[{"text":"SFURoom","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/findOrCreate(with:sfuOptions:completion:)":{"kind":"symbol","title":"findOrCreate(with:sfuOptions:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findOrCreate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C11InitOptionsC","text":"InitOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sfuOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","text":"SFUBotPluginOptions"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","text":"SFURoom"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/findOrCreate(with:sfuOptions:completion:)","navigatorTitle":[{"kind":"identifier","text":"findOrCreateWith:sfuOptions:completion:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/sfuroom\/findorcreate(with:sfuoptions:completion:)","deprecated":true},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFUBotPluginOptions":{"url":"\/documentation\/skywayroom\/sfubotpluginoptions","navigatorTitle":[{"kind":"identifier","text":"SFUBotPluginOptions"}],"type":"topic","kind":"symbol","title":"SFUBotPluginOptions","abstract":[{"text":"SFUBotPluginオプション","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFUBotPluginOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFUBotPluginOptions"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/InitOptions":{"url":"\/documentation\/skywayroom\/initoptions","type":"topic","abstract":[{"text":"Room初期化オプション","type":"text"}],"fragments":[{"text":"InitOptions","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/InitOptions","title":"InitOptions","kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":true}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"findOrCreateWith:sfuOptions:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"findOrCreateWith:sfuOptions:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"findOrCreateWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"InitOptions","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)InitOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/InitOptions"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sfuOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKWSFUBotPluginOptions","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFUBotPluginOptions"},{"text":" *) ","kind":"text"},{"text":"sfuOptions","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"SFURoom","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":[{"type":"paragraph","inlineContent":[{"text":"SkyWayRoom v3.1.0で非推奨となりました。","type":"text"}]}],"path":"\/deprecationSummary"},{"op":"replace","value":"SFURoom","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SFURoom"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SFURoom"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/navigatorTitle"},{"op":"replace","value":"findOrCreateWith:sfuOptions:completion:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:sfuOptions:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"findOrCreateWith:sfuOptions:completion:"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1findOrCreate(with:sfuOptions:completion:)\/fragments"},{"op":"replace","value":"SKWSFUBotPluginOptions","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotPluginOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SKWSFUBotPluginOptions"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotPluginOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SKWSFUBotPluginOptions"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotPluginOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}