{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"find","kind":"identifier"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"query","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Query","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/Query","preciseIdentifier":"s:10SkyWayRoom0C0C5QueryC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sfuOption"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SFUBotPluginOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFUBotPluginOptions","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions"},{"kind":"text","text":"? = nil) "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"SFURoom","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"SkyWayRoom v3.1.0で非推奨となりました。"}],"type":"paragraph"}],"style":"warning","type":"aside","name":"Warning"}]}],"variants":[{"paths":["\/documentation\/skywayroom\/sfuroom\/find(by:sfuoption:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/sfuroom\/find(by:sfuoption:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:sfuOption:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"deprecationSummary":[{"inlineContent":[{"text":"SkyWayRoom v3.1.0で非推奨となりました。","type":"text"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom"]]},"metadata":{"roleHeading":"Type Method","platforms":[{"unavailable":false,"message":"SkyWayRoom v3.1.0で非推奨となりました。","beta":false,"deprecated":true}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"find","kind":"identifier"},{"kind":"text","text":"("},{"text":"by","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Query","kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C5QueryC"},{"text":", ","kind":"text"},{"text":"sfuOption","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SFUBotPluginOptions","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"SFURoom","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","kind":"typeIdentifier"}],"externalID":"c:@M@SkyWayRoom@objc(cs)SFURoom(cm)findBy:sfuOption:completionHandler:","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"findBy:sfuOption:completionHandler:","kind":"identifier"}],"title":"find(by:sfuOption:)","symbolKind":"method"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Query":{"kind":"symbol","fragments":[{"kind":"identifier","text":"Query"}],"url":"\/documentation\/skywayroom\/query","role":"symbol","type":"topic","title":"Query","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Query","abstract":[{"type":"text","text":"Room検索クエリ"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom/find(by:sfuOption:)":{"url":"\/documentation\/skywayroom\/sfuroom\/find(by:sfuoption:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"find","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"text":"Query","kind":"typeIdentifier","preciseIdentifier":"s:10SkyWayRoom0C0C5QueryC"},{"text":", ","kind":"text"},{"text":"sfuOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SFUBotPluginOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions"},{"kind":"text","text":"?) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"SFURoom","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom\/find(by:sfuOption:)","title":"find(by:sfuOption:)","navigatorTitle":[{"kind":"identifier","text":"findBy:sfuOption:completionHandler:"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room/Query":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Query"}],"url":"\/documentation\/skywayroom\/room\/query","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Query"}],"type":"topic","title":"Room.Query","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room\/Query","abstract":[{"type":"text","text":"Room検索クエリ"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFURoom":{"url":"\/documentation\/skywayroom\/sfuroom","type":"topic","abstract":[{"text":"SFUサーバを介して通信を行うRoom","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SFURoom","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","title":"SFURoom","navigatorTitle":[{"text":"SFURoom","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SFUBotPluginOptions":{"url":"\/documentation\/skywayroom\/sfubotpluginoptions","navigatorTitle":[{"kind":"identifier","text":"SFUBotPluginOptions"}],"type":"topic","kind":"symbol","title":"SFUBotPluginOptions","abstract":[{"text":"SFUBotPluginオプション","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFUBotPluginOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SFUBotPluginOptions"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"beta":false,"deprecated":true}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"findBy:sfuOption:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"findBy:sfuOption:completionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"findBy:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Query","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Query","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Query"},{"text":" *) ","kind":"text"},{"text":"query","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sfuOption:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKWSFUBotPluginOptions","preciseIdentifier":"c:objc(cs)SKWSFUBotPluginOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFUBotPluginOptions"},{"text":" *) ","kind":"text"},{"text":"sfuOption","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SFURoom","text":"SFURoom","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)SFURoom","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/deprecationSummary","op":"replace","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SkyWayRoom v3.1.0で非推奨となりました。"}]}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:sfuOption:)\/title","op":"replace","value":"findBy:sfuOption:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom~1find(by:sfuOption:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"findBy:sfuOption:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/title","value":"SFURoom"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/fragments","value":[{"kind":"identifier","text":"SFURoom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFURoom\/navigatorTitle","value":[{"text":"SFURoom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotPluginOptions\/title","value":"SKWSFUBotPluginOptions"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotPluginOptions\/fragments","op":"replace","value":[{"text":"SKWSFUBotPluginOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SFUBotPluginOptions\/navigatorTitle","value":[{"text":"SKWSFUBotPluginOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}