{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoGravity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVLayerVideoGravity","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVLayerVideoGravity"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"デフォルトは","type":"text"},{"code":"ResizeAspect","type":"codeVoice"},{"text":"がセットされます。","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/skywayroom\/camerapreviewview\/videogravity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/camerapreviewview\/videogravity"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"videoGravity","kind":"identifier"}],"title":"videoGravity","externalID":"c:objc(cs)SKWCameraPreviewView(py)videoGravity","symbolKind":"property","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoGravity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AVLayerVideoGravity","text":"AVLayerVideoGravity","kind":"typeIdentifier"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"映像の描画モード"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView\/videoGravity","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraPreviewView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewView","kind":"identifier"}],"url":"\/documentation\/skywayroom\/camerapreviewview","role":"symbol","navigatorTitle":[{"text":"CameraPreviewView","kind":"identifier"}],"type":"topic","title":"CameraPreviewView","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView","abstract":[{"type":"text","text":"カメラプレビュー用View"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraPreviewView/videoGravity":{"url":"\/documentation\/skywayroom\/camerapreviewview\/videogravity","navigatorTitle":[{"kind":"identifier","text":"videoGravity"}],"type":"topic","kind":"symbol","abstract":[{"text":"映像の描画モード","type":"text"}],"title":"videoGravity","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView\/videoGravity","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoGravity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVLayerVideoGravity","text":"AVLayerVideoGravity"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"videoGravity","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"videoGravity","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"AVLayerVideoGravity","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVLayerVideoGravity"},{"text":" ","kind":"text"},{"text":"videoGravity","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/title","value":"SKWCameraPreviewView","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/fragments","value":[{"text":"SKWCameraPreviewView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/navigatorTitle","value":[{"text":"SKWCameraPreviewView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView~1videoGravity\/title","value":"videoGravity","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView~1videoGravity\/fragments","value":[{"text":"videoGravity","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}