{
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/LocalPersonDelegate-Implementations"
  },
  "kind": "article",
  "metadata": {
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "LocalPersonDelegate Implementations"
  },
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember": {
      "abstract": [
        {
          "text": "RoomのLocalMember",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalRoomMember"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalRoomMember"
        }
      ],
      "role": "symbol",
      "title": "LocalRoomMember",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommember"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didPublishStreamOf:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPerson"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWLocalPerson",
          "text": "LocalPerson"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didPublishStreamOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didPublishStreamOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPerson:didPublishStreamOfPublication:"
        }
      ],
      "role": "symbol",
      "title": "localPerson(_:didPublishStreamOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommember/localperson(_:didpublishstreamof:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didSubscribePublicationOf:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPerson"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWLocalPerson",
          "text": "LocalPerson"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSubscribePublicationOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWSubscription",
          "text": "Subscription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didSubscribePublicationOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPerson:didSubscribePublicationOfSubscription:"
        }
      ],
      "role": "symbol",
      "title": "localPerson(_:didSubscribePublicationOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommember/localperson(_:didsubscribepublicationof:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didUnpublishStreamOf:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPerson"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWLocalPerson",
          "text": "LocalPerson"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUnpublishStreamOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWPublication",
          "text": "Publication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didUnpublishStreamOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPerson:didUnpublishStreamOfPublication:"
        }
      ],
      "role": "symbol",
      "title": "localPerson(_:didUnpublishStreamOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommember/localperson(_:didunpublishstreamof:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didUnsubscribePublicationOf:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localPerson"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWLocalPerson",
          "text": "LocalPerson"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUnsubscribePublicationOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SKWSubscription",
          "text": "Subscription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didUnsubscribePublicationOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localPerson:didUnsubscribePublicationOfSubscription:"
        }
      ],
      "role": "symbol",
      "title": "localPerson(_:didUnsubscribePublicationOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommember/localperson(_:didunsubscribepublicationof:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didPublishStreamOf:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didSubscribePublicationOf:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didUnpublishStreamOf:)",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didUnsubscribePublicationOf:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didPublishStreamOf:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didSubscribePublicationOf:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didUnpublishStreamOf:)",
                "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember/localPerson(_:didUnsubscribePublicationOf:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1localPerson(_:didUnsubscribePublicationOf:)/title",
          "value": "localPerson:didUnsubscribePublicationOfSubscription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1localPerson(_:didUnsubscribePublicationOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localPerson:didUnsubscribePublicationOfSubscription:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1localPerson(_:didPublishStreamOf:)/title",
          "value": "localPerson:didPublishStreamOfPublication:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1localPerson(_:didPublishStreamOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localPerson:didPublishStreamOfPublication:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1localPerson(_:didUnpublishStreamOf:)/title",
          "value": "localPerson:didUnpublishStreamOfPublication:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1localPerson(_:didUnpublishStreamOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localPerson:didUnpublishStreamOfPublication:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1localPerson(_:didSubscribePublicationOf:)/title",
          "value": "localPerson:didSubscribePublicationOfSubscription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember~1localPerson(_:didSubscribePublicationOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localPerson:didSubscribePublicationOfSubscription:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/title",
          "value": "LocalRoomMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMember"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/localroommember/localpersondelegate-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/localroommember/localpersondelegate-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
