{"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","title":"createStream()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createStream","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"LocalVideoStream","preciseIdentifier":"c:objc(cs)SKWLocalVideoStream","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"createStream"}],"externalID":"c:objc(cs)SKWCustomFrameVideoSource(im)createStream","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"SkyWayRoom"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Streamを作成します。","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createStream","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"LocalVideoStream","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalVideoStream","preciseIdentifier":"c:objc(cs)SKWLocalVideoStream"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Streamの作成後にキャプチャ開始でも機能します。","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/customframevideosource\/createstream()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/customframevideosource\/createstream()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/createStream()","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CustomFrameVideoSource":{"url":"\/documentation\/skywayroom\/customframevideosource","type":"topic","abstract":[{"type":"text","text":"画像フレームの映像入力ソース"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomFrameVideoSource","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource","title":"CustomFrameVideoSource","navigatorTitle":[{"text":"CustomFrameVideoSource","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CustomFrameVideoSource/createStream()":{"abstract":[{"type":"text","text":"Streamを作成します。"}],"title":"createStream()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createStream","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"LocalVideoStream","preciseIdentifier":"c:objc(cs)SKWLocalVideoStream","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CustomFrameVideoSource\/createStream()","navigatorTitle":[{"text":"createStream","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/customframevideosource\/createstream()","type":"topic"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalVideoStream":{"url":"\/documentation\/skywayroom\/localvideostream","navigatorTitle":[{"kind":"identifier","text":"LocalVideoStream"}],"type":"topic","kind":"symbol","title":"LocalVideoStream","abstract":[{"text":"LocalVideoStreamクラス","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalVideoStream","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalVideoStream"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createStream","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createStream"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalVideoStream","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWLocalVideoStream","text":"SKWLocalVideoStream"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createStream"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SKWCustomFrameVideoSource","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SKWCustomFrameVideoSource"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SKWCustomFrameVideoSource"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource\/navigatorTitle"},{"op":"replace","value":"createStream","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource~1createStream()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createStream"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CustomFrameVideoSource~1createStream()\/fragments"},{"op":"replace","value":"SKWLocalVideoStream","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalVideoStream\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SKWLocalVideoStream"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalVideoStream\/fragments"},{"op":"replace","value":[{"text":"SKWLocalVideoStream","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalVideoStream\/navigatorTitle"}]}]}