{"variants":[{"paths":["\/documentation\/skywayroom\/remoteroommember\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/remoteroommember\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"イベントデリゲート"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate","text":"RemoteRoomMemberDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(pl)RemoteRoomMemberDelegate"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember\/delegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(pl)RemoteRoomMemberDelegate","text":"RemoteRoomMemberDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@SkyWayRoom@objc(cs)RemoteRoomMember(py)delegate","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","symbolKind":"property"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember/delegate":{"url":"\/documentation\/skywayroom\/remoteroommember\/delegate","type":"topic","abstract":[{"text":"イベントデリゲート","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RemoteRoomMemberDelegate","preciseIdentifier":"c:@M@SkyWayRoom@objc(pl)RemoteRoomMemberDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember\/delegate","title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember":{"url":"\/documentation\/skywayroom\/remoteroommember","navigatorTitle":[{"kind":"identifier","text":"RemoteRoomMember"}],"type":"topic","kind":"symbol","title":"RemoteRoomMember","abstract":[{"text":"他のSDKで生成されたRoomMember","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RemoteRoomMember","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMemberDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"RemoteRoomMemberイベントデリゲート"}],"title":"RemoteRoomMemberDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteRoomMemberDelegate"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMemberDelegate","navigatorTitle":[{"kind":"identifier","text":"RemoteRoomMemberDelegate"}],"role":"symbol","url":"\/documentation\/skywayroom\/remoteroommemberdelegate","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"delegate","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SkyWayRoom@objc(pl)RemoteRoomMemberDelegate","text":"id<RemoteRoomMemberDelegate>"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/title","value":"RemoteRoomMember","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/fragments","value":[{"text":"RemoteRoomMember","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/navigatorTitle","value":[{"text":"RemoteRoomMember","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/title","op":"replace","value":"RemoteRoomMemberDelegate"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/fragments","value":[{"text":"RemoteRoomMemberDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMemberDelegate\/navigatorTitle","value":[{"text":"RemoteRoomMemberDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}