{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/remoteroommember\/memberdidleave(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/remoteroommember\/memberdidleave(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberDidLeave","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"member","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Member","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Member","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWMember"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:@CM@SkyWayRoom@objc(cs)RemoteRoomMember(im)memberDidLeave:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberDidLeave","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWMember","text":"Member","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","extendedModule":"SkyWayRoom","navigatorTitle":[{"text":"memberDidLeave:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"memberDidLeave(_:)"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember\/memberDidLeave(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"MemberDelegate.memberDidLeave(_:)"},{"text":".","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember/memberDidLeave(_:)":{"url":"\/documentation\/skywayroom\/remoteroommember\/memberdidleave(_:)","navigatorTitle":[{"kind":"identifier","text":"memberDidLeave:"}],"type":"topic","kind":"symbol","title":"memberDidLeave(_:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember\/memberDidLeave(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberDidLeave"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWMember","text":"Member"},{"kind":"text","text":")"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember":{"url":"\/documentation\/skywayroom\/remoteroommember","navigatorTitle":[{"kind":"identifier","text":"RemoteRoomMember"}],"type":"topic","kind":"symbol","title":"RemoteRoomMember","abstract":[{"text":"他のSDKで生成されたRoomMember","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RemoteRoomMember","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"url":"\/documentation\/skywayroom\/member","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Member"}],"type":"topic","title":"Member","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Member","abstract":[{"text":"Channelに入室しているMemberの抽象クラス","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"memberDidLeave:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"memberDidLeave:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"memberDidLeave:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Member","text":"SKWMember","preciseIdentifier":"c:objc(cs)SKWMember","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"member","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember~1memberDidLeave(_:)\/title","value":"memberDidLeave:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember~1memberDidLeave(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"memberDidLeave:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/title","value":"RemoteRoomMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/fragments","value":[{"text":"RemoteRoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/navigatorTitle","value":[{"text":"RemoteRoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member\/title","value":"SKWMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member\/fragments","value":[{"text":"SKWMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member\/navigatorTitle","value":[{"text":"SKWMember","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}