{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remotePerson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"remotePerson","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"RemotePerson","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemotePerson","preciseIdentifier":"c:objc(cs)SKWRemotePerson"},{"text":", ","kind":"text"},{"text":"didSubscribePublicationOf","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscription","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Subscription","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription","preciseIdentifier":"c:objc(cs)SKWSubscription"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/remoteroommember\/remoteperson(_:didsubscribepublicationof:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/remoteroommember\/remoteperson(_:didsubscribepublicationof:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"remotePerson:didSubscribePublicationOfSubscription:","kind":"identifier"}],"title":"remotePerson(_:didSubscribePublicationOf:)","extendedModule":"SkyWayRoom","externalID":"c:@CM@SkyWayRoom@objc(cs)RemoteRoomMember(im)remotePerson:didSubscribePublicationOfSubscription:","symbolKind":"method","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remotePerson"},{"kind":"text","text":"("},{"text":"RemotePerson","preciseIdentifier":"c:objc(cs)SKWRemotePerson","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSubscribePublicationOf"},{"kind":"text","text":": "},{"text":"Subscription","preciseIdentifier":"c:objc(cs)SKWSubscription","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"RemotePersonDelegate.remotePerson(_:didSubscribePublicationOf:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember\/remotePerson(_:didSubscribePublicationOf:)","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemotePerson":{"url":"\/documentation\/skywayroom\/remoteperson","navigatorTitle":[{"kind":"identifier","text":"RemotePerson"}],"type":"topic","kind":"symbol","abstract":[],"title":"RemotePerson","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemotePerson","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemotePerson"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember/remotePerson(_:didSubscribePublicationOf:)":{"url":"\/documentation\/skywayroom\/remoteroommember\/remoteperson(_:didsubscribepublicationof:)","navigatorTitle":[{"kind":"identifier","text":"remotePerson:didSubscribePublicationOfSubscription:"}],"type":"topic","kind":"symbol","title":"remotePerson(_:didSubscribePublicationOf:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember\/remotePerson(_:didSubscribePublicationOf:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remotePerson"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RemotePerson","preciseIdentifier":"c:objc(cs)SKWRemotePerson"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSubscribePublicationOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Subscription","preciseIdentifier":"c:objc(cs)SKWSubscription"},{"kind":"text","text":")"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Subscription":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Subscription","kind":"identifier"}],"url":"\/documentation\/skywayroom\/subscription","role":"symbol","navigatorTitle":[{"text":"Subscription","kind":"identifier"}],"type":"topic","title":"Subscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription","abstract":[{"type":"text","text":"SubscriptionはLocalMemberがSubscribeした時に取得でき、Subscriptionに含まれるStreamを利用して映像を描画したりします。"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember":{"url":"\/documentation\/skywayroom\/remoteroommember","navigatorTitle":[{"kind":"identifier","text":"RemoteRoomMember"}],"type":"topic","kind":"symbol","title":"RemoteRoomMember","abstract":[{"text":"他のSDKで生成されたRoomMember","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RemoteRoomMember","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"remotePerson:didSubscribePublicationOfSubscription:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"remotePerson:didSubscribePublicationOfSubscription:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"remotePerson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWRemotePerson","text":"SKWRemotePerson","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemotePerson"},{"text":" *) ","kind":"text"},{"text":"remotePerson","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didSubscribePublicationOfSubscription:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWSubscription","text":"SKWSubscription","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription"},{"text":" *) ","kind":"text"},{"text":"subscription","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SKWRemotePerson","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePerson\/title","op":"replace"},{"value":[{"text":"SKWRemotePerson","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePerson\/fragments","op":"replace"},{"value":[{"text":"SKWRemotePerson","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePerson\/navigatorTitle","op":"replace"},{"value":"remotePerson:didSubscribePublicationOfSubscription:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember~1remotePerson(_:didSubscribePublicationOf:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"remotePerson:didSubscribePublicationOfSubscription:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember~1remotePerson(_:didSubscribePublicationOf:)\/fragments","op":"replace"},{"value":"SKWSubscription","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/title","op":"replace"},{"value":[{"text":"SKWSubscription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/fragments","op":"replace"},{"value":[{"text":"SKWSubscription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/navigatorTitle","op":"replace"},{"value":"RemoteRoomMember","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/title","op":"replace"},{"value":[{"text":"RemoteRoomMember","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/fragments","op":"replace"},{"value":[{"text":"RemoteRoomMember","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}