{"variants":[{"paths":["\/documentation\/skywayroom\/remoteroommember\/remoteperson(_:didunsubscribepublicationof:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/remoteroommember\/remoteperson(_:didunsubscribepublicationof:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RemotePersonDelegate.remotePerson(_:didUnsubscribePublicationOf:)"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remotePerson","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"remotePerson","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"RemotePerson","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemotePerson","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWRemotePerson"},{"text":", ","kind":"text"},{"text":"didUnsubscribePublicationOf","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscription","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Subscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSubscription"},{"text":")","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember\/remotePerson(_:didUnsubscribePublicationOf:)"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remotePerson"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"RemotePerson","preciseIdentifier":"c:objc(cs)SKWRemotePerson"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUnsubscribePublicationOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Subscription","preciseIdentifier":"c:objc(cs)SKWSubscription"},{"kind":"text","text":")"}],"extendedModule":"SkyWayRoom","externalID":"c:@CM@SkyWayRoom@objc(cs)RemoteRoomMember(im)remotePerson:didUnsubscribePublicationOfSubscription:","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"kind":"identifier","text":"remotePerson:didUnsubscribePublicationOfSubscription:"}],"title":"remotePerson(_:didUnsubscribePublicationOf:)","symbolKind":"method"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Subscription":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Subscription","kind":"identifier"}],"url":"\/documentation\/skywayroom\/subscription","role":"symbol","navigatorTitle":[{"text":"Subscription","kind":"identifier"}],"type":"topic","title":"Subscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription","abstract":[{"type":"text","text":"SubscriptionはLocalMemberがSubscribeした時に取得でき、Subscriptionに含まれるStreamを利用して映像を描画したりします。"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemotePerson":{"url":"\/documentation\/skywayroom\/remoteperson","navigatorTitle":[{"kind":"identifier","text":"RemotePerson"}],"type":"topic","kind":"symbol","abstract":[],"title":"RemotePerson","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemotePerson","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemotePerson"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember/remotePerson(_:didUnsubscribePublicationOf:)":{"url":"\/documentation\/skywayroom\/remoteroommember\/remoteperson(_:didunsubscribepublicationof:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remotePerson"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWRemotePerson","text":"RemotePerson"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUnsubscribePublicationOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWSubscription","text":"Subscription"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember\/remotePerson(_:didUnsubscribePublicationOf:)","title":"remotePerson(_:didUnsubscribePublicationOf:)","navigatorTitle":[{"kind":"identifier","text":"remotePerson:didUnsubscribePublicationOfSubscription:"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteRoomMember":{"url":"\/documentation\/skywayroom\/remoteroommember","navigatorTitle":[{"kind":"identifier","text":"RemoteRoomMember"}],"type":"topic","kind":"symbol","title":"RemoteRoomMember","abstract":[{"text":"他のSDKで生成されたRoomMember","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteRoomMember","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RemoteRoomMember","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"remotePerson:didUnsubscribePublicationOfSubscription:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"remotePerson:didUnsubscribePublicationOfSubscription:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"remotePerson:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWRemotePerson","text":"SKWRemotePerson","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemotePerson","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"remotePerson","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUnsubscribePublicationOfSubscription:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWSubscription","text":"SKWSubscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Subscription","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"subscription","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/title","value":"SKWSubscription"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/fragments","value":[{"text":"SKWSubscription","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Subscription\/navigatorTitle","value":[{"text":"SKWSubscription","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePerson\/title","value":"SKWRemotePerson"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePerson\/fragments","value":[{"text":"SKWRemotePerson","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemotePerson\/navigatorTitle","value":[{"text":"SKWRemotePerson","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember~1remotePerson(_:didUnsubscribePublicationOf:)\/title","value":"remotePerson:didUnsubscribePublicationOfSubscription:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember~1remotePerson(_:didUnsubscribePublicationOf:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"remotePerson:didUnsubscribePublicationOfSubscription:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/title","value":"RemoteRoomMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/fragments","value":[{"text":"RemoteRoomMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteRoomMember\/navigatorTitle","value":[{"text":"RemoteRoomMember","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}