{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iceParams","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams","text":"ContextOptionsICEParams","preciseIdentifier":"c:objc(cs)SKWContextOptionsICEParams","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/skywayroom\/contextoptions\/iceparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/contextoptions\/iceparams"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"iceParams","kind":"identifier"}],"title":"iceParams","externalID":"c:objc(cs)SKWContextOptions(py)iceParams","symbolKind":"property","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"iceParams","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContextOptionsICEParams","preciseIdentifier":"c:objc(cs)SKWContextOptionsICEParams"}]},"sections":[],"kind":"symbol","abstract":[{"text":"内部向けオプション","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions\/iceParams","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptions/iceParams":{"url":"\/documentation\/skywayroom\/contextoptions\/iceparams","navigatorTitle":[{"text":"iceParams","kind":"identifier"}],"type":"topic","kind":"symbol","title":"iceParams","abstract":[{"text":"内部向けオプション","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions\/iceParams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iceParams","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContextOptionsICEParams","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWContextOptionsICEParams"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptions","kind":"identifier"}],"url":"\/documentation\/skywayroom\/contextoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContextOptions"}],"type":"topic","title":"ContextOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions","abstract":[{"type":"text","text":"コンテキストの初期化オプション"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsICEParams":{"url":"\/documentation\/skywayroom\/contextoptionsiceparams","navigatorTitle":[{"text":"ContextOptionsICEParams","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ContextOptionsICEParams","abstract":[{"text":"内部向けオプション","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptionsICEParams","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"iceParams"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"iceParams"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SKWContextOptionsICEParams","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsICEParams","preciseIdentifier":"c:objc(cs)SKWContextOptionsICEParams"},{"text":" * ","kind":"text"},{"text":"iceParams","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions~1iceParams\/title","value":"iceParams"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions~1iceParams\/fragments","value":[{"kind":"identifier","text":"iceParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/title","value":"SKWContextOptions"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/fragments","value":[{"kind":"identifier","text":"SKWContextOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SKWContextOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams\/title","value":"SKWContextOptionsICEParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams\/fragments","value":[{"kind":"identifier","text":"SKWContextOptionsICEParams"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsICEParams\/navigatorTitle","value":[{"text":"SKWContextOptionsICEParams","kind":"identifier"}],"op":"replace"}]}]}