{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/contextoptions\/rtcconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/contextoptions\/rtcconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcConfig"},{"kind":"text","text":": "},{"text":"ContextOptionsRTCConfig","preciseIdentifier":"c:objc(cs)SKWContextOptionsRTCConfig","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsRTCConfig"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:objc(cs)SKWContextOptions(py)rtcConfig","modules":[{"name":"SkyWayRoom"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rtcConfig","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWContextOptionsRTCConfig","text":"ContextOptionsRTCConfig","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rtcConfig"}],"roleHeading":"Instance Property","symbolKind":"property","title":"rtcConfig"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions\/rtcConfig","interfaceLanguage":"swift"},"abstract":[{"text":"WebRTCに関するオプション","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptions","kind":"identifier"}],"url":"\/documentation\/skywayroom\/contextoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContextOptions"}],"type":"topic","title":"ContextOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions","abstract":[{"type":"text","text":"コンテキストの初期化オプション"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptions/rtcConfig":{"url":"\/documentation\/skywayroom\/contextoptions\/rtcconfig","navigatorTitle":[{"text":"rtcConfig","kind":"identifier"}],"type":"topic","kind":"symbol","title":"rtcConfig","abstract":[{"text":"WebRTCに関するオプション","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions\/rtcConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWContextOptionsRTCConfig","text":"ContextOptionsRTCConfig"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsRTCConfig":{"title":"ContextOptionsRTCConfig","abstract":[{"text":"WebRTCに関するオプション","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContextOptionsRTCConfig"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsRTCConfig","navigatorTitle":[{"text":"ContextOptionsRTCConfig","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/contextoptionsrtcconfig","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"rtcConfig","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rtcConfig"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SKWContextOptionsRTCConfig","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsRTCConfig","preciseIdentifier":"c:objc(cs)SKWContextOptionsRTCConfig"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rtcConfig"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/title","value":"SKWContextOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/fragments","value":[{"kind":"identifier","text":"SKWContextOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SKWContextOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions~1rtcConfig\/title","value":"rtcConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions~1rtcConfig\/fragments","value":[{"kind":"identifier","text":"rtcConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsRTCConfig\/title","value":"SKWContextOptionsRTCConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsRTCConfig\/fragments","value":[{"kind":"identifier","text":"SKWContextOptionsRTCConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsRTCConfig\/navigatorTitle","value":[{"kind":"identifier","text":"SKWContextOptionsRTCConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}