{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/contextoptions\/signaling"]},{"paths":["\/documentation\/skywayroom\/contextoptions\/signaling"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"内部向けオプション"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"signaling"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWContextOptionsSignaling","text":"ContextOptionsSignaling","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsSignaling","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions\/signaling","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"signaling","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContextOptionsSignaling","preciseIdentifier":"c:objc(cs)SKWContextOptionsSignaling","kind":"typeIdentifier"}],"externalID":"c:objc(cs)SKWContextOptions(py)signaling","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"kind":"identifier","text":"signaling"}],"title":"signaling","symbolKind":"property"},"kind":"symbol","references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptions/signaling":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"signaling"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWContextOptionsSignaling","text":"ContextOptionsSignaling"}],"url":"\/documentation\/skywayroom\/contextoptions\/signaling","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"signaling"}],"type":"topic","title":"signaling","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions\/signaling","abstract":[{"text":"内部向けオプション","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptions":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContextOptions","kind":"identifier"}],"url":"\/documentation\/skywayroom\/contextoptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContextOptions"}],"type":"topic","title":"ContextOptions","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptions","abstract":[{"type":"text","text":"コンテキストの初期化オプション"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ContextOptionsSignaling":{"url":"\/documentation\/skywayroom\/contextoptionssignaling","navigatorTitle":[{"kind":"identifier","text":"ContextOptionsSignaling"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"内部向けオプション"}],"title":"ContextOptionsSignaling","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsSignaling","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContextOptionsSignaling"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"signaling"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"signaling","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SKWContextOptionsSignaling","preciseIdentifier":"c:objc(cs)SKWContextOptionsSignaling","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ContextOptionsSignaling"},{"text":" * ","kind":"text"},{"text":"signaling","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions~1signaling\/title","value":"signaling"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions~1signaling\/fragments","value":[{"text":"signaling","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/title","value":"SKWContextOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/fragments","value":[{"text":"SKWContextOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptions\/navigatorTitle","op":"replace","value":[{"text":"SKWContextOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsSignaling\/title","op":"replace","value":"SKWContextOptionsSignaling"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsSignaling\/fragments","op":"replace","value":[{"text":"SKWContextOptionsSignaling","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ContextOptionsSignaling\/navigatorTitle","op":"replace","value":[{"text":"SKWContextOptionsSignaling","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}