{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWLocalDataStream","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream","text":"LocalDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBecomeUnwritableFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/DataStreamSubscriber","text":"DataStreamSubscriber","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"対象のDataStream"}]}],"name":"dataStream"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"データ送信が不可能になったサブスクライバー"}]}],"name":"subscriber"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/skywayroom\/localdatastreamdelegate\/datastream(_:didbecomeunwritablefor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/localdatastreamdelegate\/datastream(_:didbecomeunwritablefor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"dataStream:didBecomeUnwritableForSubscriber:"}],"title":"dataStream(_:didBecomeUnwritableFor:)","externalID":"c:objc(pl)SKWLocalDataStreamDelegate(im)dataStream:didBecomeUnwritableForSubscriber:","symbolKind":"method","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LocalDataStream","preciseIdentifier":"c:objc(cs)SKWLocalDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBecomeUnwritableFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DataStreamSubscriber","preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","sections":[],"abstract":[{"text":"データ送信が不可能になった時にコールされるイベント","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeUnwritableFor:)","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStreamDelegate":{"url":"\/documentation\/skywayroom\/localdatastreamdelegate","type":"topic","abstract":[{"text":"LocalDataStreamイベントデリゲート","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStreamDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate","title":"LocalDataStreamDelegate","navigatorTitle":[{"text":"LocalDataStreamDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/DataStreamSubscriber":{"url":"\/documentation\/skywayroom\/datastreamsubscriber","navigatorTitle":[{"kind":"identifier","text":"DataStreamSubscriber"}],"type":"topic","kind":"symbol","title":"DataStreamSubscriber","abstract":[{"type":"text","text":"DataStreamのサブスクライバー情報"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/DataStreamSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataStreamSubscriber"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStream":{"title":"LocalDataStream","abstract":[{"text":"LocalDataStreamクラス","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStream","kind":"identifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream","navigatorTitle":[{"text":"LocalDataStream","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/localdatastream","type":"topic"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStreamDelegate/dataStream(_:didBecomeUnwritableFor:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LocalDataStream","preciseIdentifier":"c:objc(cs)SKWLocalDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBecomeUnwritableFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DataStreamSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/localdatastreamdelegate\/datastream(_:didbecomeunwritablefor:)","role":"symbol","navigatorTitle":[{"text":"dataStream:didBecomeUnwritableForSubscriber:","kind":"identifier"}],"type":"topic","title":"dataStream(_:didBecomeUnwritableFor:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeUnwritableFor:)","abstract":[{"type":"text","text":"データ送信が不可能になった時にコールされるイベント"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dataStream:didBecomeUnwritableForSubscriber:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dataStream:didBecomeUnwritableForSubscriber:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"dataStream:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWLocalDataStream","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream","text":"SKWLocalDataStream","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dataStream","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didBecomeUnwritableForSubscriber:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber","text":"SKWDataStreamSubscriber","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/DataStreamSubscriber"},{"text":" *) ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"dataStream","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"対象のDataStream"}]}]},{"name":"subscriber","content":[{"type":"paragraph","inlineContent":[{"text":"データ送信が不可能になったサブスクライバー","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/title","value":"SKWLocalDataStreamDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/fragments","value":[{"text":"SKWLocalDataStreamDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/navigatorTitle","value":[{"text":"SKWLocalDataStreamDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1DataStreamSubscriber\/title","value":"SKWDataStreamSubscriber"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1DataStreamSubscriber\/fragments","value":[{"text":"SKWDataStreamSubscriber","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1DataStreamSubscriber\/navigatorTitle","value":[{"kind":"identifier","text":"SKWDataStreamSubscriber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/title","value":"SKWLocalDataStream"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/fragments","value":[{"text":"SKWLocalDataStream","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/navigatorTitle","value":[{"text":"SKWLocalDataStream","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate~1dataStream(_:didBecomeUnwritableFor:)\/title","op":"replace","value":"dataStream:didBecomeUnwritableForSubscriber:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate~1dataStream(_:didBecomeUnwritableFor:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataStream:didBecomeUnwritableForSubscriber:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}