{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/localdatastreamdelegate\/datastream(_:didbecomewritablefor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/localdatastreamdelegate\/datastream(_:didbecomewritablefor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"LocalDataStream","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream","preciseIdentifier":"c:objc(cs)SKWLocalDataStream"},{"text":", ","kind":"text"},{"text":"didBecomeWritableFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/DataStreamSubscriber","text":"DataStreamSubscriber","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"対象のDataStream","type":"text"}]}],"name":"dataStream"},{"content":[{"type":"paragraph","inlineContent":[{"text":"データ送信が可能になったサブスクライバー","type":"text"}]}],"name":"subscriber"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWLocalDataStream","text":"LocalDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBecomeWritableFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DataStreamSubscriber","preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)SKWLocalDataStreamDelegate(im)dataStream:didBecomeWritableForSubscriber:","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"dataStream:didBecomeWritableForSubscriber:","kind":"identifier"}],"title":"dataStream(_:didBecomeWritableFor:)","symbolKind":"method"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeWritableFor:)","interfaceLanguage":"swift"},"abstract":[{"text":"データ送信が可能になった時にコールされるイベント","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStreamDelegate":{"url":"\/documentation\/skywayroom\/localdatastreamdelegate","type":"topic","abstract":[{"text":"LocalDataStreamイベントデリゲート","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStreamDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate","title":"LocalDataStreamDelegate","navigatorTitle":[{"text":"LocalDataStreamDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStreamDelegate/dataStream(_:didBecomeWritableFor:)":{"url":"\/documentation\/skywayroom\/localdatastreamdelegate\/datastream(_:didbecomewritablefor:)","navigatorTitle":[{"text":"dataStream:didBecomeWritableForSubscriber:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"dataStream(_:didBecomeWritableFor:)","abstract":[{"text":"データ送信が可能になった時にコールされるイベント","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStreamDelegate\/dataStream(_:didBecomeWritableFor:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWLocalDataStream","text":"LocalDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didBecomeWritableFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DataStreamSubscriber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber"},{"text":")","kind":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/DataStreamSubscriber":{"url":"\/documentation\/skywayroom\/datastreamsubscriber","navigatorTitle":[{"kind":"identifier","text":"DataStreamSubscriber"}],"type":"topic","kind":"symbol","title":"DataStreamSubscriber","abstract":[{"type":"text","text":"DataStreamのサブスクライバー情報"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/DataStreamSubscriber","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataStreamSubscriber"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalDataStream":{"title":"LocalDataStream","abstract":[{"text":"LocalDataStreamクラス","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LocalDataStream","kind":"identifier"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream","navigatorTitle":[{"text":"LocalDataStream","kind":"identifier"}],"role":"symbol","url":"\/documentation\/skywayroom\/localdatastream","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dataStream:didBecomeWritableForSubscriber:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dataStream:didBecomeWritableForSubscriber:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"dataStream:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalDataStream","text":"SKWLocalDataStream","preciseIdentifier":"c:objc(cs)SKWLocalDataStream","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dataStream","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didBecomeWritableForSubscriber:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/DataStreamSubscriber","text":"SKWDataStreamSubscriber","preciseIdentifier":"c:objc(cs)SKWDataStreamSubscriber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"subscriber","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"dataStream","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"対象のDataStream"}]}]},{"name":"subscriber","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"データ送信が可能になったサブスクライバー"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SKWLocalDataStreamDelegate","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/title"},{"op":"replace","value":[{"text":"SKWLocalDataStreamDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/fragments"},{"op":"replace","value":[{"text":"SKWLocalDataStreamDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate\/navigatorTitle"},{"op":"replace","value":"dataStream:didBecomeWritableForSubscriber:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate~1dataStream(_:didBecomeWritableFor:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dataStream:didBecomeWritableForSubscriber:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStreamDelegate~1dataStream(_:didBecomeWritableFor:)\/fragments"},{"op":"replace","value":"SKWDataStreamSubscriber","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1DataStreamSubscriber\/title"},{"op":"replace","value":[{"text":"SKWDataStreamSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1DataStreamSubscriber\/fragments"},{"op":"replace","value":[{"text":"SKWDataStreamSubscriber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1DataStreamSubscriber\/navigatorTitle"},{"op":"replace","value":"SKWLocalDataStream","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/title"},{"op":"replace","value":[{"text":"SKWLocalDataStream","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/fragments"},{"op":"replace","value":[{"text":"SKWLocalDataStream","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalDataStream\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}