{"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoStreamProtocol"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"required":true,"modules":[{"name":"SkyWayRoom"}],"roleHeading":"Instance Method","title":"detach(_:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detach","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoView","preciseIdentifier":"c:objc(cs)SKWVideoView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"detachView:","kind":"identifier"}],"externalID":"c:objc(pl)SKWVideoStreamProtocol(im)detachView:"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detach","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"VideoView","preciseIdentifier":"c:objc(cs)SKWVideoView","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/videostreamprotocol\/detach(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/videostreamprotocol\/detach(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoStreamProtocol\/detach(_:)","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/VideoStreamProtocol":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoStreamProtocol","kind":"identifier"}],"url":"\/documentation\/skywayroom\/videostreamprotocol","role":"symbol","navigatorTitle":[{"text":"VideoStreamProtocol","kind":"identifier"}],"type":"topic","title":"VideoStreamProtocol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoStreamProtocol","abstract":[{"type":"text","text":"VideoStreamProtocol"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/VideoStreamProtocol/detach(_:)":{"abstract":[],"kind":"symbol","title":"detach(_:)","required":true,"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoStreamProtocol\/detach(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detach","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VideoView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWVideoView"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/skywayroom\/videostreamprotocol\/detach(_:)","type":"topic","navigatorTitle":[{"text":"detachView:","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/VideoView":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoView"}],"url":"\/documentation\/skywayroom\/videoview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoView"}],"type":"topic","title":"VideoView","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView","abstract":[{"type":"text","text":"Videoを描画するView"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"detachView:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detachView:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"detachView:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/VideoView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWVideoView","text":"SKWVideoView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoStreamProtocol\/title","op":"replace","value":"SKWVideoStreamProtocol"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoStreamProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"SKWVideoStreamProtocol"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoStreamProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SKWVideoStreamProtocol"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoStreamProtocol~1detach(_:)\/title","op":"replace","value":"detachView:"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoStreamProtocol~1detach(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detachView:"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView\/title","op":"replace","value":"SKWVideoView"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView\/fragments","op":"replace","value":[{"kind":"identifier","text":"SKWVideoView"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VideoView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SKWVideoView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}