{"variants":[{"paths":["\/documentation\/skywayroom\/side\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"SkyWayRoom"}],"title":"Equatable Implementations"},"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Side"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Side\/!=(_:_:)"],"anchor":"Operators","generated":true}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Side\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Side":{"url":"\/documentation\/skywayroom\/side","navigatorTitle":[{"kind":"identifier","text":"Side"}],"type":"topic","kind":"symbol","title":"Side","abstract":[{"text":"サイド","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Side","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Side"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Side/!=(_:_:)":{"url":"\/documentation\/skywayroom\/side\/!=(_:_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Side\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Side\/title","value":"SKWSide","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Side\/fragments","value":[{"text":"SKWSide","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Side\/navigatorTitle","value":[{"kind":"identifier","text":"SKWSide"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}