{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localPersonSubscribeError","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/skywayroom\/skwerrorfactory\/localpersonsubscribeerror()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/skwerrorfactory\/localpersonsubscribeerror()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)SKWErrorFactory(cm)localPersonSubscribeError","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localPersonSubscribeError"},{"kind":"text","text":"() -> any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"localPersonSubscribeError","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","title":"localPersonSubscribeError()"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorFactory"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorFactory\/localPersonSubscribeError()","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory/localPersonSubscribeError()":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localPersonSubscribeError","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"url":"\/documentation\/skywayroom\/skwerrorfactory\/localpersonsubscribeerror()","role":"symbol","navigatorTitle":[{"text":"localPersonSubscribeError","kind":"identifier"}],"type":"topic","title":"localPersonSubscribeError()","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorFactory\/localPersonSubscribeError()","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWErrorFactory":{"url":"\/documentation\/skywayroom\/skwerrorfactory","type":"topic","abstract":[{"text":"エラーファクトリー","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKWErrorFactory","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWErrorFactory","title":"SKWErrorFactory","navigatorTitle":[{"text":"SKWErrorFactory","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"localPersonSubscribeError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"localPersonSubscribeError","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"localPersonSubscribeError","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonSubscribeError()\/title","value":"localPersonSubscribeError","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory~1localPersonSubscribeError()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"localPersonSubscribeError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory\/title","value":"SKWErrorFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory\/fragments","value":[{"text":"SKWErrorFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWErrorFactory\/navigatorTitle","value":[{"text":"SKWErrorFactory","kind":"identifier"}]}]}]}