{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/roomdelegate\/room(_:publicationdidchangetodisabled:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/roomdelegate\/room(_:publicationdidchangetodisabled:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"room","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"room","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room","text":"Room","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"publicationDidChangeToDisabled","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"publication","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication","text":"RoomPublication","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"room","content":[{"type":"paragraph","inlineContent":[{"text":"Room","type":"text"}]}]},{"name":"publication","content":[{"type":"paragraph","inlineContent":[{"text":"対象のPublication","type":"text"}]}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomDelegate"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:@M@SkyWayRoom@objc(pl)RoomDelegate(im)room:publicationDidChangeToDisabled:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"room","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room","text":"Room","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"publicationDidChangeToDisabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication","text":"RoomPublication","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"room:publicationDidChangeToDisabled:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"room(_:publicationDidChangeToDisabled:)"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomDelegate\/room(_:publicationDidChangeToDisabled:)","interfaceLanguage":"swift"},"abstract":[{"text":"このRoomのPublicationが","type":"text"},{"type":"codeVoice","code":"Disabled"},{"text":"状態に変更された後に発生するイベント","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Room"}],"url":"\/documentation\/skywayroom\/room","role":"symbol","navigatorTitle":[{"text":"Room","kind":"identifier"}],"type":"topic","title":"Room","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room","abstract":[{"text":"Roomクラス","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomDelegate":{"url":"\/documentation\/skywayroom\/roomdelegate","navigatorTitle":[{"kind":"identifier","text":"RoomDelegate"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Roomイベントデリゲート"}],"title":"RoomDelegate","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomDelegate"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomPublication":{"url":"\/documentation\/skywayroom\/roompublication","type":"topic","abstract":[{"type":"text","text":"Room SDKにおけるPublication"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomPublication"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication","title":"RoomPublication","navigatorTitle":[{"kind":"identifier","text":"RoomPublication"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomDelegate/room(_:publicationDidChangeToDisabled:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"room"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Room","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publicationDidChangeToDisabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomPublication","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication"},{"kind":"text","text":")"}],"url":"\/documentation\/skywayroom\/roomdelegate\/room(_:publicationdidchangetodisabled:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"room:publicationDidChangeToDisabled:"}],"type":"topic","title":"room(_:publicationDidChangeToDisabled:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomDelegate\/room(_:publicationDidChangeToDisabled:)","abstract":[{"text":"このRoomのPublicationが","type":"text"},{"type":"codeVoice","code":"Disabled"},{"text":"状態に変更された後に発生するイベント","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"room:publicationDidChangeToDisabled:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"room:publicationDidChangeToDisabled:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"room:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Room","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room"},{"text":" *) ","kind":"text"},{"text":"room","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"publicationDidChangeToDisabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RoomPublication","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomPublication","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomPublication"},{"text":" *) ","kind":"text"},{"text":"publication","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"room","content":[{"inlineContent":[{"text":"Room","type":"text"}],"type":"paragraph"}]},{"name":"publication","content":[{"inlineContent":[{"text":"対象のPublication","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/title","op":"replace","value":"Room"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/fragments","op":"replace","value":[{"text":"Room","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/navigatorTitle","op":"replace","value":[{"text":"Room","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate\/title","op":"replace","value":"RoomDelegate"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate\/fragments","op":"replace","value":[{"text":"RoomDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate\/navigatorTitle","op":"replace","value":[{"text":"RoomDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/title","op":"replace","value":"RoomPublication"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/fragments","op":"replace","value":[{"text":"RoomPublication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomPublication\/navigatorTitle","op":"replace","value":[{"text":"RoomPublication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate~1room(_:publicationDidChangeToDisabled:)\/title","op":"replace","value":"room:publicationDidChangeToDisabled:"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate~1room(_:publicationDidChangeToDisabled:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"room:publicationDidChangeToDisabled:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}