{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/roomdelegate\/room(_:didsubscribepublicationof:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/roomdelegate\/room(_:didsubscribepublicationof:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"room","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"room","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Room","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room"},{"text":", ","kind":"text"},{"text":"didSubscribePublicationOf","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"subscription","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"room","content":[{"inlineContent":[{"type":"text","text":"Room"}],"type":"paragraph"}]},{"name":"subscription","content":[{"inlineContent":[{"type":"text","text":"対象のSubscription LocalRoomMemberによるSubscribeである場合、まだstreamがsetされていない可能性があります。"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:@M@SkyWayRoom@objc(pl)RoomDelegate(im)room:didSubscribePublicationOf:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"room","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Room","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSubscribePublicationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"room:didSubscribePublicationOf:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"room(_:didSubscribePublicationOf:)"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomDelegate"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomDelegate\/room(_:didSubscribePublicationOf:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"PublicationがSubscribeされた後にコールされるイベント"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Room":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Room"}],"url":"\/documentation\/skywayroom\/room","role":"symbol","navigatorTitle":[{"text":"Room","kind":"identifier"}],"type":"topic","title":"Room","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room","abstract":[{"text":"Roomクラス","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscription":{"url":"\/documentation\/skywayroom\/roomsubscription","navigatorTitle":[{"kind":"identifier","text":"RoomSubscription"}],"type":"topic","kind":"symbol","title":"RoomSubscription","abstract":[{"text":"Room SDK におけるSubscription","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RoomSubscription","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomDelegate/room(_:didSubscribePublicationOf:)":{"url":"\/documentation\/skywayroom\/roomdelegate\/room(_:didsubscribepublicationof:)","type":"topic","abstract":[{"type":"text","text":"PublicationがSubscribeされた後にコールされるイベント"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"room","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room","text":"Room"},{"kind":"text","text":", "},{"text":"didSubscribePublicationOf","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","text":"RoomSubscription","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomDelegate\/room(_:didSubscribePublicationOf:)","title":"room(_:didSubscribePublicationOf:)","navigatorTitle":[{"kind":"identifier","text":"room:didSubscribePublicationOf:"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomDelegate":{"url":"\/documentation\/skywayroom\/roomdelegate","navigatorTitle":[{"kind":"identifier","text":"RoomDelegate"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Roomイベントデリゲート"}],"title":"RoomDelegate","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RoomDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"room:didSubscribePublicationOf:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"room:didSubscribePublicationOf:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"room:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Room","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Room","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)Room"},{"text":" *) ","kind":"text"},{"text":"room","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didSubscribePublicationOf:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","text":"RoomSubscription","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription"},{"text":" *) ","kind":"text"},{"text":"subscription","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Room","type":"text"}],"type":"paragraph"}],"name":"room"},{"content":[{"type":"paragraph","inlineContent":[{"text":"対象のSubscription LocalRoomMemberによるSubscribeである場合、まだstreamがsetされていない可能性があります。","type":"text"}]}],"name":"subscription"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/title","value":"Room","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/fragments","value":[{"text":"Room","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Room\/navigatorTitle","value":[{"text":"Room","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/title","value":"RoomSubscription","op":"replace"},{"op":"replace","value":[{"text":"RoomSubscription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/fragments"},{"value":[{"text":"RoomSubscription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/navigatorTitle","op":"replace"},{"value":"room:didSubscribePublicationOf:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate~1room(_:didSubscribePublicationOf:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"room:didSubscribePublicationOf:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate~1room(_:didSubscribePublicationOf:)\/fragments"},{"op":"replace","value":"RoomDelegate","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate\/title"},{"op":"replace","value":[{"text":"RoomDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"RoomDelegate"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomDelegate\/navigatorTitle"}]}]}