{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDTX","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"利用する場合、発話していない時の音声通信を停止します。","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"コーデックでOpusが利用される場合は、デフォルトで利用します。","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"利用しない場合は以下のように設定します。","type":"text"}]},{"code":["let codec: Codec = .init(mimeType: \"audio\/opus\")","codec.parameters.useDTX = false","\/\/ and publish with codec options"],"syntax":null,"type":"codeListing"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/skywayroom\/codecparameters\/usedtx"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/codecparameters\/usedtx"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)SKWCodecParameters(py)useDTX","modules":[{"name":"SkyWayRoom"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useDTX","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"useDTX","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","title":"useDTX"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Opus DTXを利用するかどうか"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CodecParameters"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CodecParameters\/useDTX","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CodecParameters":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CodecParameters"}],"url":"\/documentation\/skywayroom\/codecparameters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CodecParameters"}],"type":"topic","title":"CodecParameters","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CodecParameters","abstract":[{"type":"text","text":"コーデックパラメータ"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CodecParameters/useDTX":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useDTX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/skywayroom\/codecparameters\/usedtx","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"useDTX"}],"type":"topic","title":"useDTX","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CodecParameters\/useDTX","abstract":[{"text":"Opus DTXを利用するかどうか","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"useDTX","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"useDTX"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"useDTX","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CodecParameters\/title","value":"SKWCodecParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CodecParameters\/fragments","value":[{"text":"SKWCodecParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CodecParameters\/navigatorTitle","value":[{"kind":"identifier","text":"SKWCodecParameters"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CodecParameters~1useDTX\/title","value":"useDTX","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CodecParameters~1useDTX\/fragments","value":[{"text":"useDTX","kind":"identifier"}],"op":"replace"}]}]}