{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/roomsubscriptiondelegate\/subscription(_:didattach:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/roomsubscriptiondelegate\/subscription(_:didattach:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscription"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"subscription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RoomSubscription","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription"},{"text":", ","kind":"text"},{"text":"didAttach","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"stream","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"RemoteStream","preciseIdentifier":"c:objc(cs)SKWRemoteStream","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteStream"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"RoomSubscription","type":"text"}],"type":"paragraph"}],"name":"subscription"},{"content":[{"inlineContent":[{"text":"RemoteStream","type":"text"}],"type":"paragraph"}],"name":"stream"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"LocalMember.subscribe(publicationId:options:)"},{"text":"の返り値のSubscriptionについては既にRemoteStreamが入っているため、delegateを設定してもコールされません。","type":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscriptionDelegate"]]},"metadata":{"externalID":"c:@M@SkyWayRoom@objc(pl)RoomSubscriptionDelegate(im)subscription:didAttach:","modules":[{"name":"SkyWayRoom"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"subscription","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription","text":"RoomSubscription"},{"text":", ","kind":"text"},{"text":"didAttach","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWRemoteStream","text":"RemoteStream"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"subscription:didAttach:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"subscription(_:didAttach:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscriptionDelegate\/subscription(_:didAttach:)"},"abstract":[{"text":"RoomSubscriptionにRemoteStreamが入ったことを通知するイベント","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscriptionDelegate/subscription(_:didAttach:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscription","kind":"identifier"},{"text":"(","kind":"text"},{"text":"RoomSubscription","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription"},{"text":", ","kind":"text"},{"text":"didAttach","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RemoteStream","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWRemoteStream"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/roomsubscriptiondelegate\/subscription(_:didattach:)","role":"symbol","navigatorTitle":[{"text":"subscription:didAttach:","kind":"identifier"}],"type":"topic","title":"subscription(_:didAttach:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscriptionDelegate\/subscription(_:didAttach:)","abstract":[{"type":"text","text":"RoomSubscriptionにRemoteStreamが入ったことを通知するイベント"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscription":{"url":"\/documentation\/skywayroom\/roomsubscription","navigatorTitle":[{"kind":"identifier","text":"RoomSubscription"}],"type":"topic","kind":"symbol","title":"RoomSubscription","abstract":[{"text":"Room SDK におけるSubscription","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RoomSubscription","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscriptionDelegate":{"url":"\/documentation\/skywayroom\/roomsubscriptiondelegate","navigatorTitle":[{"kind":"identifier","text":"RoomSubscriptionDelegate"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"RoomSubscriptionイベントデリゲート"}],"title":"RoomSubscriptionDelegate","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscriptionDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RoomSubscriptionDelegate","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteStream":{"url":"\/documentation\/skywayroom\/remotestream","navigatorTitle":[{"kind":"identifier","text":"RemoteStream"}],"type":"topic","kind":"symbol","title":"RemoteStream","abstract":[{"text":"抽象RemoteStreamクラス","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteStream","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteStream"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"subscription:didAttach:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"subscription:didAttach:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"subscription:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RoomSubscription","text":"RoomSubscription","kind":"typeIdentifier","preciseIdentifier":"c:@M@SkyWayRoom@objc(cs)RoomSubscription"},{"text":" *) ","kind":"text"},{"text":"subscription","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didAttach:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteStream","text":"SKWRemoteStream","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWRemoteStream"},{"text":" *) ","kind":"text"},{"text":"stream","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"subscription","content":[{"inlineContent":[{"type":"text","text":"RoomSubscription"}],"type":"paragraph"}]},{"name":"stream","content":[{"inlineContent":[{"type":"text","text":"RemoteStream"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"subscription:didAttach:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscriptionDelegate~1subscription(_:didAttach:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"subscription:didAttach:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscriptionDelegate~1subscription(_:didAttach:)\/fragments"},{"op":"replace","value":"RoomSubscription","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/title"},{"op":"replace","value":[{"text":"RoomSubscription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/fragments"},{"op":"replace","value":[{"text":"RoomSubscription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription\/navigatorTitle"},{"op":"replace","value":"RoomSubscriptionDelegate","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscriptionDelegate\/title"},{"op":"replace","value":[{"text":"RoomSubscriptionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscriptionDelegate\/fragments"},{"op":"replace","value":[{"text":"RoomSubscriptionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscriptionDelegate\/navigatorTitle"},{"op":"replace","value":"SKWRemoteStream","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteStream\/title"},{"op":"replace","value":[{"text":"SKWRemoteStream","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteStream\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SKWRemoteStream"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteStream\/navigatorTitle"}]}]}