{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/logger\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/logger\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LoggerDelegate","text":"LoggerDelegate","preciseIdentifier":"c:objc(pl)SKWLoggerDelegate","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Logger"]]},"metadata":{"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SKWLoggerDelegate","text":"LoggerDelegate"},{"kind":"text","text":")?"}],"externalID":"c:objc(cs)SKWLogger(cpy)delegate","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","symbolKind":"property"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Logger\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"イベントデリゲート"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Logger":{"url":"\/documentation\/skywayroom\/logger","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"type":"topic","kind":"symbol","title":"Logger","abstract":[{"type":"text","text":"内部Swiftモジュール向けロガークラス"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Logger/delegate":{"url":"\/documentation\/skywayroom\/logger\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"type":"topic","kind":"symbol","title":"delegate","abstract":[{"type":"text","text":"イベントデリゲート"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Logger\/delegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SKWLoggerDelegate","text":"LoggerDelegate"},{"kind":"text","text":")?"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LoggerDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerDelegate","kind":"identifier"}],"url":"\/documentation\/skywayroom\/loggerdelegate","role":"symbol","navigatorTitle":[{"text":"LoggerDelegate","kind":"identifier"}],"type":"topic","title":"LoggerDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LoggerDelegate","abstract":[{"type":"text","text":"Loggerイベントデリゲート"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"delegate","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<SKWLoggerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SKWLoggerDelegate"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SKWLogger","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Logger\/title","op":"replace"},{"value":[{"text":"SKWLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Logger\/fragments","op":"replace"},{"value":[{"text":"SKWLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Logger\/navigatorTitle","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Logger~1delegate\/title","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Logger~1delegate\/fragments","op":"replace"},{"value":"SKWLoggerDelegate","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LoggerDelegate\/title","op":"replace"},{"value":[{"text":"SKWLoggerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LoggerDelegate\/fragments","op":"replace"},{"value":[{"text":"SKWLoggerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LoggerDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}