{
  "abstract": [
    {
      "inlineContent": [
        {
          "text": "Version: 1.1.0",
          "type": "text"
        }
      ],
      "type": "strong"
    },
    {
      "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      []
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "SkyWayAINoiseCanceller",
    "modules": [
      {
        "name": "SkyWayAINoiseCanceller"
      }
    ],
    "role": "collection",
    "roleHeading": "Framework",
    "symbolKind": "module",
    "title": "SkyWayAINoiseCanceller"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SkyWay AI Noise Canceller は音声ノイズを抑制し、快適な通話を実現するためのライブラリです。",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "AINoiseCanceller は ",
              "type": "text"
            },
            {
              "code": "SkyWayRoom",
              "type": "codeVoice"
            },
            {
              "text": " ライブラリを利用しています。",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://ios-sdk.api-reference.skyway.ntt.com/room/",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 1.1.0",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayAINoiseCanceller",
      "type": "topic",
      "url": "/documentation/skywayainoisecanceller"
    },
    "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/ErrorCode": {
      "abstract": [
        {
          "code": "SkyWayNoiseCanceller.fatalErrorHandler",
          "type": "codeVoice"
        },
        {
          "text": " が呼ばれる際に渡されるエラーコード",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/ErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "role": "symbol",
      "title": "ErrorCode",
      "type": "topic",
      "url": "/documentation/skywayainoisecanceller/errorcode"
    },
    "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/ModelType": {
      "abstract": [
        {
          "text": "使用するAIノイズキャンセルモデルの種類を表します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModelType"
        }
      ],
      "identifier": "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/ModelType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ModelType"
        }
      ],
      "role": "symbol",
      "title": "ModelType",
      "type": "topic",
      "url": "/documentation/skywayainoisecanceller/modeltype"
    },
    "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayAINoiseCancellerVersionNumber": {
      "abstract": [
        {
          "text": "Project version number for SkyWayAINoiseCanceller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SkyWayAINoiseCancellerVersionNumber"
        }
      ],
      "identifier": "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayAINoiseCancellerVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "SkyWayAINoiseCancellerVersionNumber",
      "type": "topic",
      "url": "/documentation/skywayainoisecanceller/skywayainoisecancellerversionnumber"
    },
    "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayAINoiseCancellerVersionString": {
      "abstract": [
        {
          "text": "Project version string for SkyWayAINoiseCanceller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SkyWayAINoiseCancellerVersionString"
        }
      ],
      "identifier": "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayAINoiseCancellerVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "SkyWayAINoiseCancellerVersionString",
      "type": "topic",
      "url": "/documentation/skywayainoisecanceller/skywayainoisecancellerversionstring"
    },
    "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayNoiseCanceller": {
      "abstract": [
        {
          "text": "ノイズ抑制クラス",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SkyWayNoiseCanceller"
        }
      ],
      "identifier": "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayNoiseCanceller",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SkyWayNoiseCanceller"
        }
      ],
      "role": "symbol",
      "title": "SkyWayNoiseCanceller",
      "type": "topic",
      "url": "/documentation/skywayainoisecanceller/skywaynoisecanceller"
    },
    "https://ios-sdk.api-reference.skyway.ntt.com/room/": {
      "identifier": "https://ios-sdk.api-reference.skyway.ntt.com/room/",
      "title": "Room SDK",
      "titleInlineContent": [
        {
          "text": "Room SDK",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://ios-sdk.api-reference.skyway.ntt.com/room/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayNoiseCanceller"
      ],
      "title": "Classes"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/ErrorCode",
        "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/ModelType"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Variables",
              "generated": true,
              "identifiers": [
                "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayAINoiseCancellerVersionNumber",
                "doc://com.ntt.skyway.ai-noise-canceller/documentation/SkyWayAINoiseCanceller/SkyWayAINoiseCancellerVersionString"
              ],
              "title": "Variables"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayainoisecanceller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayainoisecanceller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
