{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attach","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWCameraPreviewView","text":"CameraPreviewView","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"描画を行うView","type":"text"}],"type":"paragraph"}],"name":"view"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"映像を表示するためには","type":"text"},{"type":"codeVoice","code":"startCapturing(with:options:completion:)"},{"text":"をコールする必要があります。","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/cameravideosource\/attach(_:)"]},{"paths":["\/documentation\/skywayroom\/cameravideosource\/attach(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"attachView:","kind":"identifier"}],"title":"attach(_:)","externalID":"c:objc(cs)SKWCameraVideoSource(im)attachView:","symbolKind":"method","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attach","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWCameraPreviewView","text":"CameraPreviewView","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"カメラのプレビューを"},{"type":"codeVoice","code":"SKWCameraPreviewView"},{"type":"text","text":"に描画します。"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraVideoSource"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraVideoSource\/attach(_:)","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraVideoSource":{"url":"\/documentation\/skywayroom\/cameravideosource","navigatorTitle":[{"text":"CameraVideoSource","kind":"identifier"}],"type":"topic","kind":"symbol","title":"CameraVideoSource","abstract":[{"type":"text","text":"カメラ映像入力ソース"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraVideoSource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraVideoSource","kind":"identifier"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraVideoSource/attach(_:)":{"url":"\/documentation\/skywayroom\/cameravideosource\/attach(_:)","navigatorTitle":[{"kind":"identifier","text":"attachView:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"カメラのプレビューを"},{"type":"codeVoice","code":"SKWCameraPreviewView"},{"type":"text","text":"に描画します。"}],"title":"attach(_:)","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraVideoSource\/attach(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attach"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWCameraPreviewView","text":"CameraPreviewView"},{"kind":"text","text":")"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraPreviewView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewView","kind":"identifier"}],"url":"\/documentation\/skywayroom\/camerapreviewview","role":"symbol","navigatorTitle":[{"text":"CameraPreviewView","kind":"identifier"}],"type":"topic","title":"CameraPreviewView","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView","abstract":[{"type":"text","text":"カメラプレビュー用View"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"attachView:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"attachView:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"attachView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKWCameraPreviewView","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraPreviewView","preciseIdentifier":"c:objc(cs)SKWCameraPreviewView"},{"text":" *) ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"描画を行うView"}],"type":"paragraph"}],"name":"view"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource\/title","value":"SKWCameraVideoSource","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource\/fragments","value":[{"text":"SKWCameraVideoSource","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource\/navigatorTitle","value":[{"kind":"identifier","text":"SKWCameraVideoSource"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource~1attach(_:)\/title","value":"attachView:","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource~1attach(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"attachView:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/title","value":"SKWCameraPreviewView"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/fragments","value":[{"text":"SKWCameraPreviewView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraPreviewView\/navigatorTitle","value":[{"kind":"identifier","text":"SKWCameraPreviewView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}