{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/cameravideosource\/change(_:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/cameravideosource\/change(_:completion:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"change"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil)"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"change"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"切り替え先のカメラデバイス","type":"text"}],"type":"paragraph"}],"name":"device"},{"content":[{"inlineContent":[{"text":"完了コールバック","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"この切り替えはキャプチャ中でも可能です。","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraVideoSource"]]},"metadata":{"modules":[{"name":"SkyWayRoom"}],"externalID":"c:objc(cs)SKWCameraVideoSource(im)changeDevice:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"change","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"changeDevice:completion:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"change(_:completion:)"},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraVideoSource\/change(_:completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"カメラデバイスを切り替えます。","type":"text"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWCameraVideoSourceChangeDeviceCompletion":{"url":"\/documentation\/skywayroom\/skwcameravideosourcechangedevicecompletion","navigatorTitle":[{"kind":"identifier","text":"SKWCameraVideoSourceChangeDeviceCompletion"}],"type":"topic","kind":"symbol","title":"SKWCameraVideoSourceChangeDeviceCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWCameraVideoSourceChangeDeviceCompletion","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWCameraVideoSourceChangeDeviceCompletion"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraVideoSource/change(_:completion:)":{"url":"\/documentation\/skywayroom\/cameravideosource\/change(_:completion:)","navigatorTitle":[{"kind":"identifier","text":"changeDevice:completion:"}],"type":"topic","kind":"symbol","title":"change(_:completion:)","abstract":[{"text":"カメラデバイスを切り替えます。","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraVideoSource\/change(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"change"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/CameraVideoSource":{"url":"\/documentation\/skywayroom\/cameravideosource","navigatorTitle":[{"text":"CameraVideoSource","kind":"identifier"}],"type":"topic","kind":"symbol","title":"CameraVideoSource","abstract":[{"type":"text","text":"カメラ映像入力ソース"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/CameraVideoSource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraVideoSource","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"changeDevice:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeDevice:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"changeDevice:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"text":" *) ","kind":"text"},{"text":"device","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWCameraVideoSourceChangeDeviceCompletion","text":"SKWCameraVideoSourceChangeDeviceCompletion","kind":"typeIdentifier","preciseIdentifier":"c:SKWCameraVideoSource.h@T@SKWCameraVideoSourceChangeDeviceCompletion"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"切り替え先のカメラデバイス"}],"type":"paragraph"}],"name":"device"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"完了コールバック","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceChangeDeviceCompletion\/title","value":"SKWCameraVideoSourceChangeDeviceCompletion"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceChangeDeviceCompletion\/fragments","value":[{"kind":"identifier","text":"SKWCameraVideoSourceChangeDeviceCompletion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWCameraVideoSourceChangeDeviceCompletion\/navigatorTitle","value":[{"kind":"identifier","text":"SKWCameraVideoSourceChangeDeviceCompletion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource~1change(_:completion:)\/title","value":"changeDevice:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource~1change(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"changeDevice:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource\/title","value":"SKWCameraVideoSource"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource\/fragments","value":[{"text":"SKWCameraVideoSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1CameraVideoSource\/navigatorTitle","value":[{"text":"SKWCameraVideoSource","kind":"identifier"}]}]}]}