{
  "abstract": [
    {
      "text": "LocalRoomMemberがPublicationをUnsubscribeした後にコールされます。",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnsubscribePublicationOf:)"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "c:@M@SkyWayRoom@objc(pl)LocalRoomMemberDelegate(im)localRoomMember:didUnsubscribePublicationOf:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "localRoomMember"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)LocalRoomMember",
        "text": "LocalRoomMember"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "didUnsubscribePublicationOf"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomSubscription",
        "text": "RoomSubscription"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "localRoomMember:didUnsubscribePublicationOf:"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "localRoomMember(_:didUnsubscribePublicationOf:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@objc"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "localRoomMember"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "member"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)LocalRoomMember",
              "text": "LocalRoomMember"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "didUnsubscribePublicationOf"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "subscription"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomSubscription",
              "text": "RoomSubscription"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Member",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "member"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Unsubscribeした時のSubscription",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "subscription"
        }
      ]
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.6.1",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember": {
      "abstract": [
        {
          "text": "RoomのLocalMember",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalRoomMember"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalRoomMember"
        }
      ],
      "role": "symbol",
      "title": "LocalRoomMember",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommember"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate": {
      "abstract": [
        {
          "text": "LocalRoomMemberイベントデリゲート",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LocalRoomMemberDelegate"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LocalRoomMemberDelegate"
        }
      ],
      "role": "symbol",
      "title": "LocalRoomMemberDelegate",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommemberdelegate"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnsubscribePublicationOf:)": {
      "abstract": [
        {
          "text": "LocalRoomMemberがPublicationをUnsubscribeした後にコールされます。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localRoomMember"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)LocalRoomMember",
          "text": "LocalRoomMember"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUnsubscribePublicationOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomSubscription",
          "text": "RoomSubscription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMemberDelegate/localRoomMember(_:didUnsubscribePublicationOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localRoomMember:didUnsubscribePublicationOf:"
        }
      ],
      "role": "symbol",
      "title": "localRoomMember(_:didUnsubscribePublicationOf:)",
      "type": "topic",
      "url": "/documentation/skywayroom/localroommemberdelegate/localroommember(_:didunsubscribepublicationof:)"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscription": {
      "abstract": [
        {
          "text": "Room SDK におけるSubscription",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RoomSubscription"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RoomSubscription"
        }
      ],
      "role": "symbol",
      "title": "RoomSubscription",
      "type": "topic",
      "url": "/documentation/skywayroom/roomsubscription"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "localRoomMember:didUnsubscribePublicationOf:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localRoomMember:didUnsubscribePublicationOf:"
            }
          ]
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "localRoomMember:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalRoomMember",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)LocalRoomMember",
                    "text": "LocalRoomMember"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "member"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "didUnsubscribePublicationOf:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/RoomSubscription",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@M@SkyWayRoom@objc(cs)RoomSubscription",
                    "text": "RoomSubscription"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "subscription"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Member",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "member"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Unsubscribeした時のSubscription",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "subscription"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription/title",
          "value": "RoomSubscription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RoomSubscription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "RoomSubscription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate/title",
          "value": "LocalRoomMemberDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMemberDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/title",
          "value": "LocalRoomMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMember/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LocalRoomMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didUnsubscribePublicationOf:)/title",
          "value": "localRoomMember:didUnsubscribePublicationOf:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalRoomMemberDelegate~1localRoomMember(_:didUnsubscribePublicationOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "localRoomMember:didUnsubscribePublicationOf:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/localroommemberdelegate/localroommember(_:didunsubscribepublicationof:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/skywayroom/localroommemberdelegate/localroommember(_:didunsubscribepublicationof:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
