{"kind":"symbol","abstract":[{"type":"text","text":"Channelに参加し、LocalPersonを作成します。"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"join","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"init","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWMemberInit","text":"MemberInit"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPerson","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWLocalPerson","text":"LocalPerson"},{"kind":"text","text":"?, (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil)"}]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"join","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"init","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MemberInit","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit","preciseIdentifier":"c:objc(cs)SKWMemberInit","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"LocalPerson","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPerson","preciseIdentifier":"c:objc(cs)SKWLocalPerson"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"LocalPerson初期化オプション","type":"text"}],"type":"paragraph"}],"name":"init"},{"content":[{"inlineContent":[{"type":"text","text":"完了コールバック"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/skywayroom\/channel\/join(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/channel\/join(with:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Channel\/join(with:completion:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","title":"join(with:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"join","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MemberInit","preciseIdentifier":"c:objc(cs)SKWMemberInit","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:objc(cs)SKWLocalPerson","text":"LocalPerson","kind":"typeIdentifier"},{"text":"?, (any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"joinWithInit:completion:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)SKWChannel(im)joinWithInit:completion:","modules":[{"name":"SkyWayRoom"}]},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Channel"]]},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberInit":{"url":"\/documentation\/skywayroom\/memberinit","type":"topic","abstract":[{"type":"text","text":"Member初期化オプション"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MemberInit","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit","title":"MemberInit","navigatorTitle":[{"text":"MemberInit","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/LocalPerson":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocalPerson"}],"url":"\/documentation\/skywayroom\/localperson","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LocalPerson"}],"type":"topic","title":"LocalPerson","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/LocalPerson","abstract":[{"text":"このSDKで生成されたLocalMember","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/SKWChannelJoinCompletion":{"url":"\/documentation\/skywayroom\/skwchanneljoincompletion","navigatorTitle":[{"kind":"identifier","text":"SKWChannelJoinCompletion"}],"type":"topic","kind":"symbol","title":"SKWChannelJoinCompletion","abstract":[],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelJoinCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKWChannelJoinCompletion"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel/join(with:completion:)":{"kind":"symbol","title":"join(with:completion:)","abstract":[{"type":"text","text":"Channelに参加し、LocalPersonを作成します。"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"join"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MemberInit","preciseIdentifier":"c:objc(cs)SKWMemberInit"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"LocalPerson","preciseIdentifier":"c:objc(cs)SKWLocalPerson"},{"kind":"text","text":"?, (any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Channel\/join(with:completion:)","navigatorTitle":[{"kind":"identifier","text":"joinWithInit:completion:"}],"role":"symbol","type":"topic","url":"\/documentation\/skywayroom\/channel\/join(with:completion:)"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Channel":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Channel"}],"url":"\/documentation\/skywayroom\/channel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Channel"}],"type":"topic","title":"Channel","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Channel","abstract":[{"type":"text","text":"チャンネル"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"joinWithInit:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"joinWithInit:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"joinWithInit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SKWMemberInit","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberInit","preciseIdentifier":"c:objc(cs)SKWMemberInit","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"init","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/SKWChannelJoinCompletion","text":"SKWChannelJoinCompletion","preciseIdentifier":"c:SKWChannel.h@T@SKWChannelJoinCompletion","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"init","content":[{"inlineContent":[{"text":"LocalPerson初期化オプション","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"完了コールバック","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"SKWMemberInit","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SKWMemberInit"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit\/fragments","op":"replace"},{"value":[{"text":"SKWMemberInit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberInit\/navigatorTitle","op":"replace"},{"value":"SKWLocalPerson","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson\/title","op":"replace"},{"value":[{"text":"SKWLocalPerson","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SKWLocalPerson"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1LocalPerson\/navigatorTitle","op":"replace"},{"value":"SKWChannelJoinCompletion","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelJoinCompletion\/title","op":"replace"},{"value":[{"text":"SKWChannelJoinCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelJoinCompletion\/fragments","op":"replace"},{"value":[{"text":"SKWChannelJoinCompletion","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1SKWChannelJoinCompletion\/navigatorTitle","op":"replace"},{"value":"joinWithInit:completion:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1join(with:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"joinWithInit:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel~1join(with:completion:)\/fragments","op":"replace"},{"value":"SKWChannel","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel\/title","op":"replace"},{"value":[{"text":"SKWChannel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel\/fragments","op":"replace"},{"value":[{"text":"SKWChannel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Channel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}