{"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ForwardingConfigure"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SkyWayRoom"}],"title":"maxSubscribers","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxSubscribers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"maxSubscribers"}],"externalID":"c:objc(cs)SKWForwardingConfigure(py)maxSubscribers"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"フォワードしたPublicationをSubscribeできる最大人数"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxSubscribers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"デフォルトは10人で、最大値は99です。詳しくはこちらをご覧ください。"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"https:\/\/skyway.ntt.com\/ja\/docs\/user-guide\/sfu\/"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/skywayroom\/forwardingconfigure\/maxsubscribers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/forwardingconfigure\/maxsubscribers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ForwardingConfigure\/maxSubscribers","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ForwardingConfigure/maxSubscribers":{"url":"\/documentation\/skywayroom\/forwardingconfigure\/maxsubscribers","navigatorTitle":[{"kind":"identifier","text":"maxSubscribers"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"フォワードしたPublicationをSubscribeできる最大人数"}],"title":"maxSubscribers","role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ForwardingConfigure\/maxSubscribers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxSubscribers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/ForwardingConfigure":{"url":"\/documentation\/skywayroom\/forwardingconfigure","navigatorTitle":[{"kind":"identifier","text":"ForwardingConfigure"}],"type":"topic","kind":"symbol","title":"ForwardingConfigure","abstract":[{"text":"フォワードコンフィグ","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/ForwardingConfigure","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForwardingConfigure"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"maxSubscribers","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"maxSubscribers","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"maxSubscribers","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ForwardingConfigure~1maxSubscribers\/title","value":"maxSubscribers","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ForwardingConfigure~1maxSubscribers\/fragments","value":[{"text":"maxSubscribers","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ForwardingConfigure\/title","value":"SKWForwardingConfigure","op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ForwardingConfigure\/fragments","value":[{"text":"SKWForwardingConfigure","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1ForwardingConfigure\/navigatorTitle","value":[{"text":"SKWForwardingConfigure","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}