{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/skywayroom\/microphoneaudiosource\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/microphoneaudiosource\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"externalID":"c:objc(cs)SKWMicrophoneAudioSource(im)init","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MicrophoneAudioSource"]]},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MicrophoneAudioSource\/init()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"イニシャライザ"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MicrophoneAudioSource/init()":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/skywayroom\/microphoneaudiosource\/init()","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init()","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MicrophoneAudioSource\/init()","abstract":[{"text":"イニシャライザ","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MicrophoneAudioSource":{"url":"\/documentation\/skywayroom\/microphoneaudiosource","type":"topic","abstract":[{"type":"text","text":"マイク入力ソース"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MicrophoneAudioSource","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MicrophoneAudioSource","title":"MicrophoneAudioSource","navigatorTitle":[{"text":"MicrophoneAudioSource","kind":"identifier"}],"kind":"symbol"},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MicrophoneAudioSource~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MicrophoneAudioSource~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MicrophoneAudioSource\/title","value":"SKWMicrophoneAudioSource"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MicrophoneAudioSource\/fragments","value":[{"kind":"identifier","text":"SKWMicrophoneAudioSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MicrophoneAudioSource\/navigatorTitle","value":[{"kind":"identifier","text":"SKWMicrophoneAudioSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}