{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/skywayroom\/remotedatastreamdelegate\/datastream(_:didreceive:)-7f2zw"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/skywayroom\/remotedatastreamdelegate\/datastream(_:didreceive:)-7f2zw"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"RemoteDataStream","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStream","preciseIdentifier":"c:objc(cs)SKWRemoteDataStream"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"対象のDataStream"}]}],"name":"dataStream"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"受信した文字列"}]}],"name":"string"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWRemoteDataStream","text":"RemoteDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)SKWRemoteDataStreamDelegate(im)dataStream:didReceiveString:","role":"symbol","modules":[{"name":"SkyWayRoom"}],"navigatorTitle":[{"text":"dataStream:didReceiveString:","kind":"identifier"}],"title":"dataStream(_:didReceive:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate\/dataStream(_:didReceive:)-7f2zw"},"abstract":[{"type":"text","text":"文字列情報を受信した時にコールされるイベント"}],"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteDataStreamDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RemoteDataStreamDelegate","kind":"identifier"}],"url":"\/documentation\/skywayroom\/remotedatastreamdelegate","role":"symbol","navigatorTitle":[{"text":"RemoteDataStreamDelegate","kind":"identifier"}],"type":"topic","title":"RemoteDataStreamDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate","abstract":[{"type":"text","text":"RemoteDataStreamイベントデリゲート"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteDataStream":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoteDataStream"}],"url":"\/documentation\/skywayroom\/remotedatastream","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RemoteDataStream"}],"type":"topic","title":"RemoteDataStream","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStream","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/RemoteDataStreamDelegate/dataStream(_:didReceive:)-7f2zw":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataStream","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWRemoteDataStream","text":"RemoteDataStream","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/skywayroom\/remotedatastreamdelegate\/datastream(_:didreceive:)-7f2zw","role":"symbol","navigatorTitle":[{"text":"dataStream:didReceiveString:","kind":"identifier"}],"type":"topic","title":"dataStream(_:didReceive:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStreamDelegate\/dataStream(_:didReceive:)-7f2zw","abstract":[{"text":"文字列情報を受信した時にコールされるイベント","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dataStream:didReceiveString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dataStream:didReceiveString:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"dataStream:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/RemoteDataStream","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWRemoteDataStream","text":"SKWRemoteDataStream"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dataStream"},{"text":" ","kind":"text"},{"text":"didReceiveString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"対象のDataStream","type":"text"}]}],"name":"dataStream"},{"name":"string","content":[{"type":"paragraph","inlineContent":[{"text":"受信した文字列","type":"text"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate\/title","value":"SKWRemoteDataStreamDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate\/fragments","value":[{"text":"SKWRemoteDataStreamDelegate","kind":"identifier"}]},{"op":"replace","value":[{"text":"SKWRemoteDataStreamDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate\/navigatorTitle"},{"op":"replace","value":"SKWRemoteDataStream","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStream\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStream\/fragments","value":[{"text":"SKWRemoteDataStream","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStream\/navigatorTitle","value":[{"kind":"identifier","text":"SKWRemoteDataStream"}],"op":"replace"},{"op":"replace","value":"dataStream:didReceiveString:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate~1dataStream(_:didReceive:)-7f2zw\/title"},{"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1RemoteDataStreamDelegate~1dataStream(_:didReceive:)-7f2zw\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dataStream:didReceiveString:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}