{
  "abstract": [
    {
      "text": "仮想背景プロセッサを作成します。",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
        "doc://com.ntt.skyway.room/documentation/SkyWayRoom/VirtualBackgroundProcessor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/VirtualBackgroundProcessor/init(backgroundImage:inferenceInterval:)"
  },
  "kind": "symbol",
  "metadata": {
    "externalID": "s:10SkyWayRoom26VirtualBackgroundProcessorC15backgroundImage17inferenceIntervalACSo7UIImageCSg_s5UInt8Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "backgroundImage"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIImage",
        "text": "UIImage"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "inferenceInterval"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5UInt8V",
        "text": "UInt8"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "SkyWayRoom"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(backgroundImage:inferenceInterval:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "backgroundImage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": "? = nil, "
            },
            {
              "kind": "externalParam",
              "text": "inferenceInterval"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5UInt8V",
              "text": "UInt8"
            },
            {
              "kind": "text",
              "text": " = 2)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "背景として使用する画像。",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " の場合は背景置き換えを行いません。デフォルト: ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": "。",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "backgroundImage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Vision を実行するフレーム間隔。範囲: ",
                  "type": "text"
                },
                {
                  "code": "1...10",
                  "type": "codeVoice"
                },
                {
                  "text": "、デフォルト: ",
                  "type": "text"
                },
                {
                  "code": "2",
                  "type": "codeVoice"
                },
                {
                  "text": "。",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inferenceInterval"
        }
      ]
    }
  ],
  "references": {
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom": {
      "abstract": [
        {
          "inlineContent": [
            {
              "text": "Version: 3.7.0",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": " © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom",
      "kind": "symbol",
      "role": "collection",
      "title": "SkyWayRoom",
      "type": "topic",
      "url": "/documentation/skywayroom"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/VirtualBackgroundProcessor": {
      "abstract": [
        {
          "text": "仮想背景プロセッサ。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VirtualBackgroundProcessor"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/VirtualBackgroundProcessor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VirtualBackgroundProcessor"
        }
      ],
      "role": "symbol",
      "title": "VirtualBackgroundProcessor",
      "type": "topic",
      "url": "/documentation/skywayroom/virtualbackgroundprocessor"
    },
    "doc://com.ntt.skyway.room/documentation/SkyWayRoom/VirtualBackgroundProcessor/init(backgroundImage:inferenceInterval:)": {
      "abstract": [
        {
          "text": "仮想背景プロセッサを作成します。",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "backgroundImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "inferenceInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.ntt.skyway.room/documentation/SkyWayRoom/VirtualBackgroundProcessor/init(backgroundImage:inferenceInterval:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(backgroundImage:inferenceInterval:)",
      "type": "topic",
      "url": "/documentation/skywayroom/virtualbackgroundprocessor/init(backgroundimage:inferenceinterval:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VirtualBackgroundProcessor/title",
          "value": "VirtualBackgroundProcessor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VirtualBackgroundProcessor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VirtualBackgroundProcessor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1VirtualBackgroundProcessor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VirtualBackgroundProcessor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/skywayroom/virtualbackgroundprocessor/init(backgroundimage:inferenceinterval:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
