{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"member","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"member","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Member","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Member","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWMember"},{"text":", ","kind":"text"},{"text":"didUpdateMetadata","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"metatada","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Member"}]}],"name":"member"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"更新後のMetada"}]}],"name":"metatada"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/skywayroom\/memberdelegate\/member(_:didupdatemetadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/memberdelegate\/member(_:didupdatemetadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"member:didUpdateMetadata:"}],"title":"member(_:didUpdateMetadata:)","symbolKind":"method","externalID":"c:objc(pl)SKWMemberDelegate(im)member:didUpdateMetadata:","modules":[{"name":"SkyWayRoom"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"member","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SKWMember","text":"Member","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateMetadata","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Memberのメタデータが更新された時にコールされます。"}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberDelegate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberDelegate\/member(_:didUpdateMetadata:)","interfaceLanguage":"swift"},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Member":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Member"}],"url":"\/documentation\/skywayroom\/member","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Member"}],"type":"topic","title":"Member","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Member","abstract":[{"text":"Channelに入室しているMemberの抽象クラス","type":"text"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberDelegate"}],"url":"\/documentation\/skywayroom\/memberdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MemberDelegate"}],"type":"topic","title":"MemberDelegate","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberDelegate","abstract":[{"type":"text","text":"Memberイベントデリゲート"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/MemberDelegate/member(_:didUpdateMetadata:)":{"url":"\/documentation\/skywayroom\/memberdelegate\/member(_:didupdatemetadata:)","navigatorTitle":[{"text":"member:didUpdateMetadata:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"member(_:didUpdateMetadata:)","abstract":[{"type":"text","text":"Memberのメタデータが更新された時にコールされます。"}],"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/MemberDelegate\/member(_:didUpdateMetadata:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"member"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Member","preciseIdentifier":"c:objc(cs)SKWMember"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateMetadata"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"member:didUpdateMetadata:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"member:didUpdateMetadata:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"member:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Member","preciseIdentifier":"c:objc(cs)SKWMember","text":"SKWMember","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"member","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdateMetadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"metatada","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Member","type":"text"}]}],"name":"member"},{"content":[{"type":"paragraph","inlineContent":[{"text":"更新後のMetada","type":"text"}]}],"name":"metatada"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member\/title","value":"SKWMember"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member\/fragments","value":[{"text":"SKWMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Member\/navigatorTitle","value":[{"text":"SKWMember","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate\/title","value":"SKWMemberDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"SKWMemberDelegate"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SKWMemberDelegate"}],"path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate\/navigatorTitle"},{"op":"replace","value":"member:didUpdateMetadata:","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1member(_:didUpdateMetadata:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1MemberDelegate~1member(_:didUpdateMetadata:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"member:didUpdateMetadata:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}