{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStats","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMemberId","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"memberId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStats","text":"WebRTCStats","preciseIdentifier":"c:objc(cs)SKWWebRTCStats","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/skywayroom\/publication\/getstats(withmemberid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/skywayroom\/publication\/getstats(withmemberid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Publication\/getStats(withMemberId:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SkyWayCore v2.0.0で非推奨となりました。"}]}],"hierarchy":{"paths":[["doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Publication"]]},"metadata":{"symbolKind":"method","title":"getStats(withMemberId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getStats"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withMemberId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"WebRTCStats","preciseIdentifier":"c:objc(cs)SKWWebRTCStats"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"getStatsWithMemberId:","kind":"identifier"}],"externalID":"c:objc(cs)SKWPublication(im)getStatsWithMemberId:","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"SkyWayRoom"}],"platforms":[{"deprecated":true,"beta":false,"message":"SkyWayCore v2.0.0で非推奨となりました。","unavailable":false}]},"references":{"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication/getStats(withMemberId:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStats","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withMemberId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"WebRTCStats","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SKWWebRTCStats"},{"text":"?","kind":"text"}],"url":"\/documentation\/skywayroom\/publication\/getstats(withmemberid:)","role":"symbol","navigatorTitle":[{"text":"getStatsWithMemberId:","kind":"identifier"}],"deprecated":true,"type":"topic","title":"getStats(withMemberId:)","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Publication\/getStats(withMemberId:)","abstract":[]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/Publication":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Publication","kind":"identifier"}],"url":"\/documentation\/skywayroom\/publication","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Publication"}],"type":"topic","title":"Publication","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/Publication","abstract":[{"type":"text","text":"Publication"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom/WebRTCStats":{"url":"\/documentation\/skywayroom\/webrtcstats","navigatorTitle":[{"kind":"identifier","text":"WebRTCStats"}],"type":"topic","kind":"symbol","title":"WebRTCStats","abstract":[],"deprecated":true,"role":"symbol","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStats","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebRTCStats"}]},"doc://com.ntt.skyway.room/documentation/SkyWayRoom":{"kind":"symbol","url":"\/documentation\/skywayroom","role":"collection","type":"topic","title":"SkyWayRoom","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom","abstract":[{"inlineContent":[{"type":"text","text":"Version: 3.6.0"}],"type":"strong"},{"type":"text","text":" © 2026 NTT DOCOMO BUSINESS, Inc. All rights reserved."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":true}]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"getStatsWithMemberId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getStatsWithMemberId:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"SKWWebRTCStats","kind":"typeIdentifier","identifier":"doc:\/\/com.ntt.skyway.room\/documentation\/SkyWayRoom\/WebRTCStats","preciseIdentifier":"c:objc(cs)SKWWebRTCStats"},{"text":" *) ","kind":"text"},{"text":"getStatsWithMemberId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"memberId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SkyWayCore v2.0.0で非推奨となりました。"}]}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1getStats(withMemberId:)\/title","value":"getStatsWithMemberId:"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication~1getStats(withMemberId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getStatsWithMemberId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication\/title","value":"SKWPublication"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication\/fragments","value":[{"text":"SKWPublication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1Publication\/navigatorTitle","value":[{"text":"SKWPublication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStats\/title","value":"SKWWebRTCStats"},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStats\/fragments","value":[{"text":"SKWWebRTCStats","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.ntt.skyway.room~1documentation~1SkyWayRoom~1WebRTCStats\/navigatorTitle","value":[{"text":"SKWWebRTCStats","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}